### ISSUE TITLE
can i use your code for my project?

### ISSUE THREAD

**Issue by pydemo** [dbcli/pgcli#1003]
## Description
I want to add application layer on top of your cli - will have to change 10% or your files.
How do i credit original authors?
Your LICENCE file is not very clear.

**Comment by amjith** [comment]
Our license is a BSD 3 clause. You can do whatever the hell you want with the code. :smile: 

It's nice that you're asking us how to credit, maybe send us a link to your project and list our project in your readme. 

What are you planning to build?

**Comment by pydemo** [comment]
great, thank you!
i'll send the link.
