### ISSUE TITLE
Ctrl-p not going to previous history with multiline queries in history

### ISSUE THREAD

**Issue by petobens** [dbcli/pgcli#1004]
If I paste a multiline query such as 
```
SELECT
  anomaly_date,
  factor_val,
FROM dev_coseries
WHERE insertion_id = 23
  AND anomaly_date = '2019-01-20'
ORDER BY score_value
LIMIT 50;
```
into the prompt and then press `Ctrl-p`  I expect to go to the previous query. However both in Emacs and Vi (normal) mode ctrl-p takes me to the previous  line (i.e I have to repeatedly press `Ctrl-p` until I reach the top of query and only then I go back in history to the previous query).

**Comment by j-bennet** [comment]
@jonathanslenders Can you tell if this is intended behavior?

**Comment by amjith** [comment]
The following snippet in keybindings.py might do the trick. Requires verification. 

```
from prompt_toolkit.filters import has_selection

@key_bindings.add('c-p', filter=~has_selection)
def _(event):
    event.current_buffer.history_backward(count=event.arg)
```

**Comment by petobens** [comment]
@amjith  Can this be added as a default (or optional) binding? I believe it's indeed a sensible  default to have

**Comment by lelit** [comment]
FWIW, PgUp and PgDown seems to do just that.

**Comment by amjith** [comment]
@petobens Yes. I left that comment as a direction for someone interested in contributing a PR. 

The file to add this is https://github.com/dbcli/pgcli/blob/master/pgcli/key_bindings.py
