### ISSUE TITLE
Feature Request: Optional bottom_toolbar

### ISSUE THREAD

**Issue by oblitum** [dbcli/pgcli#1010]
## Description

Hi, I wish to hide/remove/disable the footer with `[F2] Smart Completion: ON  [F3] Multiline: ON   (Semi-colon [;] will end the line) [F4] Vi-mode (I)`, is it possible?

**Comment by oblitum** [comment]
I couldn't find an option for that in the default config.

**Comment by j-bennet** [comment]
You're correct, there's no such option right now.

**Comment by oblitum** [comment]
@j-bennet thanks. For now I'm commenting out [`bottom_toolbar=get_toolbar_tokens`](https://github.com/dbcli/pgcli/blob/f614cef7ed63fd7f2a9c44600f4d3c84f96c59d2/pgcli/main.py#L703). I'll leave as a feature request to have an option around that available.

**Comment by igorkaludjer** [comment]
Duplicate of #939

**Comment by oblitum** [comment]
@igorkaludjer thanks. Closing this one.
