### ISSUE TITLE
humanize rounding down

### ISSUE THREAD

**Issue by apnewberry** [dbcli/pgcli#1015]
pgcli depends on `humanize` which is https://github.com/jmoiron/humanize. 

The current version has a slightly odd behavior of rounding down unexpectedly:

```
In [11]: humanize.naturaltime(datetime.timedelta(seconds=120))                                                                         
Out[11]: '2 minutes ago'

In [12]: humanize.naturaltime(datetime.timedelta(seconds=119.9))                                                                       
Out[12]: 'a minute ago'

```
In the latter case I would have expected 2 minutes instead of 1.

The `humanize` package seems to be unmaintained, the last commit being two years ago. I wonder if dbcli might be a good home for a fork?

**Comment by j-bennet** [comment]
Interesting. Both https://github.com/crsmithdev/arrow and https://github.com/sdispater/pendulum can humanize timespans, and they are actively developed. We could look into switching to one of those. They would both bring some extra requirements (`dateutil`, for one), but I think it would not be a ton.

**Comment by apnewberry** [comment]
I switched from arrow to pendulum after reading https://blog.eustace.io/please-stop-using-arrow.html and I'm *extremely* happy with it. For one thing, Pendulum introduces a Duration type, which seems like what's desired in the common case of asking "how long did this query take".

**Comment by j-bennet** [comment]
Closing via https://github.com/dbcli/pgcli/pull/1199. Yay!
