### ISSUE TITLE
Show when my query is waiting for another query to finish

### ISSUE THREAD

**Issue by ghost** [dbcli/pgcli#1025]
Sometimes I'll issue a command and postgres will have to wait until some other query is finished before starting mine. In this situation, pgcli just waits until the other query is done, and I'm not sure if my query is slow or it's waiting for another query.

When a query that I expect to be fast is stuck, I usually [do](https://medium.com/little-programming-joys/finding-and-killing-long-running-queries-on-postgres-7c4f0449e86d) 

```sql
SELECT
  pid,
  now() - pg_stat_activity.query_start AS duration,
  query,
  state
FROM pg_stat_activity
WHERE (now() - pg_stat_activity.query_start) > interval '5 minutes';
```

to find out if there are any long-running queries that might be blocking mine, and if there are I might kill them, depending on the situation. 

When I'm waiting for another query to finish, or a lock to be released, I wonder if pgcli could indicate that fact, so that I know whether my query is just slow or I should consider dealing with the other query that's blocking me.

**Comment by j-bennet** [comment]
That's an interesting idea. It would not be very difficult to add something to the status bar, like a little counter to show number of active queries running on database, that could be refreshed with a background thread...

**Comment by apnewberry** [comment]
Apparently it's possible to check which queries are blocking which other queries: https://wiki.postgresql.org/wiki/Lock_Monitoring

So if I submit a query and it's blocked I could get an indication that I'm blocked, rather than just that there are other queries going on.
