### ISSUE TITLE
Support 'linestyle unicode' table borders

### ISSUE THREAD

**Issue by jefft** [dbcli/pgcli#1029]
## Description
It would be nice if pgcli supported using unicode symbols for table borders, like psql does if one sets ``\pset linestyle unicode`` in .psqlrc. Compare psql output:

![image](https://user-images.githubusercontent.com/205995/55449512-8d843880-5617-11e9-84f7-777f6b959af6.png)

with equivalent pg_cli:

![image](https://user-images.githubusercontent.com/205995/55449532-a12f9f00-5617-11e9-9ab0-7d304763931d.png)

## Your environment
Ubuntu Linux, pgcli 2.0.2

**Comment by amjith** [comment]
The good news is that we already support this. You can change the table format in the config file `~/.config/pgcli/config` or at runtime using the `\T [fomat_name]`. 

The format you're looking for is called `fancy_grid`.

**Comment by jefft** [comment]
Nice - thanks!

I wonder if {{fancy_grid}} shouldn't be the default? Surely compatibility with ancient terminals isn't a concern (unlike ``psql``), as pgcli's autocomplete and colours already assume a capable terminal. If you're going with unicode, I'd also make ``null_string = '␀'`` the default.

**Comment by amjith** [comment]
We have windows users who use this with cmd.exe where the support for colors and unicode characters are less than stellar. 

It still manages to show the completion menu in those situations but not unicode. Making fancy_grid to be the default will make it less than ideal for those users.

**Comment by j-bennet** [comment]
Closed since the functionality exists.

**Comment by Smylers** [comment]
Unfortunately `fancy_grid` isn't actually equivalent to `psql`'s `unicode` display: it puts a grid line between each row, halving the  number of records that fit on the screen:

`psql` with `unicode` lines:

![image](https://user-images.githubusercontent.com/598534/62204123-761a4980-b384-11e9-8e2a-902cd0c075f9.png)

`pgclie` with `fancy_grid`:

![image](https://user-images.githubusercontent.com/598534/62204160-8a5e4680-b384-11e9-9d24-b54794b2554f.png)

Please can this issue be re-opened for `pgcli` to have a fancy border style that doesn't include grid lines between each item? Thanks

**Comment by waldyrious** [comment]
Commenting to add a reference to [Box Drawing](https://en.wikipedia.org/wiki/Box_Drawing_(Unicode_block)), the actual name of the Unicode block that contains these table-drawing characters, so that people (like me) who search for those terms can find this issue. 🙂

Also, I second @Smylers comment: the inter-row lines take up quite a bit of space, and aren't even consistent with the regular style in `pgcli` itself:

```
mydb> \dt
+----------+--------+--------+---------+
| Schema   | Name   | Type   | Owner   |
|----------+--------+--------+---------|
| public   | Table1 | table  | myuser  |
| public   | Table2 | table  | myuser  |
| public   | Table3 | table  | myuser  |
+----------+--------+--------+---------+
mydb> \T fancy_grid
mydb> \dt
╒══════════╤════════╤════════╤═════════╕
│ Schema   │ Name   │ Type   │ Owner   │
╞══════════╪════════╪════════╪═════════╡
│ public   │ Table1 │ table  │ myuser  │
├──────────┼────────┼────────┼─────────┤
│ public   │ Table2 │ table  │ myuser  │
├──────────┼────────┼────────┼─────────┤
│ public   │ Table3 │ table  │ myuser  │
╘══════════╧════════╧════════╧═════════╛
```

I would instead expect the following:

```
┌──────────┬────────┬────────┬─────────┐
│ Schema   │ Name   │ Type   │ Owner   │
├──────────┼────────┼────────┼─────────┤
│ public   │ Table1 │ table  │ myuser  │
│ public   │ Table2 │ table  │ myuser  │
│ public   │ Table3 │ table  │ myuser  │
└──────────┴────────┴────────┴─────────┘
```

...which is much closer to the ASCII version.

**Comment by waldyrious** [comment]
Update: I now realize that in the context of all available styles (which are [provided](https://github.com/dbcli/cli_helpers/blob/72376a55414e71f84a8d813b26643a39605e3f00/cli_helpers/tabular_output/tabulate_adapter.py#L11) by [python-tabulate](https://github.com/astanin/python-tabulate)), `fancy_grid` is actually a Unicode version of `grid`, which explains the inner lines:

```
mydb> \T grid; \dt
+----------+--------+--------+---------+
| Schema   | Name   | Type   | Owner   |
+==========+========+========+=========+
| public   | Table1 | table  | myuser  |
+----------+--------+--------+---------+
| public   | Table2 | table  | myuser  |
+----------+--------+--------+---------+
| public   | Table3 | table  | myuser  |
+----------+--------+--------+---------+
mydb> \T fancy_grid; \dt
╒══════════╤════════╤════════╤═════════╕
│ Schema   │ Name   │ Type   │ Owner   │
╞══════════╪════════╪════════╪═════════╡
│ public   │ Table1 │ table  │ myuser  │
├──────────┼────────┼────────┼─────────┤
│ public   │ Table2 │ table  │ myuser  │
├──────────┼────────┼────────┼─────────┤
│ public   │ Table3 │ table  │ myuser  │
╘══════════╧════════╧════════╧═════════╛
```

However, I also noticed that the `double` style is [added](https://github.com/dbcli/cli_helpers/blob/72376a55414e71f84a8d813b26643a39605e3f00/cli_helpers/tabular_output/tabulate_adapter.py#L16-L25) by `cli_helpers` on top of `python-tabulate`'s styles. So we could simply add a new format there — called `single`, as a pair to `double`, or `psql_unicode`, as a nod to psql's `\pset linestyle unicode`.

I'll prepare a PR :)

**Comment by mixmastamyk** [comment]
Just installed pgcli on Linux from PyPI and it doesn't have this new style:

    unrecognized format_name "psql_unicode"

Is there anything else I need to do?

**Comment by waldyrious** [comment]
I don't think there's been a release of `cli_helpers` including the changes https://github.com/dbcli/cli_helpers/pull/67, as can be seen in the [changelog](https://github.com/dbcli/cli_helpers/blob/717b7b42cc865215d9baa3ac3f518cce9538a691/CHANGELOG#L4-L8). Only once such a release is made will this functionality be available for PyPI installs.
