### ISSUE TITLE
History search regressions in v2

### ISSUE THREAD

**Issue by owst** [dbcli/pgcli#1031]
# Description
I use `pgcli` in vi and multi-line mode. It seems that history search with an empty query buffer has regressed in v2, possibly due to the `prompt_toolkit` upgrade.

In v1.11.0 if I use history search with ctrl-r, having previously executed multi-line queries, I am shown the full query that matches the pattern. If I press ctrl-r again, I'm shown the full next query that matches. If I press ctrl-c the buffer is set to the first matching query.

In v2.1.0 after pressing ctrl-r and typing a pattern, I only see the _line_ that matches the search pattern, which means it's difficult to identify the correct query from my history. If I press ctrl-r again, the prompt is broken and just shows the pattern, but no matches (pressing ctrl-r again appears to do nothing in this state). If I exit the broken prompt with ctrl-c I'm shown a stacktrace, which I can exit with Enter - then the buffer is set to the first matching query.

# Desired behaviour

Ideally, the history search would behave the same whether or not anything has been typed in the buffer, and regardless of the number of times ctrl-r is pressed, namely:

- Show the full matched query, not just the matching line
- Ctrl-c should return the buffer to the state before ctrl-r was pressed the first time

The first is a regression, but I suppose the latter is a feature request.

# Reproduction

With `~/.config/pgcli/history` containing:
```

# 2019-04-06 00:00:00.000000
+SELECT a
+FROM (VALUES (1, 1), (1, 2)) v(a, b)
+ORDER BY a

# 2019-04-06 00:00:01.000000
+SELECT 1

# 2019-04-06 00:00:02.000000
+SELECT a
+FROM (VALUES (1, 1), (1, 2)) v(a, b)
+ORDER BY a DESC

# 2019-04-06 00:00:03.000000
+SELECT 2

# 2019-04-06 00:00:04.000000
+SELECT b
+FROM (VALUES (1, 1), (1, 2)) v(a, b)
+ORDER BY b

# 2019-04-06 00:00:05.000000
+SELECT 3

# 2019-04-06 00:00:06.000000
+SELECT b
+FROM (VALUES (1, 1), (1, 2)) v(a, b)
+ORDER BY b DESC
```

and an empty query buffer (so no partial query typed):

## `1.11.0`:
After pressing ctrl-r and typing `ORDER` I see:
```
postgres@localhost:postgres> SELECT b
                             FROM (VALUES (1, 1), (1, 2)) v(a, b)
                             ORDER BY b DESC

I-search backward: ORDER
```
pressing ctrl-r again, I see:
```
postgres@localhost:postgres> SELECT b
                             FROM (VALUES (1, 1), (1, 2)) v(a, b)
                             ORDER BY b

I-search backward: ORDER
```
If I press ctrl-c I see:
```
postgres@localhost:postgres> SELECT b
                             FROM (VALUES (1, 1), (1, 2)) v(a, b)
                             ORDER BY b DESC
```

## `2.1.0`:

After pressing ctrl-r and typing `ORDER` I see:
```
(reverse-i-search)`ORDER': ORDER BY b DESC
```
pressing ctrl-r again, I see:
```
ORDER
```
If I press ctrl-c I see:
```
Unhandled exception in event loop:
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/eventloop/posix.py", line 154, in _run_task
    t()
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/eventloop/context.py", line 115, in new_func
    return func(*a, **kw)
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/application/application.py", line 562, in read_from_input
    self.key_processor.process_keys()
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/key_binding/key_processor.py", line 273, in process_keys
    self._process_coroutine.send(key_press)
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/key_binding/key_processor.py", line 180, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/key_binding/key_processor.py", line 323, in _call_handler
    handler.call(event)
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 78, in call
    return self.handler(event)
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/key_binding/bindings/search.py", line 28, in abort_search
    search.stop_search()
  File "/Users/owenstephens/.local/share/virtualenvs/pgcli_2.1.0-g_DKg-2C/lib/python2.7/site-packages/prompt_toolkit/search.py", line 128, in stop_search
    del layout.search_links[search_buffer_control]

Exception <SearchBufferControl buffer=<Buffer(name=u'SEARCH_BUFFER', text=u'ORDER') at 4404687696> at 4404560272>
Press ENTER to continue...
```
If I press enter, I see:
```
postgres@localhost:postgres> SELECT b
                             FROM (VALUES (1, 1), (1, 2)) v(a, b)
                             ORDER BY b DESC
```

## With a non-empty query buffer

If the query buffer is _not_ empty at the point of pressing ctrl-r for the first time, the behaviour is the same in 1.11.0 and 2.1.0:

- If I ctrl-c after typing a pattern, my buffer is reset to its state prior to pressing ctrl-r,
- If I ctrl-c after typing a pattern and pressing ctrl-r again, the buffer is reset to the first matching query

# Your environment

- [x] Please provide your OS and version information.
MacOS 10.13.6
- [x] Please provide your CLI version.
1.11.0 and 2.1.0
- [x] What is the output of ``pip freeze`` command.

`1.11.0`:
```
backports.csv==1.0.7
cli-helpers==1.2.0
Click==7.0
configobj==5.0.6
humanize==0.5.1
pgcli==1.11.0
pgspecial==1.11.5
prompt-toolkit==1.0.15
psycopg2==2.7.7
Pygments==2.3.1
setproctitle==1.1.10
six==1.12.0
sqlparse==0.2.4
tabulate==0.8.3
terminaltables==3.1.0
wcwidth==0.1.7
```
`2.1.0`:
```
backports.csv==1.0.7
cli-helpers==1.2.0
Click==7.0
configobj==5.0.6
humanize==0.5.1
pgcli==2.1.0
pgspecial==1.11.5
prompt-toolkit==2.0.9
psycopg2==2.7.7
Pygments==2.3.1
setproctitle==1.1.10
six==1.12.0
sqlparse==0.2.4
tabulate==0.8.3
terminaltables==3.1.0
wcwidth==0.1.7
```

**Comment by j-bennet** [comment]
That's one well written bug report. Thank you!

**Comment by chocobn69** [comment]
Same problem here.
I started to read code, but it might be prompt_toolkit related bug.

What do you think ?

**Comment by j-bennet** [comment]
>  it might be prompt_toolkit related bug

It looks this way. @jonathanslenders, would you be able to help?

**Comment by chocobn69** [comment]
I tried to play a little on this : 
In this method
```python
# .pyenv/versions/3.7.2/envs/pgcli/lib/python3.7/site-packages/pgcli/main.py (line 766)
def _build_cli(self, history):
...
```

We instantiate a `PromptSession` class with `multiline=pg_is_multiline(self),`

If we force `multiline` to `True` then we can use `ctrl+r` just like it was before new prompt_toolkit (full query print).

Not sure how to implement proper fix. Any idea ?

**Comment by jonathanslenders** [comment]
@owst, do you notice the same bug also in this example: https://github.com/prompt-toolkit/python-prompt-toolkit/blob/2.0/examples/prompts/history/persistent-history.py
If so, it's indeed a bug in prompt_toolkit.

**Comment by owst** [comment]
Hi @jonathanslenders, thanks - with a tweak to add `multiline=True` to the `session.prompt` call in your example, multi-line history search _works_ as expected with `prompt-toolkit==2.0.9` in terms of showing the full "query" after matching a single line.

For the record my test was with:

```python
#!/usr/bin/env python
"""
Simple example of a CLI that keeps a persistent history of all the entered
strings in a file. When you run this script for a second time, pressing
arrow-up will go back in history.
"""
from __future__ import unicode_literals

from prompt_toolkit import PromptSession
from prompt_toolkit.history import FileHistory


def main():
    our_history = FileHistory('.example-history-file')

    # The history needs to be passed to the `PromptSession`. It can't be passed
    # to the `prompt` call because only one history can be used during a
    # session.
    session = PromptSession(history=our_history)

    while True:
        text = session.prompt('Say something: ', multiline=True)
        print('You said: %s' % text)


if __name__ == '__main__':
    main()
```
and my example history in `.example-history-file`, which gives a working multi-line history search

Do you consider it a bug that this sequence:
```
Type 123
Ctrl-R
Type "ORDER"
Ctrl-C
```
returns the prompt to `123`, but:
```
Type 123
Ctrl-R
Type "ORDER"
Ctrl-R
Ctrl-C
```
returns it to the first matching query, deleting `123`? If so I can raise an issue directly on prompt-toolkit.

@j-bennet I guess this means the change in behaviour I observed is down to `pgcli`s use of prompt-toolkit 2.x?

**Comment by j-bennet** [comment]
> I guess this means the change in behaviour I observed is down to pgclis use of prompt-toolkit 2.x?

Yes, upgrading to prompt-toolkit v2 was pretty much the only reason to release pgcli 2.0, and a big deal, since `prompt-toolkit` v2 was rewritten from scratch and not compatible with v1. Later pgcli 2.x versions have comparatively minor changes.
