### ISSUE TITLE
Don't recognize new command

### ISSUE THREAD

**Issue by yihuang** [dbcli/pgcli#1032]
```
> \dE mysql
syntax error at or near "\"
LINE 1: \dE mysql
        ^
```

``\dE`` is used to list foreign tables.

**Comment by j-bennet** [comment]
Did you mean to open this issue in `mycli`?

**Comment by yihuang** [comment]
No, ``\dE`` can be used to list foreign tables in psql, "mysql" is my schema to store foreign tables linked to a mysql through mysql_fdw ;D

**Comment by j-bennet** [comment]
Looks like we don't have this command implemented in `pgspecial`. But we should handle something like this gracefully in `pgcli` (like saying "this command is not implemented" instead of throwing a syntax error).

**Comment by catherinedevlin** [comment]
Submitted https://github.com/dbcli/pgspecial/pull/81
