### ISSUE TITLE
SSL Client Certs Not Reading from uri

### ISSUE THREAD

**Issue by arjntc1** [dbcli/pgcli#1037]
First -- great work on pgcli!  It's so much better than the native cli!

I have no problem connecting to db instances that use SSL when the client certs are in the default location.  When attempting to specify the sslrootcert, sslcert and sslkey, it does not seem to pick up the certs from the uri.

pgcli postgres://user:password@netloc:5432/db?sslmode=verify-ca&sslrootcert=%fullpathtorootcert%&sslcert=%fullpathtoclientcert%&sslkey=%fullpathtoclientkey%

When running the above command, it complains about a missing root.crt in the default client cert location "~/.postgresql".  I connect to a variety of Postgres database instances (each with differing certs and I need to specify certs (vs using the default location).

In addition -- it would be great if the client cert connection parameters were made first rate member parameters (so that you can specify as you would with -h for host/-p for port, etc.).

**Comment by j-bennet** [comment]
Interesting. I'd like to determine if this is a problem with `pgcli` or `psycopg2`. See if you get the same error when you run this in Python console:

```
$ python

import psycopg2
conn = psycopg2.connect(dsn="postgres://<your full dsn string here>")
```

**Comment by dbaty** [comment]
No response from the reporter since 4 years. I am closing this issue.
