### ISSUE TITLE
Vi Mode Does Not Work in pgcli

### ISSUE THREAD

**Issue by csarraille-rpx** [dbcli/pgcli#1038]
## Description
I want to be able to use Vi commands within pgcli.
I have the following setting in my /.config/pgcli/config file: 
vi = True

Problem: Vi mode doesn't really work. F4 key does activate it, but I press "esc" and then "b" to go back one word, and am immediately in Insert mode. 

Current Behavior=
Pressing "esc" and "bb" results in moving back one word + inserting the letter "b" once. 
Expected behavior = 
move back two words.

I have the following in my .inputrc:
set editing-mode vi
set keymap vi-command

... and this in my .bash_profile:
set -o vi

...could there be a conflict?

## Your environment
MacOS 10.14.4
Bash Version = 3.2.57(1)-release
Installed pgcli using Homebrew

pip freeze
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
backports.csv==1.0.7
certifi==2019.3.9
cli-helpers==1.2.0
Click==7.0
configobj==5.0.6
enum34==1.1.6
GDAL==2.4.1
humanize==0.5.1
nose==1.3.7
numpy==1.16.2
pgcli==2.1.0
pgspecial==1.11.5
pipenv==2018.11.26
prompt-toolkit==2.0.9
psycopg2==2.7.7
Pygments==2.3.1
setproctitle==1.1.10
six==1.12.0
sqlparse==0.2.4
tabulate==0.8.3
terminaltables==3.1.0
typing==3.6.6
virtualenv==16.4.3
virtualenv-clone==0.5.3
wcwidth==0.1.7

-------------------------------------------------------------------
pip3 freeze
certifi==2019.3.9
GDAL==2.4.1
nose==1.3.7
numpy==1.16.2
pipenv==2018.11.26
virtualenv==16.4.3
virtualenv-clone==0.5.3

**Comment by csarraille-rpx** [comment]
Vi mode now works.
I tried re-installing pgcli using homebrew and re-starting the terminal... vi mode still did not work.
I tried erasing "set -o vi" from my .bash_rc and re-starting the terminal... vi mode still did not work.

Then, at some point I was using pgcli and was messing around with using "^" to go to the beginning of a line, since the pgcli documentation explicitly says that vi command will work. "you can use ^ to go to the beginning and $ to go to the end of a line..." https://www.pgcli.com/keybindings

Right after I used "^" to go to the beginning of a line (I usually use "0"), all of the normal vi keybindings began to work, and my problem described above was resolved.

**Comment by mikedmcfarland** [comment]
After upgrading to the latest pgcli with brew (a few days ago), my vi-mode stopped working properly. It seems to always be in insert mode, can't seem to escape.

**Comment by j-bennet** [comment]
The fix has been merged into master, but not released. For now, please install `pgcli` from master:

`pip install -U https://github.com/dbcli/pgcli/archive/master.zip`

I'll have a new release out as soon as I can.

**Comment by mikedmcfarland** [comment]
@j-bennet thanks! that worked perfectly!

**Comment by dmcodepogo** [comment]
I had the same issue. Thanks for the quick fix!
