### ISSUE TITLE
no longer works with password containing spaces

### ISSUE THREAD

**Issue by drewthorp** [dbcli/pgcli#1043]
## Description
Since upgrading to version 2.1.0 I get the following error when logging in with a user who's password contains a space :
`invalid dsn: missing "=" after "<???>" in connection info string`
Where `<???>` is the second word of the password. My login command is as follows :
`pgcli --host=<hostname> --port=5432 --dbname=<dbname> --password --username=<username>`

## My environment
iTerm2 v3.2.9
DB running on a local VirtualBox VM (v6.0) with a guest OS of Ubuntu 14.10
Running pgcli from host of MacOS 10.14.4
CLI is Bash version 3.2.57(1)-release (x86_64-apple-darwin18) 
I have no `pip` command (Installed pgcli with brew)

**Comment by j-bennet** [comment]
Fixed via https://github.com/dbcli/pgcli/pull/1045.
