### ISSUE TITLE
\df+ (list functions with additional information) truncates source code at ~350 characters

### ISSUE THREAD

**Issue by zadacka** [dbcli/pgcli#1067]
## Description
using the \df+ backslash command to [list functions with extra information](https://www.postgresql.org/docs/current/app-psql.html) behaves similar to `psql` but appears to limit values in the `Source code` column to 350 characters. This is inconsistent when comparing against the output of `psql` which shows the full value without truncation.

This issue is to consider:
* whether `pgcli` should behave exactly the same as `psql` and do no truncation.
* whether the truncation is sensible (I quite like it) but some warning text could be added to notify the end user that the column value has been restricted. 
* ... or something else entirely would be appropriate (including leaving things as they are)

Here is a mock up of what currently gets displayed:
```
> \df+ some_stored_procedure
 ... +------------------------+-...-+---------------------------------------------------------------------------------------+ ...
 ... | Name                   | ... | Source code                                                                           | ...
 ... +------------------------+-...-+---------------------------------------------------------------------------------------+ ...
 ... | some_stored_procedure  | ... |         SELECT                                                                        | ...
 ... |                        | ... |           col_name                                                                    | ...
 ... |                        | ... |          FROM                                                                         | ...
 ... |                        | ... |           table                                                                       | ...
 ... |                        | ... |          WH       <- this suddenly cuts out, apparent truncation at 350 characters(?) | ...
 ... +------------------------+-...-+---------------------------------------------------------------------------------------+ ...
```

## environment
-- CLI v2.1.1
-- psql 9.6.2 (for behavioural comparison)

**Comment by j-bennet** [comment]
There was a fix in cli_helpers that skips truncation for multi-line strings:

https://github.com/dbcli/cli_helpers/pull/55

e.g. in your case, function text has line breaks in it, so it would not be truncated.

The fix has not been released yet, but you can install `cli_helpers` from master to use it:

pip install -U https://github.com/dbcli/cli_helpers/archive/master.zip

**Comment by zadacka** [comment]
@j-bennet - nice, thanks!
