### ISSUE TITLE
CTRL xe doesn't open my favorite editor

### ISSUE THREAD

**Issue by vianney-g** [dbcli/pgcli#1070]
## Description

In my .zshrc and .bashrc, vim is set as my $EDITOR.
When I type `<ctrl> X E`, I can edit my current line with vim.

But in pgcli REPL, the same command open nano instead of my favorite editor.

When I type \e, vim is launched as expected.

## Your environment

  

- [x] Ubuntu 18.04
- [x] pgcli 2.1.0 on zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
- [x] ``pip freeze``

asn1crypto==0.24.0
cffi==1.12.2
cli-helpers==1.2.0
Click==7.0
configobj==5.0.6
cryptography==2.6.1
humanize==0.5.1
mycli==1.19.0
pgcli==2.1.0
pgspecial==1.11.5
pkg-resources==0.0.0
prompt-toolkit==2.0.9
psycopg2==2.7.7
pycparser==2.19
Pygments==2.3.1
PyMySQL==0.9.3
setproctitle==1.1.10
six==1.12.0
sqlparse==0.2.4
tabulate==0.8.3
terminaltables==3.1.0
wcwidth==0.1.7

**Comment by amjith** [comment]
Hi. I'm not able to reproduce this. Can you try upgrading prompt-toolkit? 

pip install -U prompt-toolkit

**Comment by chagui** [comment]
I could reproduce, however after a quick glance it seems coming from [prompt-toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/5aea076692a304ec2bf8ad18fc59d4885cc462b1/prompt_toolkit/key_binding/bindings/open_in_editor.py#L28-L38) itself?

## Your environment
- [x] Please provide your OS and version information: Ubuntu 20.04
- [x] Please provide your CLI version: 3.1
- [x] What is the output of ``pip freeze`` command.
(pruned out irrelevant part)
```
pgcli==3.1.0
pgspecial==1.12.1
prompt-toolkit==3.0.18
```

**Comment by vianney-g** [comment]
Two years later :D I found an explanation to this bug.

prompt-toolkit choose the editor in buffer._open_file_in_editor function. The $VISUAL is first looked, then $EDITOR.
So if you have 2 different settings for those var, it opens VISUAL. I don't know if it is a bug or a feature, but this is not what I was expected.

**Comment by vianney-g** [comment]
Actually this is not exactly the same bug I described 2 years ago. I can't reproduce the original one after some pip updates.

**Comment by j-bennet** [comment]
> prompt-toolkit choose the editor in buffer._open_file_in_editor function. The $VISUAL is first looked, then $EDITOR.
So if you have 2 different settings for those var, it opens VISUAL. I don't know if it is a bug or a feature, but this is not what I was expected.

Yeah this is not a bug. This behavior may be unexpected and we documented it here:

https://www.pgcli.com/editor

**Comment by j-bennet** [comment]
Same issue as https://github.com/dbcli/pgcli/issues/1235.
