### ISSUE TITLE
Possible Error with Named Queries

### ISSUE THREAD

**Issue by TheCedarPrince** [dbcli/pgcli#1072]
## Description
I have been trying to use the Named Queries feature of pgcli and have not been able to use it correctly. I followed the documentation given in the pgcli website but to no avail, here is an example query that I am trying to make that takes a specific table (replace '$1' with your table name of interest) and displays its first 5 rows:

`\ns head Select * from '$1' limit 5`

I continue to get the error: 

> No named query: head mytable

After I type in `\n head mytable`.

What am I doing wrong? I doubt it is an error with pgcli but I have tried multiple different methods of getting the named query to work - I am able to make named queries work, but they just can't take an input value. 

Thanks for the help! 

## Your environment

- Ubuntu 16.04 LTS
- zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
- pip freeze output (I installed pgcli via apt-get however, Version 0.20.1):

```
asn1crypto==0.24.0
astroid==2.2.5
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
conda==4.6.11
cryptography==2.4.2
idna==2.8
isort==4.3.17
lazy-object-proxy==1.3.1
mccabe==0.6.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pydocstyle==3.0.0
pyflakes==2.1.1
Pygments==2.3.1
pylama==7.7.1
pylama-pylint==3.1.1
pylint==2.3.1
pyOpenSSL==18.0.0
PySocks==1.6.8
requests==2.21.0
ruamel-yaml==0.15.46
six==1.12.0
snowballstemmer==1.2.1
typed-ast==1.3.1
urllib3==1.24.1
wrapt==1.11.1
```

Please let me know if you need any more info

**Comment by j-bennet** [comment]
You should update pgcli from `pip`: `pip install -U pgcli`. It looks like `apt-get` has a very old version.

Also, you don't want to single-quote the table name. Try this (after you update `pgcli`):

`\ns head select * from $1 limit 5`

and then to execute:

`n head mytable`.

**Comment by TheCedarPrince** [comment]
Hey @j-bennet 

That worked perfectly! Maybe make a note for future users that the apt version of pgcli is very old? 

Also, thanks for fixing my named query. : ) Super helpful and am now able to make new queries.

I don't know what exactly happened but if anyone has the same issue, I ended up having to reinstall postgres using a modified command recommended by user "hidemyname" from [this stackoverflow conversation](https://stackoverflow.com/questions/31645550/why-psql-cant-connect-to-server/31647044):

`sudo apt-get --purge remove postgresql\* && sudo apt-get install postgresql postgresql-contrib postgresql-server-dev-9.5 -y`

**JUST BE ADVISED, THIS COMMAND DELETES EVERYTHING ABOUT YOUR POSTGRES INSTALL!**

Followed by:

`pip install -U pgcli`

And there ya go!
