### ISSUE TITLE
Right align numbers

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [dbcli/pgcli#1074]
It is common practice to right align header and values in numeric columns, see for example https://ux.stackexchange.com/q/24066. Or more precisely, align to decimal point.

To reproduce:
```sql
SELECT name, salary FROM employees
```
Expected result:
```
+--------------------+
| name    |   salary |
|---------+----------+
| Alice   |      103 |
| Bob     |       42 |
+--------------------+

```
Actual result:
```
+--------------------+
| name    | salary   |
|---------+----------+
| Alice   | 103      |
| Bob     | 42       |
+--------------------+
```

**Comment by anthonydb** [comment]
👍 Yes, please.

Right-alignment of numbers is default behavior of psql and is much more readable.
