### ISSUE TITLE
Pytest tests missing dependencies

### ISSUE THREAD

**Issue by sebojanko** [dbcli/pgcli#1076]
## Description
After installing `requirements-dev.txt` in a virtual env and running `py.test` I had three missing dependencies:
- `fixtures`
- `testscenarios`
- `testresources`

After installing them manually, these errors disappeared.
Should this packages be added to the `requirements-dev.txt`?

## Your environment
I installed the packages in a new virtual env, as per instructions.

- [x] What is the output of ``pip freeze`` command.
aspy.yaml==1.3.0
autopep8==1.3.3
behave==1.2.6
certifi==2019.6.16
cfgv==2.0.0
chardet==3.0.4
click==6.7
codecov==2.0.15
configparser==3.7.4
contextlib2==0.5.5
coverage==4.3.4
docutils==0.14
enum34==1.1.6
filelock==3.0.12
funcsigs==1.0.2
futures==3.2.0
identify==1.4.5
idna==2.8
importlib-metadata==0.18
importlib-resources==1.0.2
linecache2==1.0.0
mock==3.0.5
nodeenv==1.3.3
packaging==19.0
parse==1.12.0
parse-type==0.4.2
pathlib2==2.3.4
pexpect==3.3
pkginfo==1.5.0.1
pluggy==0.12.0
pre-commit==1.17.0
py==1.8.0
pycodestyle==2.5.0
pyparsing==2.4.0
pytest==3.0.7
PyYAML==5.1.1
requests==2.22.0
requests-toolbelt==0.9.1
scandir==1.10.0
six==1.12.0
toml==0.10.0
tox==3.13.2
tqdm==4.32.2
traceback2==1.4.0
twine==1.11.0
typing==3.7.4
urllib3==1.25.3
virtualenv==16.6.1
zipp==0.5.2
- [x] Please provide your OS and version information.
OS: Mint 18.3 sylvia
Kernel: x86_64 Linux 4.15.0-54-generic

- [x] Please provide your CLI version.
zsh 5.1.1 (x86_64-ubuntu-linux-gnu)

**Comment by sebojanko** [comment]
I now realize I accidentally run the tests on the virtualenv also. The mentioned packages are needed for tests inside the python/site-packages.

I'm therefore closing this issue as this problem does not exist.

**Comment by j-bennet** [comment]
Hmm. You should have your venv activated when running tests. I'm not sure why this is a problem. But glad you resolved it.
