### ISSUE TITLE
move to `psycopg2-binary`?

### ISSUE THREAD

**Issue by ebeseda** [dbcli/pgcli#1080]
## Description
I tried to install your package from pip and got a usual `Error: pg_config executable not found.`
because I don't have `libpq` or `postgres-devel` packages.

I cloned your repo, replaced `psycopg2 >= 2.7.4` with `psycopg2-binary` and installed it with
`python setup.py install` command.
It works like a charm and not requires postgres stuff now.

How about to move to `psycopg2-binary`?

## Your environment
- [x] Please provide your OS and version information.
OS: Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.1.16-1-MANJARO
- [x] Please provide your CLI version.
pgcli==2.1.1
- [x] What is the output of ``pip freeze`` command.
Clean virtualenv with pgcli==2.1.1 installed

**Comment by j-bennet** [comment]
Related: https://github.com/dbcli/pgcli/pull/1060#issuecomment-497190181.

**Comment by jpambrun** [comment]
The proposed workaround in #1060 doesn't work as `pip install pgcli` fails with the above error.

**Comment by j-bennet** [comment]
I already commented on making `psycopg2-binary` the default choice here:

https://github.com/dbcli/pgcli/pull/1059#issuecomment-497193739

Honestly, I have no idea why `psycopg2` maintainers still do not recommend wheels as the default option. At this point, I would really like to switch back to wheels. But I have absolutely no way to tell how many people will be affected / have pgcli broken if we do that. And there seems to be no way to let the user choose which option he wants, source or binary, during pgcli installation.

**Comment by nvarscar** [comment]
This one worked for me as a workaround:
```
pip install pgcli --only-binary psycopg2
```

**Comment by ddimmich** [comment]
Interestingly psycopg2 recommends not using the binary version for production:  http://initd.org/psycopg/docs/install.html#binary-install-from-pypi

> 

> If you are the maintainer of a publish package depending on psycopg2 you shouldn’t use ‘psycopg2-binary’ as a module dependency. For production use you are advised to use the source distribution.

> 

Note

The binary packages come with their own versions of a few C libraries, among which libpq and libssl, which will be used regardless of other libraries available on the client: upgrading the system libraries will not upgrade the libraries used by psycopg2. Please build psycopg2 from source if you want to maintain binary upgradeability. 

This makes sense, as annoying as it is.
