### ISSUE TITLE
\df cannot list functions

### ISSUE THREAD

**Issue by mladenuzelac** [dbcli/pgcli#1081]
## Description
When I am running pgcli and try to list functions using \df I get following error 
`column p.proisagg does not exist
LINE 9:                         WHEN p.proisagg THEN 'agg'
                                     ^
HINT:  Perhaps you meant to reference the column "p.prolang".`

I don't have any issues running the command in `psql`
## Your environment
Debian buster 10, Postgresql 11.4, pgcli 1.9.1. 

![pg_cli_error](https://user-images.githubusercontent.com/673820/61201899-37c72e00-a6e6-11e9-8aec-15eff11fd3a5.png)

**Comment by verfriemelt-dot-org** [comment]
this is due to changed pg catalog tables in version 11.0 but already fixed in pgcli. ( i believe since version 2.0 ? )

**Comment by amjith** [comment]
Can you try upgrading pgcli?

```
pip install -U pgcli
```
