### ISSUE TITLE
Segfault on macos

### ISSUE THREAD

**Issue by qweeze** [dbcli/pgcli#1082]
## Description
pgcli crashes with segmentation fault on some queries:
```
goszakupki@(none):goszakupki> select * from purchase where publish_date > '2019-07-20'::date;
[1]    54595 segmentation fault  pgcli -U goszakupki goszakupki
```
No error after removing where clause:
```
goszakupki@(none):goszakupki> select * from purchase limit 3;
...
```

## Your environment

- System Version: macOS 10.12.5 (16F73)
- pgcli Version: 2.1.1
- pip freeze: 
```
cli-helpers==1.2.1
Click==7.0
configobj==5.0.6
humanize==0.5.1
pgcli==2.1.1
pgspecial==1.11.5
prompt-toolkit==2.0.9
psycopg2==2.8.3
Pygments==2.4.2
setproctitle==1.1.10
six==1.12.0
sqlparse==0.3.0
tabulate==0.8.3
terminaltables==3.1.0
wcwidth==0.1.7
```

**Comment by dbaty** [comment]
This is a very old issue... Do you still have it? If not, we'll close this issue.

**Comment by j-bennet** [comment]
Let's close. Things have changed a lot since 2019, it's not likely we'd reproduce it.
