### ISSUE TITLE
\d takes a huge time to complete

### ISSUE THREAD

**Issue by gantsevdenis** [dbcli/pgcli#1086]
## Description
`\d <tablename>` is way to slow:
```
depl1> \d company                                                        
+------------------+--------------------------+---------------------------------------------+
| Column           | Type                     | Modifiers                                   |
|------------------+--------------------------+---------------------------------------------|
| id               | uuid                     |  not null default public.uuid_generate_v4() |
| created          | timestamp with time zone |  not null default now()                     |
| rows ommitted ...  |                     |                                                           |
+------------------+--------------------------+---------------------------------------------+
Indexes:
    "provider_pkey" PRIMARY KEY, btree (id)
   indexes ommited...
Time: 57.093s (57 seconds), executed in: 57.083s (57 seconds)
```
It took a minute to complete, while psql with the same database and same table completes in a couple of seconds
## Your environment

```
denis:~ $ pgcli --version
/home/denis/anaconda3/lib/python3.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Version: 2.0.2
denis:~ $ uname -a
Linux denis-Aspire-VN7-791G 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
denis:~ $ 
```
- [ ] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment]
@gantsevdenis If you execute the command a few times, do you see the same slow response every time, or is it intermittent?

Also, is the database local or remote?

**Comment by gantsevdenis** [comment]
Hi sorry for the delay
The performance varies wildly, it goes from 6 seconds to 1 min. However, requesting `\d` twice does not speed up the second time. So there are days where it's consistently slow, and there are days where it's consistently kinda fast
The database is remote, accessed through a VPN. I wouldn't account for network speed only though, because I ve made multiple attempts, and my distance from server (Europe vs US) doesn't seem to correlate with response time (at least not to a naked eye obviously...)

`psql`'s `\d` on the other hand, is consistently very fast

**Comment by j-bennet** [comment]
Your log file might help us figure out what takes so long. Can you please do the following:

* set `log_level = DEBUG` in `~/.config/pgcli/config`
* restart pgcli
* run the `\d` command
* attach the log file (`~/.config/pgcli/log` to this issue.

After this is done, feel free to drop log level back to `INFO`.

Thank you for your patience! I hope we solve this eventually.

**Comment by gantsevdenis** [comment]
[log_pgcli.zip](https://github.com/dbcli/pgcli/files/3537364/log_pgcli.zip)

**Comment by j-bennet** [comment]
From your log file, it looks like pgcli does way too many queries on databaase to repeatedly retrieve information on your table. I think this may be related to the issue fixed in this PR:

https://github.com/dbcli/pgspecial/pull/80

This fix was previously unreleased. I just released a new version of `pgspecial` that has it included. Please try updating `pgspecial`:

```
pip installl -U pgspecial
```

You should see version 1.11.6 installed:

```
$ pip freeze | grep pgspecial
pgspecial==1.11.6
```

`pgcli` will need to be restarted for changes to take effect. Let me know if it resolves the problem.

**Comment by gantsevdenis** [comment]
I confirm I have now installed pgspecial 1.11.6 in the same environment as pgcli, but after trying it again, it took 32 seconds

**Comment by j-bennet** [comment]
Can you attach your log file again?

**Comment by gantsevdenis** [comment]
Ok, I understood the pb.. I wans't attentive enough, and actually `pgcli` was installed in `~/anaconda3/bin` instead of `~/anaconda3/envs/myenv/bin`, so even when I switched environments, it didn't affect the context for `pgcli`

I have removed the offending executable, so now it is really executed in virtual env with `pgspecial==1.11.6`.
After executing `\d table` it only took `0.9 seconds`, so I think the ticket could be closed

**Comment by j-bennet** [comment]
@gantsevdenis This is great news, thanks for letting us know! Closing the issue.

🎉

**Comment by j-bennet** [comment]
Fixed in https://github.com/dbcli/pgspecial/pull/80.
