### ISSUE TITLE
colored prompt and commands executed

### ISSUE THREAD

**Issue by verfriemelt-dot-org** [dbcli/pgcli#1088]
it would be nice, to have colors for the pgcli prompt available like the `psql` command has.

for example, this is my prompt in psqlrc which looks more appealing.

```
\set PROMPT1 '%[%33[%0;33m%] 🐘 %`date +"%H:%M:%S"` %[%33[%0;34m%]» %[%33[%0;31m%]%n%[%33[%0;33m%]@%[%33[%0;36m%]%M:%> %[%33[%0;35m%]%x%# %[%33[%0;0m%]'
\set PROMPT2 '%[%33[%0;33m%] 🐘 %R » %[%33[%0;0m%]'
```

the `%` allows you to pass vt color codes thrugh with the `%[` `%]` syntax and even better, with 
 
    %`date`

you can execute commands, which results in a nice colored prompt with the current time.

can we have this in pgcli too?

**Comment by verfriemelt-dot-org** [comment]
i tried to hack that change in like this:

```diff
diff --git a/pgcli/main.py b/pgcli/main.py
index 903966f4..3266f6a8 100644
--- a/pgcli/main.py
+++ b/pgcli/main.py
@@ -82,6 +82,7 @@ import psycopg2
 from collections import namedtuple

 from textwrap import dedent
+from prompt_toolkit.formatted_text import ANSI

 # Ref: https://stackoverflow.com/questions/30425105/filter-special-chars-such-as-color-codes-from-shell-output
 COLOR_CODE_REGEX = re.compile(r"\x1b(\[.*?[@-~]|\].*?(\x07|\x1b\\))")
@@ -777,9 +778,11 @@ class PGCli(object):
                 prompt_format == self.default_prompt
                 and len(prompt) > self.max_len_prompt
             ):
+
                 prompt = self.get_prompt("\\d> ")

-            return [("class:prompt", prompt)]
+
+            return ANSI(prompt)

         def get_continuation(width, line_number, is_soft_wrap):
             continuation = self.multiline_continuation_char * (width - 1) + " "
@@ -1019,7 +1022,11 @@ class PGCli(object):

     def get_prompt(self, string):
         # should be before replacing \\d
+
+        string = '\x1b[33m 🐘 \\t+ \x1b[34m» \x1b[31m\\u\x1b[33m@\x1b[36m\\H:\\p/\\d \x1b[35m» \x1b[0m'
+
         string = string.replace("\\dsn_alias", self.dsn_alias or "")
+        string = string.replace("\\t+", self.now.strftime("%H:%M:%S"))
         string = string.replace("\\t", self.now.strftime("%x %X"))
         string = string.replace("\\u", self.pgexecute.user or "(none)")
         string = string.replace("\\H", self.pgexecute.host or "(none)")

```

i added the `\t+` for timestamps like `16:45:21` which fits my needs and i do not need to add an external program. the prompt itself is hardcoded with colorcodes inserted via `\x1b[33m` for example.

the reason i hardcoded it, is that the escape character is lost when defined in the config and i could not bother, to figure out how to work around this.

maybe someone could pick this up as a startingpoint to use colors for nice promps!

**Comment by verfriemelt-dot-org** [comment]
colored prompts where added in 36605174a4b1aa45fd46788e6cb61c970185b9ea thanks!

**Comment by rightaway** [comment]
Do you think the pull request will be included in the released version? Would be nice to have colored prompts.

**Comment by verfriemelt-dot-org** [comment]
its already been done! check out the last releases.

**Comment by rightaway** [comment]
It's not working for me in that version, the characters from the code above just appear as they are. Could you give an example of a couple of different colors in your prompt and I can try that in mine to see if it works?

**Comment by amjith** [comment]
You can install directly from the master branch using:

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

Here's an example of colored prompt in the config: 

```
prompt = '\x1b[35m\u@\x1b[32m\h:\x1b[36m\d>'
```

`\x1b[` followed by the color code. `35m` for purple, `32m` for green and `36m` for cyan. 

This is what the prompt looks like: 

![image](https://user-images.githubusercontent.com/49260/77861087-c70a6800-71c7-11ea-84fa-932bbd0e138b.png)
