### ISSUE TITLE
Create a standalone pgcli.exe for windows

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#109]
I would love to get some help on creating a single standalone pgcli.exe binary for windows. 

I've heard that it is possible to do that using py2exe, but I don't have personal experience with that.

**Comment by amjith** [comment]
Let's face the facts. This is probably not going to happen.

**Comment by j-bennet** [comment]
Since Microsoft released Bash for Windows, I'd rather advise people to try that.
