### ISSUE TITLE
SyntaxWarnings with Python 3.8

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#1096]
## Description
SyntaxWarnings with Python 3.8

## Your environment

- [x] Windows 10, Python 3.8b3
- [x] pgcli 2.1.1.

```
c:\python\lib\site-packages\pgspecial\dbcommands.py:1504: SyntaxWarning: invalid escape sequence \d
  status.append("Number of child tables: %d (Use \d+ to list"
c:\python\lib\site-packages\pgspecial\main.py:58: SyntaxWarning: invalid escape sequence \p
  'A limited version of traditional \pset', arg_type=PARSED_QUERY)
c:\python\lib\site-packages\pgspecial\main.py:127: SyntaxWarning: invalid escape sequence \h
  message += "\nTry \h with no arguments to see available help."
c:\python\lib\site-packages\pgspecial\iocommands.py:21: SyntaxWarning: invalid escape sequence \e
  """
c:\python\lib\site-packages\pgspecial\iocommands.py:50: SyntaxWarning: invalid escape sequence \s
  match = re.match("(.*?)[\s]*\\\\watch (\d+);?$", command)
c:\python\lib\site-packages\pgspecial\iocommands.py:65: SyntaxWarning: invalid escape sequence \e
  pattern = re.compile('(^\\\e|\\\e$)')
c:\python\lib\site-packages\pgspecial\iocommands.py:176: SyntaxWarning: invalid escape sequence \d
  match = re.search('\\$\d+', query)
```

**Comment by thorstenkampe** [comment]
It looks to me that the issue has probably existed all the time but on Python 3.8 issues that warning. That issue could have easily been intercepted using for instance `pylint` ("Anomalous backslash in string: '\e'. String constant might be missing an r prefix.")

**Comment by amjith** [comment]
@thorstenkampe Thank you for testing this in Python 3.8. 

Would you be open to sending a PR with your suggested fix?

**Comment by thorstenkampe** [comment]
The error is actually in `pgspecial`. With your conset I'm going to clone `pgspecial`, apply the fix and create a pull request.

**Comment by thorstenkampe** [comment]
I had a look at the warnings: the one in `dbcommands.py` is trivial to fix but the ones in `main.py` are not simple strings. They are assembled from throughout `main.py`. Same goes for `iocommands.py`. There are already triple backslashes`\\\` in those strings. Someone who really knows about the desired output needs to have a look at it, sorry.

**Comment by amjith** [comment]
@thorstenkampe Can you open the PR and tag some lines for me to take a look? 

I'll try to get python 3.8 installed and have a look.

**Comment by thorstenkampe** [comment]
`pgspecial` 1.11.6 and 1.11.7 have been released in quick succession. I can't reproduce the issue anymore.
