### ISSUE TITLE
Cannot describe a table using `\d` if it is not in the `public` schema

### ISSUE THREAD

**Issue by jack-pace** [dbcli/pgcli#1105]
## Description
I cannot describe a table using `\d` if it is not in the `public` schema.
E.g.
```psql
> \d myschema.my_table
Did not find any relation named myschema.my_table
```
Doing `select * from myschema.my_table` works, so I am not mistyping it!

Both of the following work for tables in the public schema:
```psql
\d my_other_table
\d public.my_other_table
```

Describing tables in other schemas used to work back in version 0.20.1.

## Your environment

- [x] Please provide your OS and version information.
```sh
$ cat /etc/os-release
NAME="Linux Mint"
VERSION="18.2 (Sonya)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.2"
VERSION_ID="18.2"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sonya
UBUNTU_CODENAME=xenial
```
```sql
select version()
PostgreSQL 9.6.9 on x86_64-pc-linux-gnu (Ubuntu 9.6.9-2.pgdg16.04+1), compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609, 64-bit
```
- [x] Please provide your CLI version.
```sh
$ pgcli --version
Version: 2.1.1
```
- [x] What is the output of ``pip freeze`` command.
```sh
$ pip freeze
cli-helpers==1.2.1
Click==7.0
configobj==5.0.6
humanize==0.5.1
pgcli==2.1.1
pgspecial==1.11.7
prompt-toolkit==2.0.10
psycopg2==2.8.3
Pygments==2.4.2
setproctitle==1.1.10
six==1.12.0
sqlparse==0.3.0
tabulate==0.8.5
terminaltables==3.1.0
wcwidth==0.1.7
```

**Comment by kwakwaversal** [comment]
I am having the same issue. I have nothing else to add to the report above, but if you need to work around it you need to explicitly set the `search_path` to the schema you want to describe. Not great, but something.

```sql
set search_path to myschema;
```

**Comment by gantsevdenis** [comment]
this issue was fixed with https://github.com/dbcli/pgspecial/blob/master/changelog.rst#1118

**Comment by j-bennet** [comment]
Fixed via https://github.com/dbcli/pgspecial/pull/89. You should be good if you update pgspecial (`pip install -U pgspecial`).

**Comment by jack-pace** [comment]
Works - thanks!
