### ISSUE TITLE
PQconninfo not available in libpq < 9.3

### ISSUE THREAD

**Issue by Ian-T-Price** [dbcli/pgcli#1110]
## Description
On running pgcli the above error message is given.
Various people are getting the same error:
https://github.com/psycopg/psycopg2/issues/976
The maintainers suggest that pgcli needs a better work-around

Tried to find & update libpq but I'm not having much success with that - my bad.

## Your environment

- [ Latest AWS Amazon Linux 2 AMI with yum update applied ] Please provide your OS and version information.
- [ Version: 2.1.1 ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.
amazon-linux-extras==1.6.9
aws-cfn-bootstrap==1.4
awscli==1.16.102
Babel==0.9.6
backports.csv==1.0.7
backports.ssl-match-hostname==3.5.0.1
botocore==1.12.92
cffi==1.6.0
chardet==2.2.1
cli-helpers==1.2.1
Click==7.0
cloud-init==18.2
colorama==0.3.2
configobj==5.0.6
cryptography==1.7.2
docutils==0.12
ec2-hibinit-agent==1.0.0
enum34==1.0.4
futures==3.0.5
hibagent==1.1.0
humanize==0.5.1
idna==2.4
iniparse==0.4
ipaddress==1.0.16
Jinja2==2.7.2
jmespath==0.9.3
jsonpatch==1.2
jsonpointer==1.9
jsonschema==2.5.1
jwcrypto==0.4.2
kitchen==1.1.1
langtable==0.0.31
lockfile==0.9.1
MarkupSafe==0.11
oauthlib==2.0.1
pgcli==2.1.1
pgspecial==1.11.7
Pillow==2.0.0
ply==3.4
prompt-toolkit==2.0.10
psycopg2==2.8.3
pyasn1==0.1.9
pycparser==2.14
pycurl==7.19.0
Pygments==2.4.2
pygpgme==0.3
pyliblzma==0.5.3
pystache==0.5.3
python-daemon==1.6
python-dateutil==2.6.0
pyxattr==0.5.1
PyYAML==3.10
repoze.lru==0.4
requests==2.6.0
rsa==3.4.1
s3transfer==0.1.12
setproctitle==1.1.10
simplejson==3.2.0
six==1.9.0
sqlparse==0.3.0
tabulate==0.8.5
terminaltables==3.1.0
urlgrabber==3.10
urllib3==1.24.3
wcwidth==0.1.7
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4

**Comment by j-bennet** [comment]
@Ian-T-Price I have a possible fix in branch. Can you try installing pgcli from branch as follows:

`pip install git+https://github.com/dbcli/pgcli.git@j-bennet/pqconninfo-1110`

and see if that resolves the problem?

**Comment by j-bennet** [comment]
Fixed in 2.2.0.
