### ISSUE TITLE
How to change keybindings

### ISSUE THREAD

**Issue by lsund** [dbcli/pgcli#1125]
## Description

The [keybindings](https://www.pgcli.com/keybindings) page tells me I can change keybindings but it does not tell me how. I am missing a full list of possible keybindings to change as well as a description how to change these in the configuration file.

## Your environment

*Arch Linux kernel 5.3.13

*pgcli version 2.1.1

*Pip freeze:
```
appdirs==1.4.3
asn1crypto==1.2.0
attrs==19.3.0
bcrypt==3.1.7
CacheControl==0.12.5
cached-property==1.5.1
cffi==1.13.2
chardet==3.0.4
cli-helpers==1.2.1
Click==7.0
colorama==0.4.1
configobj==5.0.6
cryptography==2.8
distlib==0.3.0
distro==1.4.0
docker==4.1.0
docker-compose==1.25.0
docker-pycreds==0.4.0
dockerpty==0.4.1
docopt==0.6.2
feedparser==5.2.1
greenlet==0.4.15
html5lib==1.0.1
humanize==0.5.1
idna==2.8
importlib-metadata==0.23
jsonschema==3.2.0
lensfun==0.3.2
lockfile==0.12.2
louis==3.11.0
meson==0.52.0
more-itertools==7.2.0
msgpack==0.6.2
neovim==0.3.1
ordered-set==3.1.1
packaging==19.2
paramiko==2.6.0
pep517==0.6.0
pgcli==2.1.1
pgspecial==1.11.7
ply==3.11
progress==1.5
prompt-toolkit==2.0.10
psycopg2==2.8.4
pyalpm==0.9.0
pyasn1==0.4.8
pycairo==1.18.2
pycparser==2.19
Pygments==2.5.1
PyGObject==3.34.0
PyNaCl==1.3.0
pynvim==0.4.0
pyparsing==2.4.5
pyrsistent==0.15.6
python-dateutil==2.8.1
pytoml==0.1.21
PyYAML==5.1.2
regex==2019.8.19
requests==2.22.0
retrying==1.3.3
setproctitle==1.1.10
six==1.13.0
sqlparse==0.3.0
tabulate==0.8.5
terminaltables==3.1.0
texttable==1.6.2
urllib3==1.25.7
virtualenv==16.1.0
wcwidth==0.1.7
webencodings==0.5.1
websocket-client==0.56.0
youtube-dl==2019.11.22
zipp==0.6.0
```

**Comment by owst** [comment]
Hi @lsund - unfortunately there's currently no way to change the individual keybindings.

Instead, you can switch between either (default) emacs mode or vi mode, by pressing f4 when running pgcli, or by editing the config file and changing the `vi` setting to `True`.

**Comment by lsund** [comment]
Hi @owst, Okay, I was confused by
>  The keybindings can be changed via the config file (~/.config/pgcli/config) or toggled via F4 key.
But thanks for the clarification!
