### ISSUE TITLE
Error running a query after connection was lost and restored

### ISSUE THREAD

**Issue by gantsevdenis** [dbcli/pgcli#1146]
## Description
```
wakapi_depl1> \d category                                                                                                                                            
Reconnecting...
Reconnect Failed
could not translate host name "proxyprod" to address: Name or service not known

<.. turning on work VPN ... >

wakapi_depl1> \d category                                                                                                                                            
'NoneType' object has no attribute 'mogrify'
```

## Your environment
Version: 2.1.1
Linux: 4.15.0-62-generic

**Comment by dbaty** [comment]
This is a very old issue. If you're still around, could you please try to reproduce with the latest version of pgcli? Also, what output do you expect? Is "category" a table in your database?

**Comment by j-bennet** [comment]
So, I can't reproduce the issue exactly, but we do have some odd behavior when the connection is lost and then restored.

### Steps

1. Run pgcli and connect to any remote database
2. Turn off the wifi
3. Run the `\d` command and wait for it to time out

```
> pgcli -D quality
Server: PostgreSQL 12.16
Version: 4.0.0
Home: http://pgcli.com
master@dquality:quality> \d
consuming input failed: Operation timed out
SSL SYSCALL error: Operation timed out
Time: 18.321s (18 seconds), executed in: 18.321s (18 seconds)
```

4. Turn wifi back on
5. Run `\d` again

```
master@dquality:quality> \d
sending query failed: another command is already in progress
Time: 0.002s
master@dquality:quality>
```

That doesn't look right, even though the error is different. We should handle this error.
