### ISSUE TITLE
Add support for prompt_toolkit>3

### ISSUE THREAD

**Issue by blazewicz** [dbcli/pgcli#1148]
Currently `pgcli` is pinned to `prompt_toolkit` version 2:

https://github.com/dbcli/pgcli/blob/91263c37b94a1a3b45be13d35ff1ea19c7b8e1b7/setup.py#L12

This causes a compatibility issue with other tools using `prompt_toolkit`, for example with `litecli` which requires `prompt_toolkit>=3.0.3`.

https://github.com/dbcli/litecli/blob/39d7dad9d63f445e288f476f9e4b76cdd7dc8e9b/setup.py#L30

This issue blocks package managers like `macports` to keep up-to-date versions of both `pgcli`, `litecli` and some other tools.

**Comment by clbarnes** [comment]
I would consider installing pgcli using [`pipx`](https://github.com/pipxproject/pipx/), so that it doesn't have to share a virtual environment with anything, and is available everywhere for your user.

**Comment by laixintao** [comment]
> I would consider installing pgcli, along with any other system tools which happen to be written in python, using [`pipx`](https://github.com/pipxproject/pipx/), so that it doesn't have to share a virtual environment with anything, and is available everywhere for your user.

Thanks and yes, that's the recommended way, but the problem is for some distribution developers, their packaging work requires prompt-toolkit>=3 :)
