### ISSUE TITLE
PG10+ "identity" columns not differentiated in \d output

### ISSUE THREAD

**Issue by osvenskan** [dbcli/pgcli#1150]
## Description
Thanks for `pgcli`! 

Postgres 10 introduced the `IDENTITY` column as a replacement for `SERIAL` in int PKs. `pgcli`'s `\d` command reports when a column is `SERIAL` but not when it's `IDENTITY`, so when using `IDENTITY` columns it's not obvious that they're autoincrement PKs. **I'd like to see "generated by default as identity" appear in the `Modifiers` column.** Here's an example that shows that the `IDENTITY` column isn't specially marked in `Modifiers` --

    $ pgcli
    Password for postgres:
    Server: PostgreSQL 11.6
    Version: 2.2.0
    Chat: https://gitter.im/dbcli/pgcli
    Home: http://pgcli.com
    $ CREATE TABLE foo (
         id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         some_stuff text
         )

    CREATE TABLE
    Time: 0.044s
    $ \d foo
    +------------+---------+-------------+
    | Column     | Type    | Modifiers   |
    |------------+---------+-------------|
    | id         | integer |  not null   |
    | some_stuff | text    |             |
    +------------+---------+-------------+
    Indexes:
        "foo_pkey" PRIMARY KEY, btree (id)

    Time: 0.198s

Here's `psql` output for the same table, note output in the `Default` column --

                                       Table "public.foo"
       Column   |  Type   | Collation | Nullable |             Default
    ------------+---------+-----------+----------+----------------------------------
     id         | integer |           | not null | generated by default as identity
     some_stuff | text    |           |          |
    Indexes:
        "foo_pkey" PRIMARY KEY, btree (id)

Here's `pgcli` for a table created with the old school `SERIAL` default. The fact that it's an autoincrement PK is visible in the `Modifiers` column  --

    $     CREATE TABLE bar (
             id SERIAL PRIMARY KEY,
                  some_stuff text
         )

    CREATE TABLE
    Time: 0.049s
    $ \d bar
    +------------+---------+---------------------------------------------------+
    | Column     | Type    | Modifiers                                         |
    |------------+---------+---------------------------------------------------|
    | id         | integer |  not null default nextval('bar_id_seq'::regclass) |
    | some_stuff | text    |                                                   |
    +------------+---------+---------------------------------------------------+
    Indexes:
        "bar_pkey" PRIMARY KEY, btree (id)

## Your environment

I'm on a Mac, Catalina, Python 3.6, `pgcli` 2.2.0.

    $ pip freeze
    cli-helpers==1.2.1
    Click==7.0
    configobj==5.0.6
    humanize==0.5.1
    pgcli==2.2.0
    pgspecial==1.11.9
    prompt-toolkit==2.0.10
    psycopg2==2.8.4
    Pygments==2.5.2
    setproctitle==1.1.10
    six==1.14.0
    sqlparse==0.3.0
    tabulate==0.8.6
    terminaltables==3.1.0
    wcwidth==0.1.8

**Comment by gantsevdenis** [comment]
Unless someone has already took this, I am working on a PR
