### ISSUE TITLE
Feature request: use environment variables to set command line arguments

### ISSUE THREAD

**Issue by clbarnes** [dbcli/pgcli#1160]
Database connections are often project-specific, or machine-specific for containers, so it would be nice to be to set our own defaults, possibly with something like a `.env` file.

Using any part of the full connection string `postgresql://[user[:password]@][netloc][:port][/dbname][?extra=value[&other=other-value]]` would ignore all environment variables.

`PGCLI_USER`, `PGCLI_HOST`, `PGCLI_PORT`, and `PGCLI_DATABASE` would be the obvious names. In conjunction with #1159 , I see the search path for options being 

connection string -> command line options -> environment variables -> profile -> ancestor profile(s) -> current default

**Comment by laixintao** [comment]
Sounds good, what do you think? @j-bennet

**Comment by clbarnes** [comment]
My bad, this is already implemented (using the same environment variables as used by `psql`), just not documented anywhere.
