### ISSUE TITLE
setting "pager = less -SRXF" results in error

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#1167]
## Description
Setting "pager = less -SRXF" results in error (on Windows). From a process monitor trace I can see that pgcli runs `C:\WINDOWS\system32\cmd.exe /c 'less -SRXF' 'R:\Temp\tmpv1iacsw3'`. The error is an operating system error saying `Command "'less" could not be found` (note the `'less`).

It looks to me like pgcli is trying to run the pager string without normalizing it first into its components (for instance with `shlex.split`).

## Your environment

- [x] Windows 10
- [x] pgcli 2.2.0

**Comment by laixintao** [comment]
I don't use Windows so sorry I can't test.

But pgcli's pager is done by [`click.echo_via_pager`](https://click.palletsprojects.com/en/7.x/api/#click.echo_via_pager). So it might be click's issue.

However, I think a workaround solution might be setting your `$PAGER=less` and then set `$LESS=SRXF`, an environment which less will read.

From `man less`:

```
ENVIRONMENT VARIABLES
       LESS   Options which are passed to less automatically.
```

**Comment by thorstenkampe** [comment]
@laixintao Yup, you are right: there's already a [ticket](https://github.com/pallets/click/issues/1514) for the issue. I'm going to close this one here.

Thanks.
