### ISSUE TITLE
“there is no parameter $1” with named query

### ISSUE THREAD

**Issue by Smylers** [dbcli/pgcli#1176]
## Description
Named queries have stopped recognizing arguments passed to numeric positional parameters since upgrading to version 2.2.0:

```
postgres> \ns i SELECT $1                                                       
Saved.
Time: 0.003s
postgres> \n i 42                                                               
there is no parameter $1
LINE 1: SELECT $1
               ^
```

I got version 2.2.0 by upgrading Ubuntu to 20.04 LTS. I have named queries saved in my config which used to work, but I don't know which version of pgcli I had previously.

Using `%s` instead of `$1` (as suggested in #841) does work:

```
postgres> \ns i SELECT %s                                                       
Saved.
Time: 0.006s
postgres> \n i 42                                                               
> SELECT %s
+----------+
| ?column? |
+----------+
| 42       |
+----------+
SELECT 1
```

But that [isn't documented](https://www.pgcli.com/named_queries.md), and isn't as flexible.

## Your environment

- [X] Please provide your OS and version information. **Ubuntu 20.04 LTS (Focal Fossa)**
- [X] Please provide your CLI version. **2.2.0**
- [X] What is the output of ``pip freeze`` command. **Command 'pip' not found, but there are 18 similar ones.**

**Comment by j-bennet** [comment]
@Smylers instead of `pip freeze` command, try this:

```
python --version
```

and this:

```
python -m pip freeze
```
and post the output.

Thank you!

**Comment by j-bennet** [comment]
I'm not sure, but I think that the version of `pgspecial` module packaged with your Ubuntu distribution may be old. See if updating `pgspecial` fixes your problem:

`python -m pip install -U pgspecial`

**Comment by Smylers** [comment]
> I'm not sure, but I think that the version of `pgspecial` module packaged with your Ubuntu distribution may be old.
Bingo! Thanks.

Ubuntu 20.04 was released last week, but the `python3-pgspecial` package is version 1.9.0-2.

What is the minimum version of `pgspecial` that `pgcli` relies on? I'll report it as a bug in Ubuntu that it needs to have that as a dependency.

> `python -m pip install -U pgspecial`

Yay! And I found the `pip` command: it's `pip3`, to go with `python3`. Apparently I still have some legacy software installed which requires that `python` be Python 2.

**Comment by j-bennet** [comment]
@Smylers the latest `pgspecial` is 1.11.10, and it would be good to have the latest.

Was your problem fixed by updating `pgspecial`?

**Comment by Smylers** [comment]
> @Smylers the latest `pgspecial` is 1.11.10, and it would be good to have the latest.
Ta.
> Was your problem fixed by updating `pgspecial`?
Yes. Apologies if that wasn't clear in my previous response.

Thank you for being so speedy in addressing this.
