### ISSUE TITLE
Exception in thread completion_refresh

### ISSUE THREAD

**Issue by julianodba** [dbcli/pgcli#1184]
How can I fix this message, please?

```
pgcli -h localhost -U juliano -d postgres
postgres> Exception in thread completion_refresh:
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in runs-mode Refreshing completions...
self._target(self._args, *self._kwargs)
File "/usr/share/pgcli/pgcli/completion_refresher.py", line 65, in _bg_refresh
refresher(completer, executor)
File "/usr/share/pgcli/pgcli/completion_refresher.py", line 110, in refresh_tables
completer.extend_foreignkeys(executor.foreignkeys())
File "/usr/share/pgcli/pgcli/pgcompleter.py", line 278, in extend_foreignkeys
childcolmeta = meta[childschema][childtable][childcol]
KeyError: 'my_partitioned_table'
```

```
pgcli -v
Version: 2.2.0
```
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
```
```
SELECT VERSION();
PostgreSQL 11.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit
```
```
python3 --version
Python 3.8.2
```

**Comment by catherinedevlin** [comment]
I haven't worked on the completer, but that looks as though the data dictionary somehow changed while your pgcli instance was still starting up.  (Or maybe some kind of race condition bug?)

Is it a persistent problem?  Does it happen every time, or just sometimes?  Does it persist after you restart pgcli, restart postgresql, or restart the server?

**Comment by omcnoe** [comment]
Hi, I have also recently experienced this issue.
It occurred when I committed a transaction that renamed a number of tables, which had foreign keys to each other.

pgcli 3.0.0
postgres 9.6

**Comment by julianodba** [comment]
I have replaced my old laptop for a new one and the issues don't happen anymore. I am afraid that I can't provide more info as the old laptop is gone, sorry. Maybe this ticket can be closed.
