### ISSUE TITLE
Feature Request: allow ANSI sequences in the null_string setting

### ISSUE THREAD

**Issue by henderea** [dbcli/pgcli#1185]
## Description
It would be really nice if I could configure the `null_string` to be in a different style to stand out more, but doing `\x1b[1m` to get bold text like the prompt config just puts the escape sequence directly into the column as plain text instead of properly handling it as an ANSI escape sequence.  I would really like to have the `<null>` be dim or gray, because it's really hard to notice when it's the same color.

Alternatively, maybe add something to the `[colors]` section to define the style of the null string, such as an `output.null-string` property.

## Your environment
OS: macOS 10.14.6
pgcli version: 3.0.0
`pip freeze`: not relevant; this is a feature request

**Comment by laixintao** [comment]
This feature is really nice to have, what do you think? @j-bennet

**Comment by j-bennet** [comment]
@laixintao Yes! Do you feel like taking it up? :)

**Comment by laixintao** [comment]
I will give it a try :)
