### ISSUE TITLE
Custom CA certifcate in pgcli

### ISSUE THREAD

**Issue by kannangce** [dbcli/pgcli#1202]
## Description

Unable to find a config to supply custom CA certificate in `pgcli`. The cli parameter and the config file in `AppData/Local/dbcli/pgcli/config` neither of them seem to have a config to supply a custom ca file. Please help me figure out the config.

## Your environment

- [ ] Please provide your OS and version information.
Windows 10

- [ ] Please provide your CLI version.
pgcli 3.0.0

- [ ] What is the output of ``pip freeze`` command.
```
$ pip freeze
cli-helpers==2.1.0
click==7.1.2
configobj==5.0.6
humanize==2.5.0
pgcli==3.0.0
pgspecial==1.11.10
prompt-toolkit==3.0.5
psycopg2==2.8.5
Pygments==2.6.1
six==1.15.0
sqlparse==0.3.1
tabulate==0.8.7
terminaltables==3.1.0
wcwidth==0.2.5

```

**Comment by wchao** [comment]
Set the environment variable PGSSLROOTCERT, like so:
PGSSLROOTCERT=/etc/ssl/certs/ca-bundle.trust.crt

You should be able to set use all of the PG environment variables. For instance, I use the following successfully:
PGHOST
PGDATABASE
PGSSLMODE
PGSSLROOTCERT
PGSSLCERT
PGSSLKEY

**Comment by laixintao** [comment]
Is this enough for you? Can it be closed?

**Comment by kannangce** [comment]
Yes, please! I didn't get a chance to check it. But will do it later. It is worth to be updated in readme. Custom CA is a typical use case for many projects.

**Comment by laixintao** [comment]
> Yes, please! I didn't get a chance to check it. But will do it later. It is worth to be updated in readme. Custom CA is a typical use case for many projects.

Good idea! updated.
