### ISSUE TITLE
Password protecting destructive queries?

### ISSUE THREAD

**Issue by dbousamra** [dbcli/pgcli#1209]
## Description
I would like to extend the functionality in confirm_destructive_query to allow for asking of a password. I feel like the Y/N is great, but I am super paranoid, and occasionally I will autopilot through the Y/N prompt.

**Comment by j-bennet** [comment]
Interesting. Would you like to take a stab at a PR for that?

**Comment by dbousamra** [comment]
Sure.

Another feature I would be interested in is the ability to specify a background color per alias_dsn. I don't know I would add config for something like this, but I think it could be a useful feature.

**Comment by quezak** [comment]
@dbousamra about the background color -- since v3.0 you can change the color of the prompt with `--prompt`, so it's _somewhat_ possible to have different colors per db with a script.
