### ISSUE TITLE
Different versions between the PostgreSQL version and the one provided by PGCLI

### ISSUE THREAD

**Issue by FaresKi** [dbcli/pgcli#1217]
## Description
I got a PostgreSQL 13.0 server installed with PostGIS and I'm trying to use it with pgcli. However pgcli provides its own version of PostgreSQL 12.4 (on which the PostGIS extension is not installed). 

Therefore I was wondering if there's a way to configure the pgcli PostgreSQL version.
`fareskissoum@Faress-MacBook-Pro ~ % which postgres`
`/usr/local/opt/postgresql/bin/postgres`

## Your environment

- [MacOS 10.15.7 - PostgreSQL 13.0] 
- [3.0.0]
- [No output]

**Comment by FaresKi** [comment]
Nevermind, the database upgrade didn't happen despite software upgrade.

**Comment by j-bennet** [comment]
`pgcli` does not include PostgreSQL.
