### ISSUE TITLE
Separate DSN Configuration from main pgcli config

### ISSUE THREAD

**Issue by kiran94** [dbcli/pgcli#1228]
*Thank you for building such an awesome tool! I'm unsure if there is already an existing solution for this, please point out if so.*

## Description
I would like to be share my pgcli config between machines however I use the `alias_dsn` which contains sensitive information such as passwords. This information shouldn't be shared, I just want configurations such as `prompt`, `table_format` etc to be shared.

## Your environment

- [X] Please provide your OS and version information. - `Linux, Windows`
- [X] Please provide your CLI version. - `Version: 3.0.0`
- [X] What is the output of ``pip freeze`` command. - `N/A (not important for this issue)`

## Potential Solution
Break out DSN configuration into a separate file inside `~/.config/pgcli/` similar to `casing_file = default` referring to `~/.config/pgcli/casing`

**Comment by j-bennet** [comment]
Hi @kiran94! Sorry, we don't have the exact feature that you're looking for. Perhaps storing your user credentials in `~/.pgpass` might be helpful:

https://www.postgresql.org/docs/9.3/libpq-pgpass.html

**Comment by kiran94** [comment]
Thank you! This will work for me. For anyone that stumbles on this issue in the future, you can just set a DSN in pgcli config like so: `example = postgresql://postgres@localhost:5432/database` (without password) and then create a corresponding entry that matches that server,user,database inside `.pgpass`. See the link above for more info. 

@j-bennet Feel free to close this ticket if we aren't planning on adding this kind of feature directly into pgcli in the future.
