### ISSUE TITLE
Metacommand \dp not implemented

### ISSUE THREAD

**Issue by gdevanla** [dbcli/pgcli#1234]
## Description

Looks like the metacommand \dp is NotImplemented.

I am willing to submit a PR to help with this. Can I have some pointers on where to start.

## Your environment

- [ ] Please provide your OS and version information.
Linux
- [ ] Please provide your CLI version.

Server: PostgreSQL 12.3
Version: 2.2.0

- [ ] What is the output of ``pip freeze`` command.

**Comment by lelit** [comment]
The _metacommands_ are implemented in [pgspecial](https://github.com/dbcli/pgspecial). One nice trick is using `psql --echo-hidden` to get the SQL used by psql to obtain the required info.

**Comment by gdevanla** [comment]
Thanks. I realize this has to be implemented in https://pypi.org/project/pgspecial/

**Comment by gdevanla** [comment]
I went ahead and implemented this here #https://github.com/dbcli/pgspecial/pull/96
