### ISSUE TITLE
Print named queries

### ISSUE THREAD

**Issue by gdevanla** [dbcli/pgcli#1236]
## Description

It would be nice to print a named query with some option like `\np`.  Currently, the only way to view a named query is to list all of them using `\n`

Is this something we can add. I am happy to add submit a PR with this change.

## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment]
@gdevanla Sure, feel free to submit a PR! Named queries are implemented in pgspecial:

https://github.com/dbcli/pgspecial/blob/62be9a04173843f699c9e64c6b264a818d402138/pgspecial/iocommands.py#L183

**Comment by gdevanla** [comment]
I have addressed this in this PR https://github.com/dbcli/pgspecial/pull/97

**Comment by chagui** [comment]
@gdevanla thanks for the contribution!
