### ISSUE TITLE
Using visidata as pager doesn't work

### ISSUE THREAD

**Issue by dufferzafar** [dbcli/pgcli#1238]
## Description

I've been trying to use [`visidata`](visidata.org/) as a pager. Inspiration:

[![asciicast](https://asciinema.org/a/380154.svg)](https://asciinema.org/a/380154)

I have this in my config:

```ini
[main]
pager = vd -f csv
enable_pager = True
table_format = csv
```

But when I run a query in `pgcli` it outputs as CSV.

By the way, I've also tried the same setup on `mycli` and there the above config works!

## Your environment

- [ ] Please provide your OS and version information.
```
>lsb_release -a
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

>uname -a
Linux 4.15.0-126-generic #129~16.04.1-Ubuntu SMP Tue Nov 24 11:22:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

- [ ] Please provide your CLI version.

```
> pgcli --version
Version: 3.0.0
```

- [ ] What is the output of ``pip freeze`` command.

- Full config

```ini
[main]
smart_completion = True
wider_completion_menu = False
multi_line = False
multi_line_mode = psql
destructive_warning = True
expand = False
auto_expand = False
generate_aliases = False
log_file = default
keyword_casing = auto
casing_file = default
generate_casing_file = False
case_column_headers = True
history_file = default
log_level = INFO
asterisk_column_order = table_order
qualify_columns = if_more_than_one_table
search_path_filter = False
pager = vd -f csv
timing = True
table_format = csv
syntax_style = default
vi = False
on_error = STOP
row_limit = 1000
less_chatty = False
prompt = '\u@\h:\d> '
min_num_menu_lines = 4
multiline_continuation_char = ''
null_string = '<null>'
enable_pager = True
keyring = True
```

**Comment by pasenor** [comment]
It's the same issue as #1102 that was solved by hard-coding the pager name "pspg" and making an exceptional logic for it. I'll look into proper handling of csv pagers, in the meantime the hacky way to get it to work is to alias vd to pspg and set `pager = pspg -f csv`
