### ISSUE TITLE
warnings for update queries

### ISSUE THREAD

**Issue by samuelcolvin** [dbcli/pgcli#1239]
**Thank you for pgcli, it's wonderful, I use it every day. 🙏 🙇**

## Description

Two minutes ago I nearly mangled a production database using pgcli. I started writing an update query (meant to modify one user), autocomplete offered me an old query that would have undated many users, I automatically hit enter, realised what happened and managed to hit ctrl+C in time. Only latency saved me.

My heart rate is still recovering.

Please could we either add an another option like `destructive_warning` for `update` queries, or provide a way to extend `destructive_warning` to cover update queries?

I think this is reasonable, `update` queries can definitely be destructive: `update users set password_hash=null, email=null`!

There's also a question over `insert` queries, but I think that's not such a problem.

## Your environment

- Please provide your OS and version information. OSX 11.3, connecting to a pg database on heroku
- Please provide your CLI version. pgcli v3
- What is the output of ``pip freeze`` command, (not required I think and somewhat private)

**Comment by j-bennet** [comment]
This sounds like a good idea. An update without `where` clause can be especially dangerous.

**Comment by j-bennet** [comment]
Fixed in https://github.com/dbcli/pgcli/pull/1242.
