### ISSUE TITLE
Allow disabling of truncation for large json fields.

### ISSUE THREAD

**Issue by jappeace** [dbcli/pgcli#1250]
## Description

9 out of 10 times I want to read what's truncated, I don't care if it takes a lot of lines.

![image](https://user-images.githubusercontent.com/3874017/109338985-5cc9cf80-783d-11eb-90c0-a1c560628872.png)

I'd like to see it without dots

**Comment by j-bennet** [comment]
`\x on` might help.

**Comment by jappeace** [comment]
Oh nice, thanks!
