### ISSUE TITLE
Ability to "freeze" the header section

### ISSUE THREAD

**Issue by farzadmf** [dbcli/pgcli#1268]
## Description
Hi, I cannot this is a problem, per se, but I think it could be very helpful when we have a lot of rows in our data and a lot of fields (columns).

Right now, if we scroll down to see the remaining rows, we lose the header, so it's hard to know what is what in the rows that we're looking at.

I think it would be great if there's a config value that we can set to somehow "freeze" the header so that when we scroll, only the rows are scrolled (similar to Excel)

## Your environment
I'm on Linux, using Alacritty as my terminal

- [x] Please provide your OS and version information. Manjaro LInux with kernel: `5.11.19-1-MANJARO`
- [x] Please provide your CLI version: `3.1.0`

**Comment by okbob** [comment]
pspg is specialized pager that allows freezing header and more

https://github.com/okbob/pspg

**Comment by farzadmf** [comment]
Thank you @okbob for the reply. I will check it out (and close this once I see that it does the trick :slightly_smiling_face: )

**Comment by farzadmf** [comment]
OMG @okbob , thank you for your amazing suggestion. It's a superb utility and a real game changer (I think even beyond `pgcli`)

Closing this as you not only resolved my issue, you introduced a great tool to me and I thank you for that
