### ISSUE TITLE
Backslash in pgcli using a Windows computer

### ISSUE THREAD

**Issue by DataMower** [dbcli/pgcli#1274]
## Description
I didn't find out how to type a backslash in pgcli using my system (Windows 10, HP ZBook). Normally, I type: ctrl + alt + <. It  does not work on my Windows machine.

## Your environment
Windows 10, HP ZBook (Intel(R) Core(TM) i7-4910MQ CPU @ 2.90GHz , 32GB RAM).

- Windows 10 Enterprise, Version: 20H2
- pgcli Version 3.1.0

**Comment by j-bennet** [comment]
Thank you for filing the issue @DataMower!

1. You said in our previous conversation that you installed pgcli with conda. How are you running conda? Are you using Windows Subsystem for Linux (WSL)?

2. Which terminal are you running? (Windows Terminal, Power Shell, Git Bash, etc)?
