### ISSUE TITLE
SQL command typo causes python TypeError; possible command injection?

### ISSUE THREAD

**Issue by jwarner112** [dbcli/pgcli#1277]
## Description

I'm attempting to pull data into a temporary table and dump that to a CSV. Take, for example, this trivial example that causes the issue:

```sql
my_table> SELECT * INTO TEMPORARY TABLE temptbl FROM users WHERE users.email IS NOT NULL;
SELECT 68129
Time: 0.323s
my_table> \copy (SELECT * FROM temptbl) INTO 'users.csv' WITH csv;
list indices must be integers or slices, not NoneType
my_table>
```

Take note of the typo -- I've accidentally called `INTO` instead of `TO` as `\copy` uses. This leads to the decidedly Python error message that follows it. Naively, I'm guessing that adding `IN` may correspond to Python's `in` or something.

### OS

I'm on MacOS Big Sur -- specifically:
```Darwin navbookpro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64```

### Client Into

I installed `pgcli` from Homebrew recently:

```
$ brew info pgcli
pgcli: stable 3.1.0 (bottled)
CLI for Postgres with auto-completion and syntax highlighting
https://pgcli.com/
/usr/local/Cellar/pgcli/3.1.0 (2,223 files, 17.8MB) *
  Poured from bottle on 2021-07-05 at 14:53:36
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pgcli.rb
License: BSD-3-Clause
==> Dependencies
Required: libpq ✔, openssl@1.1 ✔, python@3.9 ✔
==> Analytics
install: 1,456 (30 days), 5,123 (90 days), 32,926 (365 days)
install-on-request: 1,458 (30 days), 5,124 (90 days), 32,792 (365 days)
build-error: 0 (30 days)
```

### Python environment

Digging into the homebrew's bottled Python environment, I find:

```
$ /usr/local/Cellar/pgcli/3.1.0/libexec/bin/pip freeze
cli-helpers==2.1.0
click==7.1.2
configobj==5.0.6
pendulum @ file:///private/tmp/pgcli--pendulum-20201214-76032-tt3vjl/pendulum-2.1.2
pgcli==3.1.0
pgspecial==1.11.10
prompt-toolkit @ file:///private/tmp/pgcli--prompt-toolkit-20201214-76032-z126t0/prompt_toolkit-3.0.8
psycopg2==2.8.6
Pygments==2.7.3
python-dateutil @ file:///private/tmp/pgcli--python-dateutil-20201214-76032-14v8nue/python-dateutil-2.8.1
pytzdata @ file:///private/tmp/pgcli--pytzdata-20201214-76032-1t2o5yn/pytzdata-2020.1
setproctitle @ file:///private/tmp/pgcli--setproctitle-20201214-76032-1pnn98n/setproctitle-1.2.1
six==1.15.0
sqlparse==0.4.1
tabulate==0.8.7
terminaltables==3.1.0
wcwidth==0.2.5
```

**Comment by jwarner112** [comment]
Unrelated to the tool: I'm relatively new at SQL stuff and came from trying `psql`, Postico, and Datagrip. `pgcli` gives me the balance I want of "psql, but good" and skips the need for a whole graphical kitchen-sink environment. I love this tool and am happy to take the time to contribute this issue with as much quality as I can!

**Comment by amjith** [comment]
Let me try to reproduce it.

**Comment by amjith** [comment]
Thank you for your reproducible case. I love it when the reporter includes a clean example to reproduce the issue. I found the bug and I'm working on a fix. We are only [looking](https://github.com/dbcli/pgspecial/blob/master/pgspecial/iocommands.py#L130-L145) for the words "TO" and "FROM" in that statement. If we can't find it then we return an index of None and that is not checked in the downstream. Hence the bug. 

You expressed some interest in contributing to the project. I'd welcome that very much. Here's a tip to get started, when you encounter an error like this, the first place I tend to look at is the log file which is located at ~/.config/pgcli/log. There is usually a traceback that helps me point to where the bug might be. 

The special commands such as `\copy` or `\d` etc are implemented in the library [pgspecial](https://github.com/dbcli/pgspecial/).

I hope that helps.

**Comment by amjith** [comment]
The bug was in pgspecial and I've opened a PR with the fix. You can install the PR version of pgspecial if you're familiar with how to install python packages with pip using the following command: 

```
pip install -U https://github.com/dbcli/pgspecial/archive/refs/heads/copy_exception.zip
```

**Comment by j-bennet** [comment]
It's now merged to master, so:

`pip install -U https://github.com/dbcli/pgspecial/archive/refs/heads/master.zip`
