### ISSUE TITLE
Post 3.1.0 release

### ISSUE THREAD

**Issue by gotgenes** [dbcli/pgcli#1281]
## Description

Since [its last release (3.1.0)](https://github.com/dbcli/pgcli/releases/tag/v3.1.0) in December 2020, helpful bug fixes and improvements have landed on `master` but haven't yet made their way to package repositories (PyPI, Homebrew, etc.) Prior releases seem to have come at a cadence of about one every six months. Please consider cutting a new release of pgcli.

Thanks for all your hard work! I love this tool!

**Comment by amjith** [comment]
Done!
