### ISSUE TITLE
passing sql via command line a la '-c' for psql?

### ISSUE THREAD

**Issue by jonassteinberg1** [dbcli/pgcli#1287]
## Description
I don't see a 'sql via the command ilne switch' option which is surprising.  Just want to make sure I'm not missing anything.  I've tried just appending sql to the end of a database connection and also using '-c', neither of which work.

## Your environment
MacOS

- [x] Please provide your OS and version information.
10.15.7
- [x] Please provide your CLI version.
3.1.0
- [ ] What is the output of ``pip freeze`` command.

**Comment by ubergarm** [comment]
You can kind do it in a hacky way if you really want to:
```bash
# set your env vars then
PGPASSWORD=$SRC_DB_PASS pgcli --less-chatty -h $SRC_DB_HOST -u $SRC_DB_USER $SRC_DB_NAME <<STDIN
  SELECT * from information_schema.tables WHERE table_schema = '$SRC_DB_SCHEMA';
STDIN
```
