### ISSUE TITLE
Interested in JSON output format?

### ISSUE THREAD

**Issue by spatrik** [dbcli/pgcli#1295]
## Description
I have a case where a bug in my code only appears with certain data in the database. I have now isolated the data causing the bug, and now I need to get this data into my tests. It would be great if I could get the output from pgcli in JSON format and just copy and paste it into my tests. 

Would you be interested in a PR for this feature? 

From what I can see in the code, it's the `format_output` function in `main.py`. It seems a lot of that code is most relevant for setting up the `TabularOutputFormatter`,  which isn't relevant to the JSON output. In that case I'll split the function into several smaller. I'm thinking that `format_output` either calls `format_tabular_output` which contains the code from now or `format_json_output` which handles the json format. 

The actual output format would be a list of objects, where the objects keys are column names and values the value of that column.

**Comment by j-bennet** [comment]
This is probably not a common use case, but you can sort of achieve the type of output you want already, with `row_to_json`:

```
test> create table a1(i integer, t text)
CREATE TABLE
Time: 0.008s
test> insert into a1 values (1, 'a')
INSERT 0 1
Time: 0.003s
test> insert into a1 values (2, 'b')
INSERT 0 1
Time: 0.002s
test> select * from a1;
+---+---+
| i | t |
|---+---|
| 1 | a |
| 2 | b |
+---+---+
SELECT 2
Time: 0.018s
test> select row_to_json(t) from (select row(a1.*) from a1) as t
+---------------------------+
| row_to_json               |
|---------------------------|
| {"row":{"f1":1,"f2":"a"}} |
| {"row":{"f1":2,"f2":"b"}} |
+---------------------------+
SELECT 2
Time: 0.011s
```

**Comment by spatrik** [comment]
Thanks for the tip about `row_to_json`. It doesn't give the same copy-and-pasteability as having a pgcli output mode,  but I do understand if it's a feature that's out of scope.

**Comment by j-bennet** [comment]
@spatrik Are you interested enough in this feature to attempt a PR yourself? We're always open to contributions. You would have to look at both `pgcli` and [cli_helpers](https://github.com/dbcli/cli_helpers), because currently pgcli utilizes only `TabularOutputFormatter`, and in fact the `cli_helpers` library does not implement any formatters for non-tabular output. I imagine your `JsonOutputFormatter` would become a part of `cli_helpers`.
