### ISSUE TITLE
Search and execute query from history

### ISSUE THREAD

**Issue by thuan1412** [dbcli/pgcli#1298]
## Description

It's would be convenient if pgcli supports search query history and execute it. This feature is similar to <Ctrl-r> in bash shell.
![image](https://user-images.githubusercontent.com/36019052/142759700-ae5a5005-c94c-47b3-9008-6e3659cf35fa.png)

**Comment by thuan1412** [comment]
Seem like `python-prompt-toolkit` already supported this feature.

**Comment by laixintao** [comment]
Yes I think you can try <kbd>Ctrl</kbd> + <kbd>R</kbd>
