### ISSUE TITLE
question: is there any quick command to list connections on current db ?

### ISSUE THREAD

**Issue by bagafoot** [dbcli/pgcli#1299]
İs there any command like \lc+ or could we request for enhancement ?

**Comment by laixintao** [comment]
sorry what do you expect `\lc+` do?

for list all connections, you can use `SELECT * FROM pg_stat_activity;`

**Comment by bagafoot** [comment]
I know I can query, but here we talk about quick commands,
I expect: `SELECT * FROM pg_stat_activity whre datname='current_db';`

**Comment by laixintao** [comment]
understand, I am not sure.

what do you think? does it worth a special command? @j-bennet

**Comment by j-bennet** [comment]
There's no command like that in pgcli. If you find you're using it a lot, how about storing it as a named query?

Save it:

```
test> \ns active_conn SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active';
Saved.
Time: 0.005s
```

Use it:

```
test> \n active_conn
> SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active'
+-------+--------+-------------+--------------------------------------------------------------------------------+
| pid   | state  | usename     | query                                                                          |
|-------+--------+-------------+--------------------------------------------------------------------------------|
| 26832 | active | irinatruong | SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active' |
+-------+--------+-------------+--------------------------------------------------------------------------------+
SELECT 1
Time: 0.012s
```

**Comment by bagafoot** [comment]
> There's no command like that in pgcli. If you find you're using it a lot, how about storing it as a named query?
> 
> Save it:
> 
> ```
> test> \ns active_conn SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active';
> Saved.
> Time: 0.005s
> ```
> 
> Use it:
> 
> ```
> test> \n active_conn
> > SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active'
> +-------+--------+-------------+--------------------------------------------------------------------------------+
> | pid   | state  | usename     | query                                                                          |
> |-------+--------+-------------+--------------------------------------------------------------------------------|
> | 26832 | active | irinatruong | SELECT pid, state, usename, query FROM pg_stat_activity WHERE state = 'active' |
> +-------+--------+-------------+--------------------------------------------------------------------------------+
> SELECT 1
> Time: 0.012s
> ```

thanks a lot, that very useful too
