### ISSUE TITLE
Does pgcli actually require libpq-dev and libevent-dev?

### ISSUE THREAD

**Issue by ariofrio** [dbcli/pgcli#1300]
## Description

The [README.md](https://github.com/dbcli/pgcli#readme) indicates that python-dev, libpq-dev, and libevent-dev are required for pgcli towers properly. However, it looks like the Dockerfile doesn't include libpq-dev or libevent-dev, neither of which seem to be included in the base python image (certainly not libpq-dev?). In my own experience, installing only libpq (not the development package, nor libevent at all) seems to be enough to get pgcli to work.

Could you clarify the requirements for pgcli? Thanks!

## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment]
The main dependency of `pgcli` is `psycopg2`. So we tell people to install the prerequisites that psycopg2 requires:

https://www.psycopg.org/docs/install.html#build-prerequisites

psycopg2 is a source-only package. And according to the link above, it needs python-dev, libpq-dev and pg-config to be built. We should probably simply link to the psycopg2 page in our documentation, but that's one more redirect for people to follow.

Our dockerfile does not explicitly install those requirements, but it's based on python:8 image, I think that image already has everything.
