### ISSUE TITLE
Cannot authenticate when password has changed and old password is stored in KWallet

### ISSUE THREAD

**Issue by andygoossens** [dbcli/pgcli#1307]
## Description
pgcli doesn't handle password changes well. Some time ago, I connected to a certain host+database with a certain username+password combination. That password got stored in KWallet.

Recently, my password on the server changed (but the username stayed the same). But when I want to use pgcli, I get an authentication error:
```
$ pgcli -h hostname -U username -d database
ERROR:  Auth failed
```

I tried using the `-W` parameter to force a password prompt, but the prompt never appeared and I still got the same error.

Luckily I realised that my old password was stored in KWallet. I changed the password there and that fixed the authentication error.

It would be better that pgcli:
* forces the password prompt when `-W` is mentioned, even when using KWallet
* or that it asks for another password when authentication fails, and (when the new password works) updates the password in KWallet

## Your environment
Ubuntu 21.10

I tried:
* pgcli version 3.1.0
  Installed from Ubuntu's repositories. Package version: 3.1.0-3
* pgcli version 3.3.0  
  Installed in a new virtualenv. Run: `pip install pgcli==3.3.0 dbus-python SecretStorage keyring`

Result of `pip freeze` from that virtualenv:
```
cffi==1.15.0
cli-helpers==2.2.0
click==8.0.3
configobj==5.0.6
cryptography==36.0.1
dbus-python==1.2.18
importlib-metadata==4.10.0
jeepney==0.7.1
keyring==23.5.0
pendulum==2.1.2
pgcli==3.3.0
pgspecial==1.13.0
prompt-toolkit==3.0.24
psycopg2==2.9.3
pycparser==2.21
Pygments==2.11.1
python-dateutil==2.8.2
pytzdata==2020.1
SecretStorage==3.3.1
setproctitle==1.2.2
six==1.16.0
sqlparse==0.4.2
tabulate==0.8.9
wcwidth==0.2.5
zipp==3.7.0
```

- [X] Please provide your OS and version information.
- [X] Please provide your CLI version.
- [X] What is the output of ``pip freeze`` command.

**Comment by amjith** [comment]
Ack. I have a PR pending. Can you try this out locally? You can install this version using:

```
pip install -U https://github.com/dbcli/pgcli/archive/refs/heads/always_ask_password-w.zip
```

**Comment by andygoossens** [comment]
I tried out pgcli from master and I can confirm that providing `-W` now works.
