### ISSUE TITLE
Missing SSH Tunnel option shown in docs

### ISSUE THREAD

**Issue by manojkarthick** [dbcli/pgcli#1309]
Thanks for building this awesome tool! I was looking at the [project docs](https://www.pgcli.com/ssh_tunnel) and saw there's SSH Tunnelling capabilities but I don't see it in the help command/it doesn't seem to be available. Is there any config I need to add?

**Comment by manojkarthick** [comment]
Looks like SSH Support documentation was merged in before [the PR](https://github.com/dbcli/pgcli/pull/1301) for supporting SSH Tunnels was merged. I will close the issue.

**Comment by j-bennet** [comment]
Sorry about that @manojkarthick. The PR itself is coming soon.

**Comment by manojkarthick** [comment]
Thank you!

**Comment by j-bennet** [comment]
pgcli 3.4.0 is released with SSH tunnel support.

**Comment by manojkarthick** [comment]
Thank you! Excited to try this out :)
