### ISSUE TITLE
'str' has no attribute 'parent'

### ISSUE THREAD

**Issue by Jakubzik** [dbcli/pgcli#1312]
## Description
After an update a formerly well working installation stopped working. Each command (\d t_person, select ...) fails with the message "'str' has no attribute 'parent'".

I'm not a python literate and need help fixing this ...

## My environment
- Archlinux on 5.15.16-1-lts with i3;
- pgcli --version is 3.3.1
- pip freeze:
nytree==2.8.0
  appdirs==1.4.4
  apsw==3.36.0.post1
  argcomplete==1.12.3
  backports.csv==1.0.7
  beautifulsoup4==4.10.0
  brotlicffi==1.0.9.2
  btrfsutil==5.16
  CacheControl==0.12.6
  cchardet==2.1.7
  cffi==1.15.0
  chardet==4.0.0
  cli-helpers==2.2.1
  click==8.0.3
  colorama==0.4.4
  configobj==5.1.0.dev0
  contextlib2==0.6.0.post1
  cryptography==36.0.1
  css-parser==1.0.6
  cssselect==1.1.0
  cupshelpers==1.0
  distlib==0.3.4
  distro==1.6.0
  dnspython==2.1.0
  entrypoints==0.3
  feedparser==6.0.2
  filelock==3.4.0
  future==0.18.2
  gpg==1.16.0
  html2text==2020.1.16
  html5-parser==0.4.10
  html5lib==1.1
  humanize==3.1.0
  idna==3.3
  ifaddr==0.1.7
  imaplib2==3.6
  importlib-metadata==4.8.1
  jeepney==0.7.1
  Jinja2==3.0.3
  keyring==23.4.0
  lensfun==0.3.95
  lockfile==0.12.2
  louis==3.20.0
  lxml==4.7.1
  Markdown==3.3.6
  MarkupSafe==2.0.1
  mechanize==0.4.6
  meson==0.61.1
  more-itertools==8.10.0
  msgpack==1.0.3
  multivolumefile==0.2.3
  netifaces==0.11.0
  netsnmp-python==1.0a1
offlineimap==8.0.0
  openshot-qt==2.6.1
  ordered-set==4.0.2
  packaging==20.9
  pendulum==2.1.2
  pep517==0.12.0
  pgcli==3.3.1
  pgspecial==1.13.0
  Pillow==9.0.0
  pipx==0.16.4
  ply==3.11
  progress==1.6
  prompt-toolkit==3.0.24
  psutil==5.9.0
  psycopg2==2.9.3
  py7zr==0.16.2
  pycairo==1.20.1
  pychm==0.8.6
  pycparser==2.21
  pycryptodome==3.12.0
  pycryptodomex==3.10.1
  pycups==2.0.1
  pycurl==7.44.1
  Pygments==2.11.2
  PyGObject==3.42.0
  pyOpenSSL==21.0.0
  pyparsing==2.4.7
  pyppmd==0.17.1
  PyQt5==5.15.6
  PyQt5-sip==12.9.0
  PyQtWebEngine==5.15.5
  PySocks==1.7.1
  python-dateutil==2.8.2
  pytzdata==2020.1
  PyYAML==5.4.1
  pyzmq==22.3.0
  pyzstd==0.15.0
  qutebrowser==2.4.0
  ranger-fm==1.9.3
  regex==2021.11.10
  reportlab==3.6.5
  requests==2.26.0
  requests-file==1.5.1
  resolvelib==0.5.5
  retrying==1.3.3
  rfc6555==0.1.0
  SecretStorage==3.3.1
  selectors2==2.0.2
  setproctitle==1.2.2
  sgmllib3k==1.0.0
  simplejson==3.17.6
  six==1.16.0
  soupsieve==2.2.1
  sqlparse==0.4.2
  tabulate==0.8.9
  TBB==0.2
  terminaltables==3.1.0
  texttable==1.6.4
  tldextract==3.1.2
  toml==0.10.2
  tomli==2.0.0
  torbrowser-launcher==0.3.5
  unrardll==0.1.4
  urllib3==1.26.8
  userpath==1.7.0
  validate==5.1.0.dev0
  visidata==2.8
  wcwidth==0.2.5
  webencodings==0.5.1
  youtube-dl==2021.12.17
  zeroconf==0.38.1
  zipp==3.7.0

**Comment by lelit** [comment]
This is an issue with Pygments 2.11.2, either downgrade that to 2.11.1 or install pgcli master

**Comment by amjith** [comment]
This issue was fixed in the latest version of pgcli 3.3.1. But it is puzzling that you have the right version but it seems like you're still encountering the issue. 

You can downgrade pygments using this command: `pip install pygments==2.11.1` and see if that works.

**Comment by Jakubzik** [comment]
Thank you, `pip install pygments==2.11.1` solved the issue for me.

**Comment by forward32** [comment]
Same problem on version 3.3.1, downgrading to pygments 2.11.1 helped.
