### ISSUE TITLE
stderr swallowed when using visidata as pager

### ISSUE THREAD

**Issue by kbd** [dbcli/pgcli#1326]
## Description

When using visidata as pager, stderr is swallowed.

There are a few tickets about similar issues (#1200, #1275) but after reading those tickets I don't know that there is a solution that works.

Interestingly, `litecli` works properly! Here are my configs and some examples:

### pgcli config:

```ini
[main]
pager = kw /usr/local/bin/vd -f csv
table_format = csv
less_chatty = True
prompt = '> '
```

### litecli config:

```ini
[main]
multi_line = False
pager = kw /usr/local/bin/vd
table_format = tsv
less_chatty = True
```

`kw` is "kitty window" that opens the output in a split, as you can see in the screenshots:

Visidata works as pager:

![Screen Shot 2022-03-21 at 4 17 18 PM](https://user-images.githubusercontent.com/728060/159375406-4a86e73a-81c7-4317-bb79-0abcade6ce6d.png)

But stderr swallowed:

![Screen Shot 2022-03-21 at 4 17 28 PM](https://user-images.githubusercontent.com/728060/159375575-d4c6fc7b-91b8-4287-bab7-b5a76fb54a00.png)

Visidata works as pager in litecli:

![Screen Shot 2022-03-21 at 4 51 13 PM](https://user-images.githubusercontent.com/728060/159376036-e4b1d5ab-da88-49c3-82af-6643f07f060f.png)

But stderr is not swallowed:

![Screen Shot 2022-03-21 at 4 51 55 PM](https://user-images.githubusercontent.com/728060/159376043-fb3fa656-cb86-449e-9cf9-27d6daa5bcfe.png)

For some reason using Visidata only works as a pager in pgcli with `csv` format and not `tsv` (like I have set with litecli). If set to tsv, the pager seems to be ignored.

Running on Mac Big Sur 11.6.4 and pgcli version Version: 3.4.1.

**Comment by amjith** [comment]
@lelit I think you ran into a similar issue earlier. Were you able to fix the issue?

**Comment by amjith** [comment]
I'm able to reproduce the issue. I'll take a deeper look into why this is happening. Sorry about the issue.

**Comment by amjith** [comment]
Here's the pending PR: https://github.com/dbcli/pgcli/pull/1341

You can install this locally with this command: 

```
pip install -U https://github.com/dbcli/pgcli/archive/refs/heads/fix-csv-status.zip
```

Can you give that a try? 


@lelit I believe you worked on ensuring the csv format works well with pspg pager. Can I ask your help to verify that this won't break the integration with pspg?

**Comment by lelit** [comment]
Yes, I will try that out and report back

**Comment by waydegg** [comment]
@amjith I just installed the pending PR and stderr is visible now.

**Comment by kbd** [comment]
> I think it would be nice if stderr wasn't read by Visidata though, and instead just printed out in the command line.

Given that litecli works the right way -- it prints the error inline (see original screenshot) -- why can't pgcli?
