### ISSUE TITLE
Move log and history out of `~/.config` to `~/.cache`

### ISSUE THREAD

**Issue by SuperSandro2000** [dbcli/pgcli#1331]
## Description
Frequently changing log and history files do not belong into `~/.config`, they would much rather fit into `~/.cache`

## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

I am using pgcli 3.3.1 with nixpkgs on Ubuntu 21.10.

**Comment by amjith** [comment]
Moving these files to different locations adds confusion during support queries. I don't believe we will change the location without a compelling reason.

**Comment by SuperSandro2000** [comment]
> I don't believe we will change the location without a compelling reason.

It is not compliant with https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#basics and makes dotfile management (e.g. with home-manager) harder because random, frequently changing files are sprinkled into `~/.config`.
