### ISSUE TITLE
Ignore all duplicates

### ISSUE THREAD

**Issue by rightaway** [dbcli/pgcli#1334]
Running 2 commands over and over adds them all to the history file without removing the older ones. And when you press up arrow you keep coming across the duplicates again. You should only see a command once in the up arrow history. zsh has `histignorealldups` which does it like this. Can similar feature be added here?

**Comment by amjith** [comment]
@rightaway I don't see this behavior. I tried running the same command multiple times and duplicates are not added to the history. Also pressing the up arrow only cycles through unique command and doesn't have duplicates. 

Perhaps you're using an older version. Try upgrading and report back if you're still seeing this issue.
