### ISSUE TITLE
"CryptographyDeprecationWarning: Blowfish has been deprecated"

### ISSUE THREAD

**Issue by warcayac** [dbcli/pgcli#1343]
After Manjaro was updated I'm getting this message when running pgcli for any operation:
```
~/.local/lib/python3.10/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
```

PGCLI version: **3.4.1**

**Comment by j-bennet** [comment]
This is fixed in Paramiko 2.11.0:

https://github.com/paramiko/paramiko/pull/2039

You can update paramiko with:

`pip install --update paramiko`.
