### ISSUE TITLE
Feature request: Support GCP Cloud SQL

### ISSUE THREAD

**Issue by carlpett** [dbcli/pgcli#1361]
## Description
I'm primarily working with Postgres databases hosted on Google Cloud with IAM auth and private IPs. This means I cannot reach the database without having the [`cloud_sql_proxy`](https://github.com/GoogleCloudPlatform/cloudsql-proxy/) program running.

Would it be in scope for pgcli to integrate [Google's library](https://github.com/GoogleCloudPlatform/cloud-sql-python-connector)?

**Comment by WojciechRydel** [comment]
@carlpett I agree, it would be nice to have that. Though, while waiting for that, I have just made https://github.com/WojciechRydel/gcp-sql-proxy which allows you to run the proxy as systemd service in the background. Even for several at once. Would love to hear your thoughts!

**Comment by n14s** [comment]
Would love to see it as well :)

**Comment by gmile** [comment]
Something I'd be very interested in using too.

**Comment by carlpett** [comment]
@j-bennet Was very happy to see this marked as completed, but I cannot see any actual changes that implements this? Is it implemented in some library and pulled in, or is was it more of a "not prioritized" close?
