### ISSUE TITLE
LGTM service shutting down 12/22

### ISSUE THREAD

**Issue by ERYoung11** [dbcli/pgcli#1365]
## Description

The service which the PGSQL pull request workflow depends on, LGTM will be shutting down in Dec 2022.
https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/

## Your environment

- [x] Please provide your OS and version information.
- [x] Please provide your CLI version.
- [x] What is the output of ``pip freeze`` command.

**Comment by amjith** [comment]
We haven't been relying on LGTM bot for a while now. I'm happy to remove it from CI unless you have a different solution in mind.

**Comment by ERYoung11** [comment]
Honestly, I'm too ignorant to understand whether it's a real issue or not.  I noticed that LGTM was showing up on my PRs and wanted to make sure you all had seen the announcement in case it could be an issue.  It looks like they will provide a conversion to the new github version anyway.  

I mostly wanted to make sure you were aware.  You're aware, so I'll close this Issue.  Thanks!
