### ISSUE TITLE
'Connection' object has no attribute 'server_version' ... 

### ISSUE THREAD

**Issue by Jakubzik** [dbcli/pgcli#1370]
## Description

Getting 'Connection' object has no attribute 'server_version' when calling \df
SQL statements work fine

## Your environment

Arch Linux (5.15.67-1-lts), i3, st as terminal
pgcli 3.5.0
PostgreSQL 14.5

pip freeze:
anytree==2.8.0
appdirs==1.4.4
apsw==3.38.5.post1
argcomplete==2.0.0
async-timeout==4.0.2
autocommand==2.2.1
backports.csv==1.0.7
beautifulsoup4==4.11.1
Brotli==1.0.9
brotlicffi==1.0.9.2
btrfsutil==5.19.1
CacheControl==0.12.11
cchardet==2.1.7
certifi==2022.9.14
cffi==1.15.1
chardet==5.0.0
cli-helpers==2.2.0
click==8.1.3
colorama==0.4.5
commonmark==0.9.1
configobj==5.1.0.dev0
contextlib2==21.6.0
cryptography==38.0.1
css-parser==1.0.7
cssselect==1.1.0
cupshelpers==1.0
Cython==0.29.32
distlib==0.3.6
distro==1.7.0
dnspython==2.2.1
docutils==0.19
entrypoints==0.4
feedparser==6.0.10
filelock==3.8.0
future==0.18.2
gpg==1.18.0
html2text==2020.1.16
html5-parser==0.4.10
html5lib==1.1
humanize==3.1.0
idna==3.4
ifaddr==0.2.0
imaplib2==3.6
importlib-metadata==4.8.3
inflate64==0.1.3
inflect==6.0.0
jaraco.context==4.1.2
jaraco.functools==3.5.1
jaraco.text==3.9.1
jeepney==0.8.0
Jinja2==3.1.2
keyring==23.9.0
lensfun==0.3.3
lockfile==0.12.2
louis==3.23.0
lxml==4.9.1
Markdown==3.4.1
MarkupSafe==2.1.1
mechanize==0.4.8
meson==0.63.2
more-itertools==8.13.0
msgpack==1.0.4
multivolumefile==0.2.3
netifaces==0.11.0
netsnmp-python==1.0a1
nspektr==0.4.0
offlineimap==8.0.0
openshot-qt==2.6.1
ordered-set==4.1.0
packaging==21.3
pdftotext==2.2.2
pendulum==2.1.2
pep517==0.13.0
pgcli==3.5.0
pgspecial==1.13.0
Pillow==9.2.0
pipx==1.1.0
platformdirs==2.5.2
ply==3.11
progress==1.6
prompt-toolkit==3.0.31
psutil==5.9.1
psycopg==3.1.1
psycopg-c==3.1.1
psycopg2==2.9.3
py7zr==0.19.0
pybcj==1.0.1
pycairo==1.21.0
pychm==0.8.6
pycparser==2.21
pycryptodome==3.15.0
pycryptodomex==3.12.0
pycups==2.0.1
pycurl==7.45.1
pydantic==1.10.2
Pygments==2.11.1
PyGObject==3.42.2
pyOpenSSL==22.0.0
pyparsing==3.0.9
pyppmd==1.0.0
PyQt5==5.15.7
PyQt5-sip==12.11.0
PyQt6==6.3.1
PyQt6-sip==13.4.0
PyQt6-WebEngine==6.3.1
PyQtWebEngine==5.15.6
PySocks==1.7.1
python-dateutil==2.8.2
pytzdata==2020.1
PyYAML==6.0
pyzmq==23.2.0
pyzstd==0.15.3
qutebrowser==2.5.2
ranger-fm==1.9.3
regex==2022.8.17
reportlab==3.6.11
requests==2.28.1
requests-file==1.5.1
resolvelib==0.8.1
retrying==1.3.3
rfc6555==0.1.0
rich @ file:///build/python-rich/src/rich-12.5.1/dist/rich-12.5.0-py3-none-any.whl
SecretStorage==3.3.3
selectors2==2.0.2
setproctitle==1.3.1
sgmllib3k==1.0.0
simplejson==3.17.6
six==1.16.0
soupsieve==2.3.2.post1
sqlparse==0.4.2
tabulate==0.8.10
TBB==0.2
tenacity==8.0.1
terminaltables==3.1.0
texttable==1.6.4
tldextract==3.3.1
toml==0.10.2
tomli==2.0.1
torbrowser-launcher==0.3.5
trove-classifiers==2022.8.31
typing_extensions==4.3.0
unrardll==0.1.5
urllib3==1.26.12
userpath==1.8.0
validate==5.1.0.dev0
validate-pyproject==0.10.1
visidata==2.10.1
wcwidth==0.2.5
webencodings==0.5.1
youtube-dl==2021.12.17
zeroconf==0.39.0
zipfile-deflate64==0.2.0
zipp==3.8.1

Thank you for getting me back on my feet!

**Comment by j-bennet** [comment]
Hi @Jakubzik ,

I have the same versions of pgcli and `psycopg` as you do, and I don't get this error. However, I have a different version of `pgspecial`:

```
pgcli==3.5.0
pgspecial==2.0.1
psycopg==3.1.1
```

I'm also surprised that you were able to install pgcli==3.5.0, and pgspecial was not updated, since we pin it to `>=2.0.0` in 3.5.0:

https://github.com/dbcli/pgcli/blob/c280f8e398662e43a1637c6918700f0883baea1c/setup.py#L9

I'm not sure if that's the problem, but can you try updating pgspecial? If you installed pgcli with pip, then:

`pip install -U pgspecial`

If updating doesn't help, please attach the pgcli log file, so we can see where it breaks exactly. It should be located at `~/.config/pgcli/log`.

**Comment by Jakubzik** [comment]
Thank you very much, this solved the problem: pgspecial asked for an update of cli-helpers (from 2.2.0 to 2.2.1). After running 

`pip install -U pgspecial cli_helpers`

everything works like a charm again.

**Comment by j-bennet** [comment]
Ok, great. I'll close the issue.
