### ISSUE TITLE
in windows there is no response when entered sql

### ISSUE THREAD

**Issue by yukungis** [dbcli/pgcli#138]
In windows,when I entered the sql,then press enter key,but there is no response in command line.

**Comment by darikg** [comment]
I believe that's [this issue](jonathanslenders/python-prompt-toolkit#86) which is happening in python-prompt-toolkit on windows in python 2.7. If it is, you can press control+enter instead.

**Comment by amjith** [comment]
Issue: https://github.com/jonathanslenders/python-prompt-toolkit/issues/86

Fix the link in the Darik's comment.

**Comment by yukungis** [comment]
my python version is 3.4.
If I press ctrl+enter ,It will produces errors like this.
![error](https://cloud.githubusercontent.com/assets/1825425/5914394/ee136b40-a62f-11e4-9861-0f30a59400c0.png)

**Comment by amjith** [comment]
@yukungis  Can you try the latest version? It has a new upgraded version of prompt_toolkit. 

You can upgrade using: 

```
pip install -U pgcli
```

**Comment by amjith** [comment]
Feel free to reopen if the issue still persists.
