### ISSUE TITLE
Make pgcli the default for django's dbshell command. 

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#139]
Django has a helper method to launch the respective database client using the django-admin.py dbshell.

Right now it defaults to psql for postgres, it'll be nice to use pgcli if it is installed and then fall back to psql. 

https://github.com/django/django/blob/master/django/db/backends/postgresql_psycopg2/client.py

**Comment by thedrow** [comment]
Yes please!

**Comment by schinckel** [comment]
You could just write a management command: although that would require installing an app in your `settings.INSTALLED_APPS`.

**Comment by amjith** [comment]
https://github.com/ashchristopher/django-pgcli

Created by a friend. :)

Thanks @ashchristopher.
