### ISSUE TITLE
Wrapping on long JSONB rows?

### ISSUE THREAD

**Issue by zefoo** [dbcli/pgcli#1394]
Howdy. 

```
$ pgcli --version                                                                                                     |
Version: 3.4.1
```

I've been tolerating this for a while... finally going to see if there is something I don't know. :) Love pgcli, use it every day. Is there a way to wrap text on a very long column with a very long JSONB value? It keeps getting cut off and I want to pull it into another program to analyze rather than scrolling right. 

Thank you!

**Comment by amjith** [comment]
You can try a different table format using the `\T ` command. 

You should see a list of options. I sometimes use the `\T vertical` to get long line of JSON.

**Comment by j-bennet** [comment]
We also have`max_field_width` in config settings:

https://github.com/dbcli/pgcli/blob/141873f86d299a7c8469392367b820960d01707a/pgcli/pgclirc#L140

You can leave the value blank to disable long field truncation, but formatting a large batch of rows like that may get slow.

**Comment by zefoo** [comment]
Thank you! 

I tried every \T option, everything requires me to scroll manually to the right. 

If I do `max_field_width`, it cuts the field and doesn't show all the data.

eg. Right now I see this:

```
skills-pool> SELECT * from transactions WHERE other->>'DocNumber' = 'CM-414' and org_id = 3;
-[ RECORD 1 ]-------------------------
id                      | 14372
api_id                  | 45
user_id                 | <null>
other                   | {"RemainingCredit": 750.0, "domain": "QBO", "sparse": false, "Id": "465", "SyncToken": "0", "MetaData": {"CreateTime": "2023-02-22T08:29:07-08:00", "LastUpdatedTime": "2023-02-2>
created                 | 2023-02-22 16:29:07.543557+00
updated                 | 2023-02-22 18:11:11.743104+00

SELECT 1
```

Success looks like the JSON data wrapping nicely and/or looking "pretty" so it's more readable. It seems right now the only possibility I have is to export the result to a file and open it that way. Otherwise I have to manually scroll to the right until I can see the entire row. Hope this makes more sense, I could have shared more originally.

**Comment by amjith** [comment]
I see. 

We don't have a way to pretty print the JSON in the output. You could set the pager to `cat` so it doesn't do the right scrolling but JSON won't be pretty printed. 

```
pgcli> \pager cat
```

**Comment by zefoo** [comment]
@amjith - that is EXACTLY what I was looking for. I have been wanting this for years. Thank you.

**Comment by amjith** [comment]
You can also set this option in your config file so you don't have to keep doing this in every session. 

```
pager = cat
```

**Comment by atten** [comment]
`\x` (toggle expanded mode) also works for long lines

**Comment by im-n1** [comment]
The ultimate is to toggle between pagers cat and less. Cat wraps long lines but sometimes it's useful to have a nice table without wrapped table decorations - thats what less is good for.
