### ISSUE TITLE
Add support for pypy

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#140]
Right now pgcli won't work in pypy because psycopg2 won't install for pypy. But there is psycopg2cffi for pypy.

**Comment by thedrow** [comment]
It also works for PyPy 3 FYI.

**Comment by veegee** [comment]
An alternative is to use pg8000. Is there a really hard dependency on psycopg2?

**Comment by amjith** [comment]
@veegee That's interesting. I didn't know of it's existence. There is no hard dependency but I'd like the library to handle unicode stuff correctly. I'll check it out. Thank you!

**Comment by thedrow** [comment]
Pyscopg2cffi is a good library and you'll use it anyway if you're using PyPy.

**Comment by wulczer** [comment]
AFAIK both psycopg2cffi and psycopg2ct are drop-in PyPy-compaible replacements for psycopg2.

This is how txpostgres handles it: https://github.com/wulczer/txpostgres/blob/master/txpostgres/psycopg2_impl.py

**Comment by amjith** [comment]
@wulczer Thank you for the reference implementation. That looks useful.

The piece that confuses me, is how to list the necessary dependency for it in setup.py based on the interpreter. Because I need to choose psycopg2 for CPython and psycopg2cffi for PyPy at installation time.

Maybe psycopg2cffi just work in both CPython and PyPy and I can include that as the dependency instead of psycopg2. 

I have not tried that.

**Comment by thedrow** [comment]
@amjith cffi is slower on CPython.

**Comment by amjith** [comment]
@thedrow I just tried it out locally. It doesn't seem noticeably slower. Since this is a CLI, I think the speed difference will be negligible. It's not like people going to expect high throughput because the number of queries executed will be limited by how fast you can type them in. 

Unless it is significantly slower for some use cases that I haven't tried yet.

**Comment by thedrow** [comment]
I haven't tried every possible usecase but that's a rule of thumb.
Also note that psycopg2cffi is a few patch versions behind.

**Comment by amjith** [comment]
I tried using psycopg2cffi but it breaks on unicode. I've filed a bug https://github.com/chtd/psycopg2cffi/issues/32. 

Waiting to hear back.

**Comment by d33tah** [comment]
What's the current status of the issue? Is there any patch that I could test and work on?

**Comment by amjith** [comment]
This is in the back burner now. I'm not really interested in making this a priority since psycopg2cffi isn't quite as stable as psycopg2. 

Without that it is not possible to add pypy support. 

Is there a specific reason you're interested in getting this working in PyPy?

**Comment by d33tah** [comment]
I'm interested in testing pgcli on a billion-row-scale database and I'm a bit worried about the performance.

**Comment by amjith** [comment]
I doubt that you'll get significant boost from using PyPy. Because most of the time is spent in I/O which PyPy won't be of help.

Since psycopg2 is C-extension you'll get the same performance characteristic between CPython and PyPy.

**Comment by Julian** [comment]
+1 on this, we run nothing but PyPy (and have been running psycopg2cffi in prod directly for awhile with no issue) so would be great to be able to use pgcli.
