### ISSUE TITLE
bash: pgcli not found after port forwarding in vscode

### ISSUE THREAD

**Issue by SimerdeepSinghGrewal** [dbcli/pgcli#1401]
## Description
HI, I recently started de-zoomcamp and I was setting up everything when I encountered this problem. I am extreme new to this, so need help. I forwarded the port in VS code and then tried to execute this command in git bash new window, without ssh to my instance "pgcli -h localhost -U root -d ny_taxi"  this gave me error "bash: pgcli: command not found"
I am lost now, coz dont have any idea what to do to solve this, tried deleting fwd port and again entering it but nothing, restarted laptop but again same error

## Your environment

following this zoomcamp
https://www.youtube.com/watch?v=ae-CV2KfoN0&list=PL3MmuxUbc_hJed7dXYoJw8DoCuVHhGEQb&ab_channel=DataTalksClub%E2%AC%9B
I am at 33mins and this forwarding this started may be at 31mins.
- [ ] Please provide your OS and version information.
- GCP has ubuntu instance
- [ ] Please provide your CLI version.
- docker/compose version is v2.17.2
- [ ] What is the output of ``pip freeze`` command.
- $ pip freeze
asttokens==2.0.5
backcall==0.2.0
beautifulsoup4==4.11.1
bs4==0.0.1
certifi==2021.10.8
charset-normalizer==2.0.12
click==8.1.3
colorama==0.4.4
colorgram.py==1.2.0
debugpy==1.6.0
decorator==5.1.1
dnspython==2.2.1
dominate==2.6.0
email-validator==1.2.1
entrypoints==0.4
executing==0.8.3
Flask==2.1.2
Flask-Bootstrap==3.3.7.1
Flask-WTF==1.0.1
html-to-json==2.0.0
idna==3.3
ipykernel==6.13.0
ipython==8.2.0
itsdangerous==2.1.2
jedi==0.18.1
Jinja2==3.1.2
jupyter-client==7.3.0
jupyter-core==4.10.0
MarkupSafe==2.1.1
matplotlib-inline==0.1.3
nest-asyncio==1.5.5
numpy==1.22.2
packaging==21.3
pandas==1.4.1
parso==0.8.3
pickleshare==0.7.5
Pillow==9.0.1
prompt-toolkit==3.0.29
psutil==5.9.0
pure-eval==0.2.2
Pygments==2.12.0
pyparsing==3.0.8
python-dateutil==2.8.2
pytz==2022.1
pywin32==303
pyzmq==22.3.0
requests==2.27.1
selenium==3.141.0
six==1.16.0
soupsieve==2.3.2.post1
stack-data==0.2.0
tornado==6.1
traitlets==5.1.1
urllib3==1.26.9
utils==1.0.1
visitor==0.1.3
wcwidth==0.2.5
Werkzeug==2.1.2
WTForms==3.0.1

**Comment by j-bennet** [comment]
Hey @SimerdeepSinghGrewal,

I looked briefly at de-zoomcamp tutorial that you linked, I didn't have the time to watch the whole video. The person who created the tutorial does a lot of things there, and so many could go wrong. From what I can see:

- he is running a Postgres instance on Ubuntu in GCP
- he is forwarding the remote port to his local machine which runs Windows
- he is using pgcli installed via `conda` or `pip` to talk to postgres. In both cases, he actually gets quite a few errors.

So, `psql` should be installed on your local (in this case Windows) machine. If you installed it successfully, you should be able to run it. If it didn't install successfully, you need to solve that problem first, and from your `pip freeze` output, I don't see `pgcli` listed, so it wasn't installed successfully. Did you encounter any errors during installation? Was it with `conda` or `pip` that you tried to install it? What's your python version (which you can check with `python --version`? Newer versions of pgcli use the `psycopg` library, which supports python 3.7+:

https://www.psycopg.org/psycopg3/docs/basic/install.html#supported-systems

Let me make something else clear as well. `pgcli` is not a necessary tool for this tutorial. This could use any PostgreSQL client. The official client for postgresql is `psql`, which has a binary installer and you can just use that:

https://www.postgresql.org/download/windows/

The commands would be the same, you would just replace `pgcli` with `psql`.

I hope this helps. This doesn't look like an easy tutorial for someone who is completely new to the subject. Bt I have a feeling that you don't even need pgcli in there. It shouldn't be a stumbling block.

**Comment by dbaty** [comment]
Thanks for digging in! I suppose that the reporter has found a solution since April. I am closing this issue.
