### ISSUE TITLE
Is it ok to add pgcli as 1password shell plugin?

### ISSUE THREAD

**Issue by szymon** [dbcli/pgcli#1418]
Hi, as I'm not affiliated with either projects I just wanted to make sure if it's ok to add pgcli as a 1Password shell plugin (or at least try to add it)?

1Password has a cli support for plugins which can load credentials from vault, populate env and lunch the program.

**Comment by j-bennet** [comment]
Hi @szymon,

Do I understand correctly that you want to build a shell plugin for 1Password to authenticate with pgcli, and create a PR in here?

https://github.com/1Password/shell-plugins

**Comment by szymon** [comment]
exactly. The one I'm using locally is just swapped psql with pgcli and it works perfectly.

As I'm using it almost daily I'll be happy to fix it if something breaks.

**Comment by j-bennet** [comment]
Sure @szymon , go ahead. Why not, if it solves a need.

**Comment by dbaty** [comment]
OP contributed this in 1Password's repository: https://github.com/1Password/shell-plugins/commit/b4e7b26416b8826a74ce31b51af555494f0c986c.
