### ISSUE TITLE
Readme link - this page has moved

### ISSUE THREAD

**Issue by Tamir198** [dbcli/pgcli#1468]
When clicking on this : 

![image](https://github.com/dbcli/pgcli/assets/34707669/c8dc9048-0206-4b6f-b920-969513bcd1e2)

We see this : 

![image](https://github.com/dbcli/pgcli/assets/34707669/c37f25a3-8042-4b6d-877d-6a726f99abde)

After the site redirects us to the correct page maybe we can fix this link so it will go straight into the correct link.

**Comment by dbaty** [comment]
Good point, I'll fix this in #1469.

Thanks for the report! :)
