### ISSUE TITLE
error while retoring dump with zstd compreesion.

### ISSUE THREAD

**Issue by allanegidio** [dbcli/pgcli#1473]
## Description
I'm trying to restore one dump, but I'm facing this problem: 
```
pg_restore: warning: archive is compressed, but this installation does not support compression (this build does not support compression with zstd) -- no data will be available
pg_restore: error: cannot restore from compressed archive (this build does not support compression with zstd)
```

There is a possibility to add support for pg restore for work with this dump file? 

## Your environment
MAC OS 14.4.1
PGCLI 4.1.0

- [x] Please provide your OS and version information.
- [x] Please provide your CLI version.
- [x] What is the output of ``pip freeze`` command.

**Comment by dbaty** [comment]
Can you clarify which command you run? The error message seems to show that you are running pg_restore, not pgcli.

**Comment by dbaty** [comment]
No answer, I close this. Feel free to reopen with details.
