### ISSUE TITLE
how to provide password by command line option.

### ISSUE THREAD

**Issue by bestgopher** [dbcli/pgcli#1476]
## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

**Comment by dbaty** [comment]
Just like psql, pgcli does not have any command line option to provide the password. Alternatives:

- set the `PGPASSWORD` environment variable (see [PostgreSQL documentation](https://www.postgresql.org/docs/current/libpq-envars.html#LIBPQ-ENVARS) for warnings). For example: `PGPASSWORD=my-password pgcli -d my-database -U my-user`

- use a connection string. For example: `pgcli postgresql://my-user:my-password@localhost:5432/my-database`

Also, note that pgcli supports `.pgpass`. See [PostgreSQL documentation](https://www.postgresql.org/docs/current/libpq-pgpass.html) for further details.

For future questions, please open a new discussion [here](https://github.com/dbcli/pgcli/discussions).

**Comment by bestgopher** [comment]
Thanks for your reply.
