### ISSUE TITLE
Rendering is broken when pgcli is started in a subprocess

### ISSUE THREAD

**Issue by zoiman** [dbcli/pgcli#1480]
## Description

I am using 1password cli to inject the db password to PGPASsWORD so I can connect with pgcli without having the password in some plaintext on my machine.

The way it works is that you run 1password cli which injects the passwords in the env var for the process it kicks off. So I am doing this:
```
op run --env-file="/Users/zoiman/.config/pgcli/dev.env"  -- pgcli -D dev
```

This works and I can see somehow that I connected, however the rendering is completly broken. There is  no color, and the user input is on the wrong place. It looks like the UI drawing does not work at all.

## Your environment

- [x] Please provide your OS and version information.
macOS: 14.6.1 (23G93)
- [x] Please provide your CLI version.
Version: 4.1.0

**Comment by zoiman** [comment]
I found the solution, apparently the masking of passwords for stdout was messing with it. When adding the `--no-mask` flag it works

**Comment by j-bennet** [comment]
Thank you for writing back @zoiman, this will be helpful to others.
