### ISSUE TITLE
Wrapped grid mode

### ISSUE THREAD

**Issue by wbolster** [dbcli/pgcli#162]
It would be awesome if `pgcli` could grow a wrapped `fancy_grid` output, similar to what `\pset format wrapped` in `psql` does when long column values are shown.

**Comment by amjith** [comment]
Yeah, that would be nice. Auto-detecting the screen-size and adjusting the table width seems a bit tricky, but probably doable.

**Comment by amjith** [comment]
We've started leveraging the pager to do horizontal scrolling when the output is too wide to fit the screen. 

Try an upgrade:

```
pip install -U pgcli
```

**Comment by vinayak-mehta** [comment]
:tada:
