### ISSUE TITLE
Upgrade prompt_toolkit dependency

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#168]
pgcli still depends on prompt_toolkit version 0.26. The current version of prompt_toolkit is 0.31. 

It's time to upgrade the dependency.

**Comment by svenstaro** [comment]
:+1: In Arch, we usually have only the most recent version so pgcli is currently broken over there.

**Comment by amjith** [comment]
:(

I didn't know it was broken on Arch. 

Do you have the latest prompt_toolkit because you're using ptpython? Because you wouldn't be installing the latest version unless you have another package that is dependent on the newer version.

**Comment by svenstaro** [comment]
There is an AUR package that I maintain that gets the current version of prompt toolkit and that happens to be 0.31.

**Comment by amjith** [comment]
You're killing me @svenstaro. :)

Just kidding. That's a good incentive for me to work on this issue. I'll tackle it once I get back from PyCon.

**Comment by amjith** [comment]
Done!

Available in the latest version 0.17.0. Please upgrade using: 

```
pip install -U pgcli
```
