### ISSUE TITLE
non-ascii character make pgcli crash

### ISSUE THREAD

**Issue by jradix** [dbcli/pgcli#171]
Hello,

My conf :

windows 7 64bits - French, with French keyboard layout.
python 2.7.9 x86
psycopg2-2.6.0.win32-py2.7-pg9.4.1-release.exe
cmder 1.1.4.100 with codepage 850

Installing pgcli works on windows (`pip install pgcli`).

But when I enter a non-ascii character (a character of cp 850, like this one : `é` ), pgcli crashes with the following error message : 

    λ pgcli -h 127.0.0.1 postgres
    Version: 0.16.1
    Chat: https://gitter.im/amjith/pgcli
    Mail: https://groups.google.com/forum/#!forum/pgcli
    Home: http://pgcli.com
    postgres> Traceback (most recent call last):
      File "C:\bin\python2-x86_32\Scripts\pgcli-script.py", line 9, in <module>
        load_entry_point('pgcli==0.16.1', 'console_scripts', 'pgcli')()
      File "C:\bin\python2-x86_32\lib\site-packages\click\core.py", line 610, in __call__
        return self.main(*args, **kwargs)
      File "C:\bin\python2-x86_32\lib\site-packages\click\core.py", line 590, in main
        rv = self.invoke(ctx)
      File "C:\bin\python2-x86_32\lib\site-packages\click\core.py", line 782, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "C:\bin\python2-x86_32\lib\site-packages\click\core.py", line 416, in invoke
        return callback(*args, **kwargs)
      File "C:\bin\python2-x86_32\lib\site-packages\pgcli\main.py", line 344, in cli
        pgcli.run_cli()
      File "C:\bin\python2-x86_32\lib\site-packages\pgcli\main.py", line 189, in run_cli
        document = cli.read_input(on_exit=AbortAction.RAISE_EXCEPTION)
      File "C:\bin\python2-x86_32\lib\site-packages\prompt_toolkit\__init__.py", line 251, in read_input
        next(g)
      File "C:\bin\python2-x86_32\lib\site-packages\prompt_toolkit\__init__.py", line 313, in _read_input
        loop_result = self.eventloop.loop()
      File "C:\bin\python2-x86_32\lib\site-packages\prompt_toolkit\eventloop\win32.py", line 44, in loop
        keys = self._console_input_reader.read()
      File "C:\bin\python2-x86_32\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 121, in read
        key_presses = self._event_to_key_presses(ev)
      File "C:\bin\python2-x86_32\lib\site-packages\prompt_toolkit\terminal\win32_input.py", line 141, in _event_to_key_presses
        result = KeyPress(ev.AsciiChar.decode('ascii'), ev.AsciiChar.decode('ascii'))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 0: ordinal not in range(128)

**Comment by amjith** [comment]
Thanks for reporting the bug. The issue seems to arise from [prompt_toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) which is a dependent library for pgcli.

It looks like there is already a pending github issue for this problem: https://github.com/jonathanslenders/ptpython/issues/13

I don't have a windows machine to try this, so I'm unable to try it out or fix it. 

@draikg I know you use pgcli on windows can you try it out and let me know if there is a way to fix it?

**Comment by darikg** [comment]
Sure, I'll try poking around a bit.

**Comment by amjith** [comment]
@jradix Can you try out the latest version 0.17.0. This uses the very latest `prompt_toolkit`. 

Please upgrade using: 

```
pip install -U pgcli
```

**Comment by jradix** [comment]
I still get the same error message when I press a non-ascii key :

![image](https://cloud.githubusercontent.com/assets/11317551/7831451/2230b3da-0457-11e5-9d62-1f93f8e00d69.png)

**Comment by jradix** [comment]
Just for you to see that I have correctly installed pgcli :

![image](https://cloud.githubusercontent.com/assets/11317551/7831487/7f0c9312-0457-11e5-9eed-1c096722c4bc.png)

**Comment by amjith** [comment]
Thanks for checking that. I presume you're using cmd.exe as your terminal. If so, can you try changing the character encoding using the following command before launching `pgcli`? 

```
> chcp 65001
> pgcli
```

I'm not really familiar with Windows and I got that info from reading stackoverflow: http://stackoverflow.com/questions/1259084/what-encoding-code-page-is-cmd-exe-using

**Comment by jradix** [comment]
No, it's not an encoding problem. I'm using cmder but it's the same problem on cmd.exe :

![image](https://cloud.githubusercontent.com/assets/11317551/7859071/e6dfd9e0-053d-11e5-9de0-d23e228b6b37.png)

The 65001 encoding is not working :

![image](https://cloud.githubusercontent.com/assets/11317551/7859051/a6438828-053d-11e5-8b1b-8e167ce83d53.png)

**Comment by darikg** [comment]
Last time I tried looking into this, I got as far as [this](https://github.com/jonathanslenders/python-prompt-toolkit/blob/0b4a2424b1ed3cf4c4975492f34f37d53080ba0d/prompt_toolkit/terminal/win32_input.py#L114). It's calling `ReadConsoleInputA`, specically requesting an ascii character. According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684961(v=vs.85).aspx) (linked in the comments there), it should be possible to replace that call with `ReadConsoleInputW` instead, but I got in over my head there with C types and gave up

**Comment by amjith** [comment]
@darikg That's impressive progress. We should report this progress back to @jonathanslenders, see if he has an insight into that method. I'll leave a comment on the prompt_toolkit ticket (https://github.com/jonathanslenders/ptpython/issues/13) with your findings.

**Comment by jonathanslenders** [comment]
So, it looks like I got a fix for it in prompt_toolkit. As soon as I have a release ready, I'll try to create a pull request to upgrade pgcli as well. There are some more API changes.

**Comment by amjith** [comment]
@jradix This is now fixed in master. Can you try installing directly from master and trying again? 

```
pip install -U -e git+https://github.com/dbcli/pgcli.git#egg=pgcli
```

**Comment by amjith** [comment]
This is now fixed in the latest released version of pgcli. Please upgrade to v0.18.0.
