### ISSUE TITLE
Support for more back-slash commands

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#188]
\e, \ef, \sf, \z, \do, \dT, \du, \copy and \watch

From reddit: http://www.reddit.com/r/PostgreSQL/comments/31n0d9/screencast_pgcli_basics_intro_to_installation/cq31v4j?context=3

**Comment by j-bennet** [comment]
Amjith, do you mind if I take this one?

**Comment by amjith** [comment]
Go for it. 

Just a hint, the \e is supposed to launch an editor to edit the query. It is possible to do that, using the `click` module that is already used by pgcli. http://click.pocoo.org/4/utils/#launching-editors

**Comment by masonjm** [comment]
+1. It would be nice if \x worked, as well.

**Comment by amjith** [comment]
@masonjm The \x is already implemented. It should work just like psql. Unless you have a very old version of pgcli. In which case you should consider upgrading.

You can upgrade using `pip install -U pgcli` or `brew update && brew upgrade pgcli`. Depending on how you installed it originally.

**Comment by masonjm** [comment]
Sure enough. Brew gave me 0.10.2 originally.

Thanks :).

**Comment by Graham42** [comment]
+1 for `\copy`

**Comment by boblannon** [comment]
+1 for `\copy`

**Comment by amjith** [comment]
I have to set some reasonable expectations. I have not used `\copy` myself. 

Little bit of researching makes me think that it is ridiculously hard to implement. But I did find some relevant functions in psycopg2 that might make it easy. http://initd.org/psycopg/docs/usage.html#using-copy-to-and-copy-from

@drocco007 @darikg Either of you have experience using `\copy`?

**Comment by j-bennet** [comment]
@amjith This looks pretty amazing (psycopg2). I'm starting to think it's not as impossible as we thought.

**Comment by boblannon** [comment]
one relevant distinction that should be made: the postgres `COPY` command is not the same as psql's `\copy` command.  from 9.4 docs:

> Do not confuse COPY with the psql instruction \copy. \copy invokes COPY FROM STDIN or COPY TO STDOUT, and then fetches/stores the data in a file accessible to the psql client. Thus, file accessibility and access rights depend on the client rather than the server when \copy is used.

that might constrain the development task significantly.  i bet limiting the expectations to supporting `\copy` behavior will satisfy many, many users.  it's often the case that non-superusers can't even execute `COPY`

**Comment by darikg** [comment]
I'm +1 on \copy, but I don't know anything about how it works. From @boblannon's comment it sounds like a `\copy` command could be transformed into a SQL `COPY` command and then sent to `psycopg2.copy_expert`?

**Comment by amjith** [comment]
This release adds `\e` and `\dT`. 

Please upgrade using: 

```
pip install -U pgcli
```

**Comment by Fire-** [comment]
I use `\copy` on a regular basis to export data to TSV or CSV with headers and was disappointed to find a lack of this functionality in pgcli. It's kind of a core feature of psql and as far as I can tell pgcli doesn't actually have another way to export queried data?

**Comment by shofetim** [comment]
+1 for `\copy`

**Comment by amjith** [comment]
`\copy` is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
