### ISSUE TITLE
Suggest set-returning functions after the FROM keyword

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#189]
http://www.postgresql.org/docs/9.1/static/functions-srf.html

Set-returning functions should be suggested after the FROM keyword.

**Comment by darikg** [comment]
Totally agreed. Actually it doesn't even need to be restricted to SRFs -- all non-aggregate functions are valid table expressions. E.g. `select * from round(1.1)` returns a 1-row resultset. It's easy to suggest function names -- the tricky part is handling the column names so they can be autocompleted in the SELECT or WHERE clause.

Functions can

1. Declare named output arguments like `CREATE FUNCTION f1 (..., OUT col1 INT, OUT col2 INT)`
in which case `SELECT * FROM f1(...) WHERE <tab>` should suggest col1 and col2. We need to parse the function input argument list to get these names. 

2. Return a table, like `CREATE FUNCTION f2 (...) RETURNS TABLE (col1 INT, col2 INT)`. We need to parse the return expression to get these names.

3. Return a composite type, in which case the column names are the field names of the composite type. 

4. Return an unspecified number of columns, like `CREATE FUNCTION f3 (...) RETURNS SETOF RECORD` in which case the columns need to be specified in the query itself, so e.g. `SELECT * FROM f3(...) AS myfunc (col1 INT, col2 TEXT, ...) WHERE <tab>` should suggest col1 and col2.  

I wrote a bunch of code a while ago to do 1 & 2, but IIRC it relied on some newer changes in sqlparse that haven't been released in a new version yet.

**Comment by amjith** [comment]
Looks like this got closed automatically when I merged #361. I'm going to keep this open until we merge #368.

@darikg I think the changes in #368 covers all the items you had listed here. Is that right?

**Comment by darikg** [comment]
#368 covers items 1 and 2 in the list above. 3 and 4 are a lot more esoteric and I won't be attempting to address them any time soon.

**Comment by j-bennet** [comment]
I'm going to declare this "good enough implementation" and close it.
