### ISSUE TITLE
Fix the failing tests in Travis

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#216]
It seems like the tests are failing on Travis because a new SQLParse library is out and the output format has changed. (Thanks to @darikg for catching that). 

We need to update the tests to match the new format.

**Comment by darikg** [comment]
The tests are right, sqlparse is wrong. The easiest thing to do is just wait for sqlparse to release 0.1.16, where it's been fixed, then pin setup.py to that. In the interim we could pin sqlparse to 0.1.14, before the bug regression, but I don't know what that does to pgcli installed with 0.1.15 'in the wild'

**Comment by amjith** [comment]
It's an install time check, so if someone has 0.1.15 installed then it will continue to work as normal. 

If someone is installing it for the first time it will install 0.1.14 (as expected). But if someone has 0.1.15 installed then install a new version of pgcli it will downgrade their sqlparse to 0.1.14. 

So I think it is safe to assume that we can pin it to 0.1.14 without collateral damage.

**Comment by amjith** [comment]
Thanks for the fix @darikg.
