### ISSUE TITLE
Support for psql environment variables

### ISSUE THREAD

**Issue by micahhausler** [dbcli/pgcli#220]
It'd be awesome to use the `PGPASSWORD="..." pgcli` syntax like psql to set the connecting password

http://www.postgresql.org/docs/9.3/static/libpq-envars.html

**Comment by amjith** [comment]
For some reason I thought we already had support for PGPASSWORD, but looks like we honor PGHOST, PGUSER etc but PGPASSWORD is missing. 

It shouldn't be hard to add. We'll take a stab at it. :)

**Comment by amjith** [comment]
This is now available in version 0.18.0.
