### ISSUE TITLE
Provide a way to update autocomplete without restarting

### ISSUE THREAD

**Issue by chrisanderton** [dbcli/pgcli#225]
If the structure of a table changes, the autocomplete options don't seem to refresh - i assume the definitions are cached somewhere?

It would be good to provide a command to invalidate the cache to avoid having to quit and reload to get the latest structure in the autocomplete..

**Comment by amjith** [comment]
@chrisanderton Can you tell us how you're altering the table? We're automatically refreshing the completion when we encounter a `CREATE` or `ALTER` statement. We're also investigating various ways to auto-detect when schemas are modified (see #211). 

But I'm open to the idea of adding a command called `refresh` or `rehash` which will refresh the autocompletion.

**Comment by chrisanderton** [comment]
I'm not altering the table from within pgcli - in this particular case, another tool i'm working with is setting up tables/altering them - and i am using pgcli to interact with them.

I know when the table has changed - as i have made it happen - so i'd be happy with a manual command instead of auto-detection magic! :)

**Comment by amjith** [comment]
@chrisanderton This is now available in 'master'. You can install directly from master using:

```
pip install -U -e git+https://github.com/dbcli/pgcli.git#egg=pgcli
```

You can refresh the completions using `\#` or `\refresh` commands.
