### ISSUE TITLE
Investigate if it's possible to embed pgcli inside emacs 

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#23]
http://www.emacswiki.org/emacs/SqlMode

**Comment by amjith** [comment]
Closing it since it's a rare use case.

**Comment by gtrak** [comment]
I would like this..

**Comment by tninja** [comment]
+1

**Comment by bandagriss** [comment]
+1

**Comment by agzam** [comment]
pgcli would be awesome as a back-end for ob-sql, so then you could query from org-mode source blocks and have autocompletion, etc.
