### ISSUE TITLE
pgcli can't handle creating functions

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#236]
Typically functions in postgres are multi-line. Here's an example:

```
CREATE FUNCTION delete_address() RETURNS TRIGGER AS $_$
BEGIN
    DELETE FROM address WHERE address.id_user = OLD.id;
    RETURN OLD;
END $_$ LANGUAGE 'plpgsql';
```

But it is impossible to enter this in pgcli, because in multi-line mode we treat a semi-colon at the end of a line to be the end of a query. So at the end of `RETURN OLD;` it will end the query and send it to the server which causes a syntax error. :(

I'm open to suggestions for solving this issue. 

My current thoughts are manipulate the [is_multiline()](https://github.com/dbcli/pgcli/blob/master/pgcli/pgbuffer.py#L9) to do clever things. 

Look into what [ptpython](https://github.com/jonathanslenders/ptpython/tree/master/ptpython) does for multi-line mode and see if we can adopt it's behavior.

**Comment by j-bennet** [comment]
We could use $_$ as a trigger to switch on a "special" multiline mode that would not treat ";" as end-of-query until a second $_$ is encountered.

**Comment by amjith** [comment]
I did some more reading. Looks like this is how postgresql handles this case: 

http://www.postgresql.org/docs/9.1/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING

It seems reasonable. 

We can't rely on just '$_$' but we'll have to treat '$\.*$' as the markers that start and end the special mode. 

We might need a state machine for this since nesting of dollar tags is possible.

**Comment by avesus** [comment]
Thank you. Wonderful that right when I need the functionality, you have just released it!
Also thank you so much for horizontal scrolling of tables with lot of columns!
Best wishes to you and the startup!

**Comment by amjith** [comment]
I'm glad you found the feature useful. 

I'm amused you think this is a startup. This is just a open source project with volunteer contributors. :)

**Comment by j-bennet** [comment]
That's a thought to think on, @amjith. :)

**Comment by avesus** [comment]
> I'm amused you think this is a startup. This is just a open source project with volunteer contributors. :)

[KickStarter's $4800 for mysql-cli](https://www.kickstarter.com/projects/1839007321/mysql-cli) tells me another things. This days all smart geeks make their own start-ups with public open source technology, volunteer contributors and public donations. You really could raise much more on writing specific functionality for people who needs that. Think about system administrators and DBAs of large companies. They will give you a lot of money for even simple things which make their lifes much happier. Think about including your pgcli into official Postgres distribution and into Red Hat's distributions too!

**Comment by amjith** [comment]
Fair enough. Kickstarter was an experiment to see if there was enough demand for a mysql version. Turns out there was. Creating tools is not the issue it's reaching out to the DBAs and finding out what they need which is the tricky bit. 

Even that kickstarter campaign took me an entire month of just promoting it and getting the word out. It didn't reach it's goal until 3 days before the deadline. It was nerve wracking to say the least. 

That said, I haven't discounted the idea of building a product around this in the future. So thanks for the encouragement. :)

**Comment by avesus** [comment]
Thank you for sharing your experience with us! To write code is much better than do public relations. But without the latter our code will be alone. Thank you for the spent month.
