### ISSUE TITLE
Pgcli needs a light theme.

### ISSUE THREAD

**Issue by j-bennet** [dbcli/pgcli#237]
Doesn't look so great when using a light theme in terminal right now.

I'm using Tango in GNOME terminal.
![pgcli-light](https://cloud.githubusercontent.com/assets/637013/7657998/58e21f2e-faeb-11e4-8e18-0906fc254b5e.png)

**Comment by amjith** [comment]
You probably saw the email on the pgcli mailing list, but there are plenty of themes to choose from. You just have to pick the right one from the config file.

Try deleting your config file ~/.pgclirc and restart pgcli. It'll create the latest config file and it has a ton of options to choose from.

**Comment by j-bennet** [comment]
Heh. I'm so behind. This works.
