### ISSUE TITLE
Is there a way to delay auto-completion popup?

### ISSUE THREAD

**Issue by xiaochuanyu** [dbcli/pgcli#256]
I find it a bit distracting when typing a SQL statement with the auto-completion popup flashing in and out when I don't need it yet. I think it would be nice to have a config option to add a delay before the popup after you stop typing. Alternatively, we can also make the auto-completion only popup when user presses a hotkey similar to how most IDEs work.

**Comment by amjith** [comment]
Hi @xiaochuanyu. In it's current form pgcli doesn't have the ability to turn off the auto pop-up. 

But it is possible to make the auto-completion popup only when you press `<tab>` or Ctrl-Space. I've added this feature in a branch for you to test it out. You can install directly from the branch using the following command: 

```
pip install -U -e "git+https://github.com/dbcli/pgcli.git@amjith/optional-auto-complete#egg=pgcli"
```

Once you install from that branch, open up your config file in ~/.pgclirc and add this line at the top of the file in the `[main]` section.

`always_on_autocompletion = False`

That should make the autocompletion only trigger when you press tab or ctrl-space. 

Let me know how it works for you.

**Comment by xiaochuanyu** [comment]
Hey @amjith, I tried out the branch, but I still think adding a delay would be ideal so I don't even have to press the hotkey to get auto-completion suggestions when I need them. I think this will be valuable to future users since a lot of times people tend to pause when typing out their queries when they are not sure about something and need auto-completion suggestions.
How difficult do you think it is right now to add this feature? I was thinking about taking a look at the code on the weekend and try to add it myself.

P.S. I really love this project. Thank you for creating something like this.

**Comment by amjith** [comment]
@xiaochuanyu I believe it is possible. You might want to look into [prompt_toolkit](https://github.com/jonathanslenders/python-prompt-toolkit) the library that powers the completion menu. 

Especially this file: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/filters/base.py

I'm currently changing the auto-completion behavior here in pgcli: https://github.com/dbcli/pgcli/blob/amjith/optional-auto-complete/pgcli/main.py#L237

The two options available are `Always` and `Never`, see if you can add something called `Delayed`. Although I'm not 100% sure if that's the approach to take, so take my suggestion with a grain of salt and let your imagination run wild. :)

**Comment by flipperbw** [comment]
What happened to this branch?

**Comment by j-bennet** [comment]
@flipperbw It may have been deleted after being inactive for a while. Timers are tricky though, just like @amjith and @jonathanslenders mentioned, hotkey-autocompletion (Tab or Ctrl+Space) may be a better bet.

**Comment by amjith** [comment]
This is not something we plan to pursue. Sorry to disappoint.
