### ISSUE TITLE
There is no autocompletion inside a named query.

### ISSUE THREAD

**Issue by j-bennet** [dbcli/pgcli#270]
When inside the named query, suggestions don't show up.

![named-query-no-autocomplete](https://cloud.githubusercontent.com/assets/637013/8294961/1df337e0-18f5-11e5-860e-5b47ae95dbe1.png)

Boo.

**Comment by amjith** [comment]
Yes I'm aware of that handicap. Thanks for filing an issue for it. :)

**Comment by amjith** [comment]
BTW, we also need a way to allow multi-line mode for this. Otherwise named queries are just a fancy gimmick. :P
