### ISSUE TITLE
Selecting JSONB throws error "unknown encoding: SQLASCII"

### ISSUE THREAD

**Issue by arsgeografica** [dbcli/pgcli#274]
I have a JSONB field in a PostgreSQL 9.4.4 database. Selecting it with pgcli 0.17.0 throws the error in the title. Using psql I get the JSON string representation for the field.

**Comment by amjith** [comment]
I'm unable to reproduce this issue. 

Here are a few things I've tried so far: 

```
postgres> select '1'::jsonb
╒═════════╕
│   jsonb │
╞═════════╡
│       1 │
╘═════════╛
SELECT 1
Command Time: 4.05311584473e-06
Format Time: 0.000195980072021
postgres> SELECT '{"foo": [true, "bar"], "tags": {"a": 1, "b": null}}'::jsonb
╒═════════════════════════════════════════════════════╕
│ jsonb                                               │
╞═════════════════════════════════════════════════════╡
│ {"foo": [true, "bar"], "tags": {"a": 1, "b": null}} │
╘═════════════════════════════════════════════════════╛
SELECT 1
Command Time: 8.10623168945e-06
```

Doing a bit of research shows that SQL_ASCII is an odd encoding style. http://www.postgresql.org/docs/9.0/static/multibyte.html

Do you have any pointers on why SQL_ASCII is used as encoding style for the database?

**Comment by amjith** [comment]
After a bit of research I found out that this is not related to JSONB but it has to do with the encoding of the database. I've fixed this in a branch and I was wondering if you could try it out and let me know if it works for you. 

You can install directly from a branch in github using the following command: 

```
pip install -e "git+https://github.com/dbcli/pgcli.git@amjith/force-utf8-encoding#egg=pgcli"
```

**Comment by arsgeografica** [comment]
Will do tonight. Thinking of it, this DB was created with an Ansible playbook, probably not specifying an encoding, causing it to have that weird encoding. Stupid me. :)

**Comment by arsgeografica** [comment]
This works! Although I'm not sure what exactly causes this. The DB is encoded UTF8...

**Comment by amjith** [comment]
If it's encoded UTF8 then pgcli will be using utf8 as the default encoding. 

Can you try `psql -l` to see the list of databases and their encodings?

That should tell you what postgres thinks the encoding is set for that DB.

**Comment by arsgeografica** [comment]
Looks ok:

   Name    |    Owner    | Encoding |   Collate   |    Ctype    |   Access privileges   
-----------|-------------|----------|-------------|-------------|-----------------------
 postgres  | postgres    | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 registry  | registry    | UTF8     | en_US.UTF-8 | en_US.UTF-8 |
