### ISSUE TITLE
support \h

### ISSUE THREAD

**Issue by keturn** [dbcli/pgcli#281]
or some other help key to show the syntax of a SQL command.

**Comment by amjith** [comment]
This is a valid request. Unfortunately I don't have an easy solution here. 

There is no way to get the documentation out of postgres programmatically. At least I haven't found a way to do it. 

So I'm open to ideas.

**Comment by stuartquin** [comment]
We could get pretty good results using the sgml from the open source psql client.
For example the `SELECT` command: https://github.com/postgres/postgres/blob/aa9eac45ea868e6ddabc4eb076d18be10ce84c6a/doc/src/sgml/ref/select.sgml#L34

We could parse the synopsis and description sections.

Happy to take a look at this if it seems like a good idea.

**Comment by amjith** [comment]
@stuartquin I'd love to see a solution for this. So if you have an idea I'm not going to stop you from exploring it. 

In fact, @j-bennet had a similar idea where, we can check if psql is installed on the system, if it is, then proxy all the `\h` calls to psql and read the output and display it into pgcli. Which is better than nothing, but I think there might be some challenges to get it right on all platforms. 

So please feel free to explore and see what you can come up with.

**Comment by amjith** [comment]
Fix released in 0.20.0. 

Please upgrade:

```
pip install -U pgcli
```
