### ISSUE TITLE
Explicit dependency on PostgreSQL in Homebrew

### ISSUE THREAD

**Issue by geordee** [dbcli/pgcli#284]
I already have PostgreSQL using Postgres.app

    ~ $ brew install pgcli
    ==> Installing pgcli dependency: postgresql
    ==> Downloading https://homebrew.bintray.com/bottles/postgresql-9.4.4.yosemite.b
    ^C
    ~ $

Can we avoid installing PG for pgcli?

**Comment by amjith** [comment]
You can install pgcli as follows:

    brew install --build-from-source pgcli

That will skip installing postgres from brew if postgres already exists in the system.

Sorry about the explicit dependency on postgres in brew. I couldn't find a different way to bring in the dependencies needed for psycopg2 to install in OS X. And there is no way for me to check if Postgres is already available on the system before declaring it as a dependency.

**Comment by geordee** [comment]
Thanks! It worked.

I wonder whether <code>pip install pgcli</code> is simpler.
