### ISSUE TITLE
Wrongly double quoting name of some databases in autocompletion

### ISSUE THREAD

**Issue by Umedoc** [dbcli/pgcli#285]
Running osx 10.10.3, pgapp version of postgres, installed pgcli using brew install --build-from-source pgcli
\l  produces a list of databases, the names of which are all shown without double quotes.
When I try and use \c to connect to a database, the list of databases shows some with double quotes and some without. The ones with double quotes fail 
umedoc_sql_practice> \c "depot-jrb_development"
FATAL:  database ""depot-jrb_development"" does not exist
.....
postgres> \c guestbook
You are now connected to database "guestbook" as user "foo"

It looks like the problem is names with hyphen (dash) characters . 
create database pgcli_test  (with underscore)
CREATE DATABASE

create database pgcli-test
syntax error at or near "-"
LINE 1: create database pgcli-test

create database "pgcli-test"  (with dash, but surrounded by double quotes)
CREATE DATABASE

psql also requires double quotes around a name containing a dash when creating a database, but once created, the new database can be connected to without using double quotes in the command

pgcli-test=# \c pgcli-test1
You are now connected to database "pgcli-test1" as user "foo".

**Comment by amjith** [comment]
Hi @Umedoc. Can you tell me which version of pgcli you're using? 

This bug is fixed in the latest version. Can you try upgrading?

You can upgrade using pip (pip install -U pgcli) or brew (brew upgrade pgcli). Depends on how you installed pgcli originally. 

Let me know if this is still a problem after the upgrade.

**Comment by Umedoc** [comment]
Sorry, just saw this, it was v0.17.0
