### ISSUE TITLE
Order keyword autocomplete by some form of frequency of use

### ISSUE THREAD

**Issue by MattOates** [dbcli/pgcli#287]
At the moment it looks like keywords are ordered alphabetically this is usually not what you want. Instead it might be good to order them by their frequency of appearance in actual SQL. For example WH gives WHEN and WHENEVER before WHERE. This could even be learnt as people use pgcli so its custom to their use case.

**Comment by amjith** [comment]
This would be a fantastic feature. :)

But it'll require some plumbing on the completion algorithm to get it right. So it might not be a quick addition, but I'll definitely take a stab.

Thank you!

**Comment by mknapik** [comment]
:+1:

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
