### ISSUE TITLE
support "service="

### ISSUE THREAD

**Issue by zakm** [dbcli/pgcli#289]
With psql, one can create a .pg_service.conf file with the following format:

```ini
[someservice]
host=the.host
user=the-user
dbname=the-db
```

and then run `psql service=someservice`. Support for this feature would be nice.

**Comment by amjith** [comment]
Reasonable request, I'll see if I can add that feature in. 

Can you tell me if `.pg_service.conf` is always on the home folder of the user or is there a common location like `/etc/postgres`?

**Comment by Dinoshauer** [comment]
Here's the docs for `.pg_service.conf` http://www.postgresql.org/docs/9.4/static/libpq-pgservice.html :)

**Comment by amjith** [comment]
Thank you for the doc. It seems simple enough, I'll give it a shot. Thank you!

**Comment by Dinoshauer** [comment]
Maybe you could even support `.pgpass` files! http://www.postgresql.org/docs/9.3/static/libpq-pgpass.html

Ofcourse, that is if you don't do so already :) I couldn't get the package to work on arch linux `pgcli-git` so I never got around to check

**Comment by amjith** [comment]
There is already support for pgpass. https://github.com/dbcli/pgcli/issues/53 I get it for free since it's a libpq feature. 

pg_service might need some tinkering to parse the file.

**Comment by Dinoshauer** [comment]
It's a regular ini file, python is quite good at that: https://docs.python.org/2/library/configparser.html

**Comment by amjith** [comment]
@Dinoshauer There might be an arch AUR package. Related: https://github.com/dbcli/pgcli/issues/168

/cc @svenstaro

**Comment by j-bennet** [comment]
This is now in master.
