### ISSUE TITLE
Emulate `jsonb_pretty`

### ISSUE THREAD

**Issue by ruimarinho** [dbcli/pgcli#293]
Would it be possible to implement `jsonb_pretty`-like functionality for pretty printing JSON(B) fields on postgres < 9.5?

**Comment by amjith** [comment]
Looks like jsonb_pretty() is a built in function to be introduced in Postgres 9.5. 

When that is introduced the output in pgcli will look quite crappy. It's because the library we use for tabulating the output can't handle multi-line text. 

But to get back to your real question. It is possible to emulate the jsonb_pretty by always prettyfying the results of json fiends, but before that we need to address the tabulation issue. 

So it's not an easy change.

**Comment by ruimarinho** [comment]
Thank you for the feedback. Please close at will since this is more of a feature request then.

**Comment by tsroten** [comment]
Just a note that tabulate does support multi-line text now (in its master branch, yet to be released).

**Comment by riyadparvez** [comment]
What's the status of this feature request? It'd be pretty helpful.

**Comment by j-bennet** [comment]
We'd be happy to accept a PR if someone submits one, but no volunteers so far.

**Comment by amjith** [comment]
This is now working. Please upgrade pgcli (`pip install -U pgcli`). 

```
SELECT jsonb_pretty(EmployeeDetails) AS EmployeeDetails FROM tbl_TestJSON;
+-----------------------------------+
| employeedetails                   |
|-----------------------------------|
| {                                 |
|     "employees": [                |
|         {                         |
|             "lastName": "Patel",  |
|             "firstName": "Anvesh" |
|         }                         |
|     ]                             |
| }                                 |
| {                                 |
|     "employees": [                |
|         {                         |
|             "lastName": "Shah",   |
|             "firstName": "Nancy"  |
|         }                         |
|     ]                             |
| }                                 |
+-----------------------------------+
SELECT 2
Time: 0.092s

```

**Comment by ahussain3** [comment]
It would be great if there was a config option to turn this on for all jsonb columns by default.

Similar to how `auto_expand = True` lets me mimic `\x auto`. I understand that the change won't be as simple since it will need to identify the jsonb columns in each query.

**Comment by alarbada** [comment]
> It would be great if there was a config option to turn this on for all jsonb columns by default.
> 
> Similar to how `auto_expand = True` lets me mimic `\x auto`. I understand that the change won't be as simple since it will need to identify the jsonb columns in each query.

Agree. It is very useful when debugging to just do a `select *`, but with jsonb columns the output always eating all the window width.
