### ISSUE TITLE
Measure test coverage

### ISSUE THREAD

**Issue by thedrow** [dbcli/pgcli#295]
Either coveralls or codecov is fine but test coverage should be measured.

**Comment by amjith** [comment]
I've tried a few times to add coverage but I'm always doing something wrong and it never works. 

If you can get the coverage working, I'll be happy to accept a PR.

**Comment by j-bennet** [comment]
I managed to get it working for dockercli with codecov and this config:

https://github.com/j-bennet/dockercli/blob/master/.travis.yml

Will try to add for pgcli.
