### ISSUE TITLE
Is there a way to modify popup menu colors?

### ISSUE THREAD

**Issue by stardiviner** [dbcli/pgcli#310]
RT

**Comment by amjith** [comment]
I don't know what you mean by RT. 

But to answer your question, right now there is no easy way to change it. We wanted to make sure the suggestions and the menu are visible in any background, so we decided to hard code it to a known value. 

Is there a specific reason why you want this changed?

**Comment by stardiviner** [comment]
Because the selected candidate background color is not very clear for me.
I usually use black background & white foreground for selected candidate, and white background & black foreground for candidates.

**Comment by amjith** [comment]
Can you take a screenshot with the completion menu showing and paste it here?

These are the lines that control the colors for the completion menu. 

https://github.com/dbcli/pgcli/blob/master/pgcli/pgstyle.py#L20-L21

It is possible to set those colors from a function argument, but I'm reluctant to add more config options unnecessarily. Reason: http://c2.com/cgi/wiki?ConfigurabilityIsTheRootOfAllEvil

But if you have a legitimate reason I'm open to changing that behavior.

**Comment by stardiviner** [comment]
![pgcli-popup-menu-screenshot](https://cloud.githubusercontent.com/assets/378699/9025517/619be5cc-393a-11e5-9a4b-d6663203682b.png)

**Comment by stardiviner** [comment]
@amjith Can you show me how to modify those colors from a function? I learned a little about Python before, but I forgot it now.

**Comment by amjith** [comment]
Here's one way to do it: 

https://gist.github.com/amjith/6825dc9693120db529e5#file-pgstyle-py-L20

You'll see that style_factory takes in two new arguments `completion_selected_color` and `completion_unselected_color` which are used to set the colors down below on Line 20 and 21. 

This needs to be called from the main.py file here: https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L255

Where you'll pass in two additional arguments for the colors as strings which are formatted like this: 
`bg:#ffffff #000000`

If you were to do this, then you'll have to maintain a separate fork of pgcli with your own customizations. I'm not convinced that this is a necessary config option.

**Comment by jonathanslenders** [comment]
People always like to play with colors.

The hardest part is that colors are actually defined using Pygments colorschemes, which are Python code, and pgcli uses plain text for configuration files.
A configuration section to override the defaults could look like this:
```
[colors]
Token.Menu.Completions.Meta = 'bg:#448888 #ffffff'
Token.Menu.Completions.ProgressButton = 'bg:#003333'
```
However, writing a parser to parse that (without using "eval") and turning it into a Pygments colorscheme could be a challenge.

**Comment by stardiviner** [comment]
Can I let pgcli accept executing extra command with option `-e` or `-c` like some shell command options, for example:
`python -c "print('hi')"`.
And combine it with something like "Python method overriding"?

**Comment by amjith** [comment]
@stardiviner I'll tell you what, I don't have the time to implement color customization for completion menu. But if you are really motivated to get this added, I'd highly encourage you to take a stab at implementing it. 

Define a section in pgclirc file called `colors` like how Jonathan described in the comment above. 

Then read that in as part of the main.py file here: https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L72

Pass that value into the style_factory call here: https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L257

Then use the gist I gave you at the beginning to see if you can build out the customizations. 

If you send it as a PR, I'll merge it in.

**Comment by stardiviner** [comment]
OK

**Comment by amjith** [comment]
Someone else requested this exact same feature in mycli (https://github.com/dbcli/mycli/issues/107). I'm going to reopen this issue and work on adding ways to customize the menu colors. 

Thanks for filing the ticket.

**Comment by amjith** [comment]
@stardiviner We just landed a new PR to master which allows customizations to the menu colors. You can try it out. Install directly from master as follows:

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

Then add these lines to your config file (~/.pgclirc):

```
[colors]
Token.Menu.Completions.Completion.Current = 'bg:#ffffff #000000'
Token.Menu.Completions.Completion = 'bg:#008888 #ffffff'
Token.Menu.Completions.Meta.Current = 'bg:#44aaaa #000000'
Token.Menu.Completions.Meta = 'bg:#448888 #ffffff'
Token.Menu.Completions.ProgressButton = 'bg:#003333'
Token.Menu.Completions.ProgressBar = 'bg:#00aaaa'
Token.SelectedText = '#ffffff bg:#6666aa'
Token.IncrementalSearchMatch = '#ffffff bg:#4444aa'
Token.IncrementalSearchMatch.Current = '#ffffff bg:#44aa44'
Token.Toolbar = 'bg:#222222 #aaaaaa'
Token.Toolbar.Off = 'bg:#222222 #888888'
Token.Toolbar.On = 'bg:#222222 #ffffff'
```

Then customize them to your hearts content. Let us know if you have any questions. 

I'll release this to PyPI in a few weeks.

**Comment by stardiviner** [comment]
This's great. Thanks. It works fine.

**Comment by mknecht** [comment]
@amjith stumbled over this since in the built-in solarized-dark theme of my gnome terminal, I see nothing:

 ![selection_306](https://cloud.githubusercontent.com/assets/77181/9752434/9d2ce648-56e2-11e5-9138-2c7e66647d99.png)

Any chance of this making it to pip?

Thanks for the project, it's one of those things that you wonder how you did without. :)

**Comment by mknecht** [comment]
Ah, ignore me, this works already! Just modified the wrong color. Thank you! :+1:
