### ISSUE TITLE
Does not respect \x auto

### ISSUE THREAD

**Issue by carymrobbins** [dbcli/pgcli#315]
Is there a way to get the `psql` behavior with `\x auto`?

**Comment by amjith** [comment]
Yes. This is a known issue. I think it is possible to detect the size of the terminal using prompt_toolkit library. 

So it is possible to add this feature. But I just haven't gotten around to doing it. I'll take this into consideration.

**Comment by Abscond63** [comment]
\x  is not good to use, as it should be working as xml on a page handler.


Extended mark-up language. For web publishing.  Some one is trying to get back at 'X' as extended an issue???

What next rotten apples.


Sharon L Doherty 

On Aug 3, 2015, at 09:32, Cary Robbins <notifications@github.com> wrote:

Is there a way to get the psql behavior with \x auto?

**Comment by stuartquin** [comment]
I think this issue is resolved and can be closed with the next release

**Comment by amjith** [comment]
Yes. @carymrobbins If you'd like to give it a shot now you can always install pgcli from master as follows: 

```
pip install https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by carymrobbins** [comment]
Looks good, thanks!
