### ISSUE TITLE
psycopg2.ProgrammingError: column el.typarray does not exist

### ISSUE THREAD

**Issue by lujianbo** [dbcli/pgcli#316]
in 
https://github.com/dbcli/pgcli/blob/master/pgcli/pgexecute.py  datatypes_query

will throw  psycopg2.ProgrammingError: column el.typarray does not exist

when el.typarray does not exist.

![screenshot from 2015-08-04 17-47-27](https://cloud.githubusercontent.com/assets/1668083/9058051/e72122b0-3ad0-11e5-8508-dda60242d794.png)

**Comment by darikg** [comment]
What version of PostgreSQL are you using?

**Comment by lujianbo** [comment]
@darikg  Postgresql 8.2.15(Greenplum Database 4.2.8.3)

**Comment by darikg** [comment]
Thanks. That query was written on postgresql 9.something so I guess it's not backwards compatible. I'll try to fix it.

**Comment by amjith** [comment]
@lujianbo Are you using a special version of pgcli? Because I don't think it will even open when you use Postgres versions less than 9.x.

**Comment by topraymond** [comment]
<code>psycopg2.ProgrammingError: column el.typarray does not exist
LINE 17: ...                   WHERE   el.oid = t.typelem AND el.typarra...</code>

@amjith  I got the same error,   I'm using the latest  version`0.19.0` of pgcli
 
btw: postgresql version is 8.x

**Comment by topraymond** [comment]
It works fine with PostgreSQL 9.4.1

**Comment by amjith** [comment]
Yeah Postgres 8.x was never a target for pgcli. It requires a lot of work to add support for older versions of postgres. There is an effort under way to try and add support for older versions. #18

**Comment by topraymond** [comment]
Oh, I see.  Thanks!

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
