### ISSUE TITLE
"\c" completes, but "\connect" doesn't.

### ISSUE THREAD

**Issue by jonathanslenders** [dbcli/pgcli#322]
"\connect" completes with "ACCESS", "ADD", "ALL", etc instead of the table names.

**Comment by amjith** [comment]
Looks like the ticket auto-closed when I merged the PR (Thanks @darikg). But the fix is available in master. 

You can install directly from master (I'm sure you already know this). 

```
pip install https://github.com/dbcli/pgcli/archive/master.zip
```
