### ISSUE TITLE
embed() entry point.

### ISSUE THREAD

**Issue by jonathanslenders** [dbcli/pgcli#330]
I'd like to see pgcli embedded in tools like `django_extensions`. (Just like `shell_plus`.)

What we need to do for that is have one simple entry point that takes all the database parameters as input. (The `main.cli` method with all the click arguments doesn't look like a good way to embed. You don't want to accidently use environment variables, or options that are passed to the main executable.)

Right now, one way to do it is by calling these three lines by hand:

``` python
pgcli = PGCli()
pgcli.connect(database, host, user, port)
pgcli.run()
```

**Comment by amjith** [comment]
Right now there is a django-extension to embed pgcli. https://github.com/ashchristopher/django-pgcli

I know that @darikg did a bunch of refactor to embed pgcli in ipython. All of that work is encapsulated in this well named file called magic.py. https://github.com/dbcli/pgcli/blob/master/pgcli/magic.py

So I'm not entirely sure how the embed() entry point will be used. Can you explain it a little bit?
