### ISSUE TITLE
Debian Packages

### ISSUE THREAD

**Issue by sammcj** [dbcli/pgcli#35]
Love the app, but I wouldn't like to be installing it from pip everywhere - It would be great if this could be packaged and available on an apt mirror somewhere.

This would:

* Make installs easier
* Make upgrades easier
* Ensure installations are properly logged
* Ensure clean uninstallations when required
* Reduce dependancies
* Allow for easy on-site mirroring / caching

FYI packagecloud.io is pretty good, supports different package formats and their free plan would easily suffice.

**Comment by amjith** [comment]
Yes. I agree with all of the points you've made. I have no experience in creating deb packages. But I'll read up on it and see if I can put together something. 

Thank you for the feedback.

**Comment by sammcj** [comment]
Hey @amjith thanks for that, again I love the project and want to use it but I really need packages before I can think about rolling it out.

Take a look at FPM, which can easily generate packages for any platform: https://github.com/jordansissel/fpm

**Comment by whiteinge** [comment]
Something like FPM would be a quick way to start. Creating .deb's the Right Way (TM) takes some serious dedication. ;-)

**Comment by zanchey** [comment]
There's an intent-to-package notification filed in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=794250

**Comment by amjith** [comment]
I saw that but I didn't know the process of debian. It'll be nice if it is released. :)
