### ISSUE TITLE
Indentation in output are stripped

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#351]
Explain plans have indentation to show the hierarchy of query plan. But tabulate is stripping the indentation.

**Comment by d33tah** [comment]
Any ideas on which piece of code is to blame? This is affecting me as well.

**Comment by amjith** [comment]
I suspect the indentation is removed somewhere in this file: https://github.com/dbcli/pgcli/blob/master/pgcli/packages/tabulate.py

But I haven't had the time to dig in yet. So if you have a possible fix, I'd most welcome it. :)

**Comment by d33tah** [comment]
I basically removed all `.strip()` in this file and got indentation working:

```

**Comment by d33tah** [comment]
I could have broken something in the process because I don't know the codebase, but a simple `explain` test works fine.

**Comment by darikg** [comment]
@d33tah would you be willing to submit a PR? That would make it easier for the rest of us to test your changes, and allow the automated testing to run as well. You can see guidelines [here](http://pgcli.com/develop) for cloning the git repo to your machine. The remaining steps would be to make a new branch, commit your changes, push them back to github, and then open a pull request.

**Comment by d33tah** [comment]
@darikg: Done.

**Comment by amjith** [comment]
Fix released in 0.20.0. 

Please upgrade:

```
pip install -U pgcli
```
