### ISSUE TITLE
Misc pg functions not showing on smart autocompletion

### ISSUE THREAD

**Issue by edcrypt** [dbcli/pgcli#353]
When typing things like `select pg_get_viewdef('viewname', true)` with Smart Completion turned on, pgcli will not try to complete the `pg_get_viewdef` function. It works with naive completion.

Other functions lacking on smart completion: http://www.postgresql.org/docs/7.4/static/functions-misc.html

**Comment by amjith** [comment]
@darikg Would you mind taking a look at this? 

I remember that we added logic to not show table names and view names that start with `pg_` until the user explicitly types `pg_`. But do you know if we did the same for functions?

**Comment by darikg** [comment]
Sorry I'm away from my computer for the next 5 days or so.  I glanced at the source and it looks like I never handled pg_ functions specifically my guess is this is a legit bug. I can fix it when I get back!

**Comment by edcrypt** [comment]
It's not just with functions started with pg_ -- current_database() for example won't show also.

**Comment by darikg** [comment]
Ok had a chance to look into this again. The pgexecutor functions query isn't returning any functions from the pg_catalog namespace. It'd be an easy fix, but here's the problem:

```
test> SELECT COUNT(DISTINCT p.proname)
      FROM pg_catalog.pg_proc p
      INNER JOIN pg_catalog.pg_namespace n
      ON n.oid = p.pronamespace
      WHERE n.nspname = 'pg_catalog'
      AND p.proname NOT ilike 'pg_%';
+---------+
|   count |
|---------|
|    1837 |
+---------+
SELECT 1
```

That is, there's 1837 functions in pg_catalog that don't start with `pg_`, would that be too much to throw into the completions menu?

**Comment by j-bennet** [comment]
Showing 1837 functions may not be very helpful. But once the user starts typing something, the list will decrease. I would try it and see if it's feasible in terms of performance. If yes, then I think it's better to show too much rather than nothing.

**Comment by darikg** [comment]
@j-bennet I think you're right
