### ISSUE TITLE
command \d don't work

### ISSUE THREAD

**Issue by martinjanda** [dbcli/pgcli#354]
If I write `\d events`, I will see:
```
column c.reloftype does not exist
LINE 5:                 CASE WHEN c.reloftype = 0 THEN ''
```

**Comment by amjith** [comment]
What version of postgres are you running? 

Can you tell me if `\d` is a table or a view?

**Comment by martinjanda** [comment]
Thank you for fast response.

Version of postgres is 8.4. `events` is table.

**Comment by amjith** [comment]
Pgcli only supports Postgres 9.x.

Adding support for older Postgres is not actively pursued.

**Comment by martinjanda** [comment]
OK. I understand. Thank you.
