### ISSUE TITLE
CONCURRENTLY keyword not in suggestion list

### ISSUE THREAD

**Issue by johshoff** [dbcli/pgcli#358]
When creating an index concurrently like so

    CREATE INDEX CONCURRENTLY ...

the word `CONCURRENTLY` gets syntax highlighting as expected, but is not in the drop-down list of suggested keywords.

I'd be happy to pair on this issue if you want :)

**Comment by amjith** [comment]
Yes adding a new keyword to the completion menu is trivial. Here's the list of keywords used for completion. https://github.com/dbcli/pgcli/blob/master/pgcli/pgcompleter.py#L19..L40

You're welcome to take a stab at it, if I don't see a PR, I'll try and tackle it tonight.

**Comment by johshoff** [comment]
Thanks. Expect to see a PR for this.
