### ISSUE TITLE
Read socket configuration information

### ISSUE THREAD

**Issue by scw** [dbcli/pgcli#37]
When connecting to a local database configured with a local socket, `pgcli` fails:

```
pgcli -U postgres data_entry

    could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

The equivalent call to `psql` succeeds:

```
psql -U postgres data_entry
psql (8.4.22)
Type "help" for help.

data_entry#
```

Running `strace` against `psql` shows that it reads the socket configuration directory from the `unix_socket_directory` of the postgresql.conf file. I can get `pgcli` to run by specifying `-h /tmp` which is the socket location on this distribution (Ubuntu 12.04.5), perhaps because this Postgres release is backported. The psql code executes [this search](https://github.com/jbq/postgresql-common/blob/master/PgCommon.pm#L354-381) to find the appropriate path.

Some defaults for sockets on various distributions and OSes:
- "/var/run/postgresql" # Debian default
- "/var/pgsql_socket" # MacOS default
- "/usr/local/var/postgres" # FreeBSD default; custom installation
- "/tmp" # custom installation

May be worth just iterating over these for an appropriate socket directory before failing with a blank 'host' parameter.

**Comment by amjith** [comment]
Awesome bug report! :)

When I fall back to empty string for host, I'm relying to `psycopg2` to do the right thing. But I'll see if I can iterate over the common locations to find the socket before doing that.

**Comment by SpotlightKid** [comment]
On a related note, if you specify a port with the `-p` command-line option, but no host with the `-h` option, `pgcli` still tries to use a unix domain socket. Maybe it should assume an inet socket and `localhost` as the default hostname in that case, since specifying a port doesn't make sense with unix domain sockets.

**Comment by amjith** [comment]
Good point. Added #229

**Comment by demidovakatya** [comment]
Hey there, I have the same error (os x, `pgcli` v.1.5.1, installed via brew, `postgresql` v.9.6.2)
```
pgcli
	could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
```

**Comment by demidovakatya** [comment]
upd.: [this](http://dba.stackexchange.com/questions/21587/postgresql-is-running-locally-but-i-cannot-connect-why) helped

```
sudo mkdir /var/pgsql_socket
sudo chown -R whoami /var/pgsql_socket
cat "unix_socket_directory = /var/pgsql_socket" > /usr/local/var/postgres/postgresql.conf
/usr/local/bin/pg_ctl init -D DB_DIRECTORY

Success. You can now start the database server using:

    /usr/local/Cellar/postgresql/9.6.2/bin/pg_ctl -D DB_DIRECTORY -l logfile start
```

**Comment by bersace** [comment]
@j-bennet @amjith should we close this too then ?

**Comment by amjith** [comment]
Recent changes in psycopg2 and libpq seem to do the right thing. No additional work required on pgcli.
