### ISSUE TITLE
[BUG] Pasting doesn't work in some cases

### ISSUE THREAD

**Issue by disconnect3d** [dbcli/pgcli#389]
I've got a function written in such syntax:

```
CREATE OR REPLACE FUNCTION testfunction() RETURNS VOID AS
$$
BEGIN

END
$$ LANGUAGE 'plpgsql';
```

Whenever I paste it into `psql` it works:
```
psql (9.2.4, server 9.4.4)
WARNING: psql version 9.2, server version 9.4.
         Some psql features might not work.
Type "help" for help.

postgres=# CREATE OR REPLACE FUNCTION testfunction() RETURNS VOID AS
postgres-# $$
postgres$# BEGIN
postgres$# 
postgres$# END
postgres$# $$ LANGUAGE 'plpgsql';
CREATE FUNCTION
postgres=# 
```

But in `pgcli` it doesn't:

```
postgres> CREATE OR REPLACE FUNCTION testfunction() RETURNS VOID AS$$BEGINEND$$ LANGUAGE 'plpgsql';
syntax error at or near "AS$$BEGINEND$$"
LINE 1: ...E OR REPLACE FUNCTION testfunction() RETURNS VOID AS$$BEGINE...
                                                             ^
Command Time: 0.000s
Format Time: 0.000s
```

**Comment by amjith** [comment]
@disconnect3d What you're pasting is a multi-line query. pgcli by default is not in multi-line mode. You can switch to multi-line mode using `F3` key or you can set it permanently by editing your config file ~/.pgclirc to set `multi_line = True`. 

After you enable the multi-line mode you can paste the function without problem.

**Comment by disconnect3d** [comment]
Good to know, thanks!

Could we warn users who paste something with a lot of newline characters, that there is such option?

**Comment by amjith** [comment]
If you have thoughts on how to warn users, I'm all ears. Originally when I started pgcli, it was designed as an exploratory tool for running quick commands by hand. Then slowly it grew as a drop in replacement for psql. So I had made a choice to make multi-line mode disabled by default.

I can always enable the multi-line mode in the future releases, so it matches psql's behavior more closely. 

/cc @dbcli/pgcli-core I'd like your thoughts on this please.

**Comment by darikg** [comment]
Is it possible to automatically detect newlines, switch to multiline mode, paste, then switch back to single line mode? 90% of the time the user is going to press enter immediately anyway so it seems like this would be pretty convenient

**Comment by amjith** [comment]
I don't know of a good way to detect when a user is pasting vs typing. I believe that as far as prompt_toolkit is concerned, you're entering one character at a time whether it is being pasted or typed in. So differentiating the enter key would be difficult (if not impossible). 

/cc @jonathanslenders Can you think of a way to auto-detect when a user is pasting?

**Comment by jonathanslenders** [comment]
No, we can't detect that. When you paste in the terminal, using for instance command+V or Ctrl+Shift+V, the terminal application sends whatever is on the clipboard to the stdin of the application. That is exactly the same as what it does when the user types on the keyboard.

We could of course measure the speed at which characters come in. Nobody is able to type 100 characters in a fraction of a second, but I don't like this kind of guess work. There is a reason why Vi has a paste mode.

A few months back, I have been working on system clipboard integration. That is possible, but I never did extensive testing. Try this: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/examples/system-clipboard-integration.py
Personally, I think not enough users know the Emacs or Vi shortcuts for copy/pasting at the command line for doing this.

Jonathan

**Comment by disconnect3d** [comment]
Ok, another case - pasting in multiline mode changes the indentation - which breaks compilation whenever the function is written in PLPythonU:

The function:
```
CREATE OR REPLACE FUNCTION aaa() RETURNS VOID AS
$$
    y = 1
    x = [
        1, 2, 3
    ]
$$ LANGUAGE 'plpythonu';
```

pgcli:
```
postgres> CREATE OR REPLACE FUNCTION aaa() RETURNS VOID AS
          $$
              y = 1
                  x = [
                          1, 2, 3
                              ]
                              $$ LANGUAGE 'plpythonu';
could not compile PL/Python function "aaa"
DETAIL:  IndentationError: unexpected indent (<string>, line 4)

postgres> 
```

psql:
```
psql (9.2.4, server 9.4.4)
WARNING: psql version 9.2, server version 9.4.
         Some psql features might not work.
Type "help" for help.

postgres=# CREATE OR REPLACE FUNCTION aaa() RETURNS VOID AS
postgres-# $$
postgres$#     y = 1
postgres$#     x = [
postgres$#         1, 2, 3
postgres$#     ]
postgres$# $$ LANGUAGE 'plpythonu';
CREATE FUNCTION
postgres=# 
```

**Comment by jonathanslenders** [comment]
Have a look at this key binding: https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/key_binding/bindings/basic.py#L163

Pressing enter will copy the margin from the previous line, unless paste mode is on. (https://github.com/jonathanslenders/python-prompt-toolkit/blob/master/prompt_toolkit/application.py#L86)

You may either want to add a paste mode shortcut like ptpython, or override this key binding.
Probably I should give a "Buffer" class an auto_indent option as well. (What is the Vi name for this?)

**Comment by amjith** [comment]
Thanks for the tip @jonathanslenders. I think I want to convert the keybinding to not copy the previous margin but always add a constant margin. That way people realize it's still part of the previous command but not keep inserting the space.

**Comment by disconnect3d** [comment]
Hello, me again.

Once @jonathanslenders wrote that you can't detect whenever user is pasting something.
I heard today, that this is what Neovim does whenever you paste something (it detects it, sets paste mode and paste the clipboard) and that this feature is done thanks to "bracketed paste mode":
* http://cirw.in/blog/bracketed-paste
* https://github.com/neovim/neovim/issues/937
* http://www.xfree86.org/current/ctlseqs.html#Bracketed%20Paste%20Mode

As stated on the last url, to enable it, you have to send special sequence to the terminal to enable this mode:

```
P s = 2 0 0 4 → Set bracketed paste mode.
```

**Comment by jonathanslenders** [comment]
@disconnect3d,

Wow! Thanks a lot for this! I was totally unaware of bracketed paste mode. It should be easy to implement.

**Comment by mrzechonek** [comment]
To spare you fiddling, control sequences are `sys.stdout.write('\x1b[?2004h')` for enablind and `sys.stdout.write('\x1b[?2004l')` for disabling.

**Comment by jonathanslenders** [comment]
@disconnect3d @mrzechonek @amjith: Thanks everyone: prompt-toolkit has now support for bracketed paste.

See this commit:
https://github.com/jonathanslenders/python-prompt-toolkit/commit/623648bad28de69cf90f833203bd6d0449afcc79

Pasting of big chunks is now about 10x or more faster and indentation is not destroyed anymore.

**Comment by mrzechonek** [comment]
:heart:

**Comment by oblitum** [comment]
It seems this bracketed paste mode usage isn't working when [pasting from tmux through vim-slime](https://github.com/jpalardy/vim-slime/issues/169#issuecomment-463067983).
