### ISSUE TITLE
Detect connections from pgadmin

### ISSUE THREAD

**Issue by dbkaplun** [dbcli/pgcli#403]

**Comment by amjith** [comment]
Can you elaborate? I don't know what this means.

**Comment by dbkaplun** [comment]
@amjith I have connections in pgadmin3 set up already that I would like to be able to use from pgcli without additional work. Would be great if this was possible!

**Comment by j-bennet** [comment]
Relevant link:

http://stackoverflow.com/questions/3464396/pgadmin-sharing-db-connection-definitions

**Comment by amjith** [comment]
@j-bennet Thanks for the link to SO, it helped me get some background.

@dbkaplun Can you add some links to the documentation or some examples of the .pgadmin3 file? 

I don't use pgadmin. Looking at their site (http://www.pgadmin.org/) I see that it's a GUI tool. But I don't understand how connections are setup or how to reuse the said connections. 

I'm less inclined to install pgadmin and try to go through the initial setup just to get the format of .pgadmin3 file. So if you can provide some help, I'd appreciate it.

**Comment by j-bennet** [comment]
I looked at my .pgadmin3 file. It's an .ini-formatted file and looks like it doesn't have password information.

The file that has this info:
http://dave.webdev.pgadmin.org/docs/1.6/pg/libpq-pgpass.html

We could parse users and passwords out of that, keyed on host/port combo, and use them when user is connecting to host:port that are present in this file, if he left user and password empty.

Is that what you would like @dbkaplun?

**Comment by dbkaplun** [comment]
That sounds about right. Good stuff @j-bennet!

**Comment by darikg** [comment]
psycopg2 should already be checking .pgpass for us so it should already work, c.f. #53 #292

**Comment by j-bennet** [comment]
You're right @darikg. It's just that the current behaviour may not be quite what the user would expect.

For example, I have user "user1" with password "pass1" configured in my .pgpass for localhost. My Ubuntu user is named "iryna". When I run `pgcli` or `pgcli -h localhost`, I expect to connect as "user1" with password already there, but instead it asks for password for "iryna". Which is actually the same behavior as psql, but it does not seem correct.

**Comment by darikg** [comment]
Got it. That does sound more convenient

**Comment by darikg** [comment]
What if there's multiple user/pass combinations for a given host in pgpass? Take the first one?

**Comment by j-bennet** [comment]
Either the first one or the last one?

I'm wondering if this is a bug in psycopg2 though.

I tried to put in `.pgpass` file a username that is the same as my Ubuntu user, and this way it works. However, I don't see why it would not with a different user. The behavior does not seem logical. We can handle it ourselves but it may be better to submit a bug.

**Comment by darikg** [comment]
I think pgcli defaults to your own username if none is supplied, which is also what psql does.

**Comment by j-bennet** [comment]
Yes, it does. Also found one more case: if I run `psql -U user1`, then it uses password from pgpass. But if I run `pgcli -U user1`, it still asks for password. That looks like our bug (or psycopg2 bug, since we are not handling it ourselves).

The whole behavior though, do we want to stick to what psql does? Or do we want to improve it?
