### ISSUE TITLE
completion for count and explain functions

### ISSUE THREAD

**Issue by lookforit** [dbcli/pgcli#415]
I noticed that these 2 functions are not listed by `pgcli`.
How to add it by users?

**Comment by amjith** [comment]
Yes `EXPLAIN` is not yet added to the list. We're in the process of refactoring how we supply these keywords. 

You can add it to this file and send a PR: https://github.com/dbcli/pgcli/blob/master/pgcli/packages/pgliterals/pgliterals.json

**Comment by lookforit** [comment]
Thanks.
Looking forward these completions be included in next release.

**Comment by amjith** [comment]
@lookforit I've added the EXPLAIN keyword in PR #420, but what do you mean by `COUNT` because it is already listed as a suggestion.

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/420.
