### ISSUE TITLE
Humanize numbers?

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#431]
```
db> select count(distinct x) from tbl;


+-----------+
|     count |
|-----------|
| 634823020 |
+-----------+
SELECT 1
Time: 27823.563s (7 hours)
```

It would be nice to take a look at the number and be able to say whether we're talking millions or billions here. How could I add special formatting for numbers?

**Comment by amjith** [comment]
The code is here: https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L346

You can probably use a variant of 

```
print ('{:,}').format(query.total_time) 
```

to achieve what you want. Although I'm not sure if it is compatible with Python 2.6. 

But you're welcome to send me a PR.

**Comment by j-bennet** [comment]
I think @d33tah might have meant numeric data in his query, not time elapsed. Was that `count` field or timer you were talking about, @d33tah?

**Comment by amjith** [comment]
You're right. My bad. 

That's part of the tabulate function. https://github.com/dbcli/pgcli/blob/master/pgcli/packages/tabulate.py

But it's hard to determine when to use the commas and when not to use them. For example, it makes perfect sense to use them dollar values or other means of measure, but it'll be intrusive to use them for the `id` field.

**Comment by j-bennet** [comment]
Yeah... In this case, it's a calculated field (`count()`), and for those, we don't even know the type.

**Comment by d33tah** [comment]
@j-bennet , @amjith: yes - `count` is what I meant. You say that pgcli can't know its type? Would a hack of trying to cast it to int work then?

**Comment by darikg** [comment]
pgexecute has access to field types through the psycopg2 cursor -- should be able to check each column's OID and do whatever you want with its value. Or I think it's possible to override the default psycopg2 int adapters to supply your own adapter? Still no way to distinguish ID columns though.

**Comment by foxyterkel** [comment]
Hello. I wanna take part in issue solving. I'm watching code, and found place where int, float, and str value are formatting. Value formatting in agree with column type. So can we suggest that all int, and float values must be comma divided? As for me ID values is not a problem, UUID value is usually placed in str columns. If id will be in int column(like auto increasing), so id is not random value but serial number, in this case comma divided value not a problem.

**Comment by amjith** [comment]
@foxyterkel I'd love to see a PR with the idea you've described. One of the problems is we don't have a prototype to play around with different ideas, but once someone puts forth a PR, we can try to collaborate on it and make it better.

**Comment by kosciej16** [comment]
@amjith There is a problem with ids now, I can't just copy id and paste it to another query. Is there a clear way to disable 'humanize numbers' feature? I found that change **dcmlfmt** to empy string in **tabulate.py** works, but i guess there should be better way to achieve this.

**Comment by foxyterkel** [comment]
@kosciej16 in main directory of the project there is pgclirc file where you can define default dcmlfmt.

**Comment by amjith** [comment]
@kosciej16 As mentioned by @foxyterkel you can set the format in your config file. The config file is usually located in your `~/.config/pgcli/config`. 

If you don't have the following lines add them in and set the format to empty string:

https://github.com/dbcli/pgcli/blob/master/pgcli/pgclirc#L134
