### ISSUE TITLE
Copy-paste mode?

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#432]
I noticed that copy-pasting long, preformatted queries adds indentation that makes it less readable. Perhaps it would be useful to have some copy-paste detection similar to what Irssi or Weechat does that:

1. Detects multiple lines entered at a quick burst,
2. Asks the user for confirmation on whether he actually meant to paste,
3. Disables indentation for input lines.

What do you think about that?

**Comment by amjith** [comment]
There is a solution for this in prompt-toolkit. https://github.com/dbcli/pgcli/issues/389#issuecomment-157805320

I think we should investigate the path to upgrading to the latest prompt-toolkit. /cc @jonathanslenders

**Comment by jonathanslenders** [comment]
Yes, it is indeed implemented in the latest prompt-toolkit, but I haven't done any release yet after these changes. I plan to do at least one new release before new year. (With many improvements.)

**Comment by jonathanslenders** [comment]
So, now that the latest prompt_toolkit (0.57) supports bracketed paste, we should upgrade to that version. Ping me, if the upgrade is not trivial.

**Comment by amjith** [comment]
There is a pending PR for mycli to do the upgrade to 0.56 (https://github.com/dbcli/mycli/pull/214). I'm working on updating it to 0.57. Once that is tested and merged, I'll do the same for pgcli.

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```

**Comment by saml** [comment]
How can I copy a long wrapped query from pgcli so that I can paste it to other program (such as text editor)?

**Comment by jonathanslenders** [comment]
Hi @saml,

The easiest is to open a text editor from the REPL itself. In Emacs mode, I think you have to press the C-X C-E sequence in Emacs mode and in Vi mode, it's the 'v' key in navigation mode. (This requires the "open_in_editor" prompt_toolkit option to be enabled, I didn't check whether that's the case for pgcli.)

I know that right now, even if there is a soft wrap, that the copy paste will insert a line ending at that place. @asmeurer noticed this as well. See this issue: https://github.com/jonathanslenders/python-prompt-toolkit/issues/493 In practice, this is something which is hard to solve, if it can be solved at all, without breaking other stuff. I believe GNU Readline doesn't have this issue, but it doesn't support the more complex UI layouts that we have.

Another option would be to bind a custom shortcut in pgcli and use the pyperclip package to copy text to the system clipboard. (Or implement a special postgres magic like `\copy` to copy things to the clipboard.) This has also the advantage that it also works in tmux.

**Comment by saml** [comment]
Wow `C-x C-e` opened nano. Thank you @jonathanslenders

**Comment by jonathanslenders** [comment]
If you prefer another editor, it can be configured by setting the ``$EDITOR`` environment variable.

**Comment by j-bennet** [comment]
@saml Editor can also be opened with a special `pgcli` command: `\e`.

this will open editor with previous query in it:
```
> \e
```

this will open editor with current query in it:
```
select * from test \e
```

**Comment by saml** [comment]
Nice. thanks. 

- `C-x C-e`, edit, save and quit: immediately executes the query.
    - It copies current content in prompt to editor. If prompt was empty, editor is empty.
- `\e`, edit, save and quit: it updates prompt but does not hit enter.

**Comment by asmeurer** [comment]
By the way if you don't want `C-x C-e` (or `v`) to execute the prompt after saving, you can add a custom keybinding

```py
@r.add_binding(Keys.ControlX, Keys.ControlE)
def open_in_editor(event):
    event.current_buffer.open_in_editor(event.cli)
```

where `r` is the keybinding registry (`KeyBindings()` object in 2.0).

**Comment by asmeurer** [comment]
And to the original question, here is a keybinding that will copy the selected text on OS X (it can easily be extended to Linux, and probably Windows too)

```py

def osx_copy(text):
    try:
        # In Python 3.6 we can do this:
        # run('pbcopy', input=text, encoding='utf-8', check=True)
        subprocess.run('pbcopy', input=text.encode('utf-8'), check=True)
    except FileNotFoundError:
        print("Error: could not find pbcopy", file=sys.stderr)
    except subprocess.CalledProcessError as e:
        print("pbcopy error:", e, file=sys.stderr)

@r.add_binding(Keys.ControlX, Keys.ControlW)
def copy_to_clipboard(event):
    if event.current_buffer.document.selection:
        from_, to = event.current_buffer.document.selection_range()
        run_in_terminal(lambda:osx_copy(event.current_buffer.document.text[from_:to + 1]))
```
