### ISSUE TITLE
Editor command not retaining last query

### ISSUE THREAD

**Issue by rdlugosz** [dbcli/pgcli#434]
When I enter `\e` my default editor (Vim) opens with an empty buffer. I can enter my SQL into the editor, save/quit and the query appears on the pgcli command line as expected. However, after executing the query and typing `\e` again I'm presented with an empty Vim.

The `\e` command works as expected in `psql`–the last query is shown in Vim.

My pgcli reports version `0.20.1`

**Comment by amjith** [comment]
Yes. This is a valid request. But it requires patching prompt-toolkit to
give us a way to access previous item from the history. But it is doable.
Thanks for the request.

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/710.
