### ISSUE TITLE
\i: run() got an unexpected keyword argument 'on_error'

### ISSUE THREAD

**Issue by dcere** [dbcli/pgcli#443]
Hi,

I was testing a query using the \i option and I got this error. Using psql's \i option work as expected, so I guess this is an error somewhere in pgcli's code. Steps to reproduce:

## Create test database
```
_$: createdb -O myuser testdb
_$: psql -U myuser testdb
testdb=> CREATE table employee
testdb-> (
testdb(>   name character varying(32);
testdb(> );
```

## Insert test data
```
testdb=> INSERT INTO employee VALUES('John Doe');
```

## Create query file
```
_$: echo "SELECT count(*) FROM employee;" > /tmp/test.sql
```

## Test with psql
```
testdb=> \i /tmp/test.sql
 count 
-------
     1
(1 row)
```

## Test with pgcli
```
pgcli --host dbserver --user myuser --dbname testdb
Password: 
Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
testdb> \i /tmp/test.sql
run() got an unexpected keyword argument 'on_error'
testdb> \q
Goodbye!
```

I've taken a (very) quick look at the code base and I think it fails because of the difference between [this line](https://github.com/dbcli/pgcli/blob/master/pgcli/pgexecute.py#L229) and [this other line] (https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L160) but maybe you can take a more detailed look at this.

Thank you.

**Comment by amjith** [comment]
Thanks for filing the issue. I'll take a look.

**Comment by Kareeeeem** [comment]
I'm still getting this issue. Installed pgcli from pypi. Saw that it is an old version from last year. Should I clone from github to get the fix?

**Comment by amjith** [comment]
This is now fixed in master. I haven't released it to pypi. 

You can install directly from master as follows: 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```
