### ISSUE TITLE
Can't describe foreign table

### ISSUE THREAD

**Issue by fpietka** [dbcli/pgcli#447]
This happens when I'm using a foreign data wrapper and try to describe a table:
```
global name 'ftoptions' is not defined
```

In my case I use a FDW to access MySQL tables, but it may also fail on Postgres tables using FDW.

**Comment by amjith** [comment]
I'm new to FDW, I'm still reading up on it. Can you give me a reproducible case?

**Comment by darikg** [comment]
Looks to me like [this line](https://github.com/dbcli/pgspecial/blob/3bb90bc3ffce885849b1ecfa1bbe8564be43313a/pgspecial/dbcommands.py#L888) should just have `ftoptions` replaced with `row[1]` but I don't have a foreign table to test it on.

**Comment by fpietka** [comment]
:+1: I tested @darikg suggestion with success. Opening an issue on dbcli/pgspecial
