### ISSUE TITLE
Group by which has more than 1000 rows returning Question mark 

### ISSUE THREAD

**Issue by PaviJas** [dbcli/pgcli#455]
For the query select count(*) from table_name group by column which returns more than 1000 rows is returning only question mark like as follow 

`???????+??4????????+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???+++???`

**Comment by darikg** [comment]
Are you on windows by any chance?

**Comment by PaviJas** [comment]
Yes I am using windows. Is it a known issue?

**Comment by darikg** [comment]
Yeah, for some reason the windows default pager (more.exe) mis-identifies the pretty printed table symbols as being unicode. Do you have any other pagers installed on your computer? I have less.exe which I think came with Git for Windows. I set the environmental variable `PAGER` to `less` and then that fixed the issue.

**Comment by amjith** [comment]
@PaviJas Did you try changing your default pager to `less.exe`?

If that didn't fix the issue, please reopen the ticket.
