### ISSUE TITLE
pgcli syntax highlighting does not understand double quote

### ISSUE THREAD

**Issue by morenoh149** [dbcli/pgcli#460]
reading http://philip.greenspun.com/sql/introduction.html
and inputting `insert into mailing_list (name, email)
values ('Michael O''Grady','ogrady@fastbuck.com');` pgcli's syntax highlighting doesn't understand the double quote rule.

**Comment by amjith** [comment]
You're right that it doesn't auto-escape two single quotes adjacent to each other while syntax highlighting, but functionally it does the right thing, which is to insert the value with the single quote. I can understand how that can send the wrong signal to someone learning SQL and typing in the command. 

This will require an exception in the Pygments module. Would you mind filing an issue with [pygments](https://bitbucket.org/birkenfeld/pygments-main).

**Comment by morenoh149** [comment]
https://bitbucket.org/birkenfeld/pygments-main/issues/1209/sql-double-quote-does-not-get-highlighted

**Comment by birkenfeld** [comment]
Which lexer are you using? I checked with the SQL lexer and the specialized PostgresSQL lexer, and both seem to highlight the given snippet just fine.

**Comment by amjith** [comment]
@birkenfeld I'm using PostgresLexer. https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L34

This is what I see when I do the double quote. You'll see that after I type `'Michael O''Grad` it highlights Michael in red which denotes it's a string and then `Grad` is all gray denoting unfinished quote. 

![double-quote](https://cloud.githubusercontent.com/assets/49260/12877511/44cf82cc-cdc9-11e5-8065-870be9466dde.gif)

**Comment by birkenfeld** [comment]
Ah, I see. This is because Pygments usually caters only for complete code highlighting. So a string is only recognized once it has a beginning and end quote.

In this case, it is easy to fixup the behavior though; using a separate state for strings is possible. I implemented that in https://bitbucket.org/birkenfeld/pygments-main/commits/4f26309906cdacdcedd092ea16f9e5b11e874755 and it will be released with 2.1.1.

**Comment by amjith** [comment]
Thank you for fixing it. I'll bump up the version in the next release. Cheers!
