### ISSUE TITLE
\i <filename> + tab fails to autocomplete filenames

### ISSUE THREAD

**Issue by mikebissell** [dbcli/pgcli#467]
When I import a SQL file using the \i command, I expect the tab key to autocomplete filenames for me, however pgcli doesn't know how to do this (PostgreSQL 9.3.3, Python 2.7.10, OS X 10.10.5).

Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
pgdbdev> \i foo

I hit tab after typing the prefix "foo", so pgcli should have autocompleted "foobar.sql", since the file foobar.sql exists in the working directory. Instead, nothing happened -- no autocompletion. Absolute and relative paths to files outside the working directory should work, too, but they don't. For reference, this autocompletion feature works well in the old psql CLI.

**Comment by amjith** [comment]
Yes. We have this planned but haven't gotten around to it.

**Comment by ajlai** [comment]
@amjith I'd be interested in taking a stab at this one if someone isn't already doing it.

**Comment by amjith** [comment]
Be my guest. :smile:

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
