### ISSUE TITLE
The 'set' command fails to autocomplete the 'schema' subcommand (or any other).

### ISSUE THREAD

**Issue by mikebissell** [dbcli/pgcli#468]
Expected: when I type the command prefix 'set s', I get a drop-down menu for autocompleting all of the commands beginning with 's', especially 'set schema'.

Observed: tab key does nothing after typing 'set s'. No drop-down menu.

Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
pgdbdev> set s

**Comment by amjith** [comment]
Valid issue.
