### ISSUE TITLE
'set schema' autocomplete generates a syntax error because it omits single quotes.

### ISSUE THREAD

**Issue by mikebissell** [dbcli/pgcli#469]
If I type the command prefix "set schema ", a list drops down containing a list of all my schemas for autocompletion. However, if I select a schema, the command is then completed without the required single quote marks around the schema name, and so it fails.

Moreover, if I type the correct command prefix "set schema '" (same as above, except that I provide a single quote mark as a hint), I get no autocompletion options at all.

Observe, please:

Version: 0.20.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
pgdbdev> set schema thumper
syntax error at or near "thumper"
LINE 1: set schema thumper
                   ^

pgdbdev> set schema '
unterminated quoted string at or near "'"
LINE 1: set schema '
                   ^

pgdbdev> set schema 'thumper'
SET

The very last example succeeded only because I hand-keyed it.

**Comment by amjith** [comment]
You're right this is an issue. We'll address it.
