### ISSUE TITLE
How to actually use vi-mode

### ISSUE THREAD

**Issue by esn89** [dbcli/pgcli#474]
I have enabled it with the F4 key, but how do I stop "inserting" and start using the vi keys?

**Comment by amjith** [comment]
You can press 'esc' key to go to normal mode which allows you to use the vi keys.

**Comment by JikkuJose** [comment]
Thats not working for me! Pressing escape key doesn't do anything, I am on Mac (10.14.5) in iTerm with tmux.

**Comment by Mange** [comment]
Same here. It used to work a few weeks ago, but not anymore.
