### ISSUE TITLE
Suggestions after the FROM keyword are jumbled

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#475]
<img width="759" alt="1__1_0_python2_7_-__pgcli___users_amjith_dropbox_code_python_pgcli____tmux_" src="https://cloud.githubusercontent.com/assets/49260/13720553/2dadeb8a-e7c1-11e5-8455-fd6c9d8fa091.png">

The list of items suggested after the `FROM` keyword are not in any specific order. The list has alternating table names and function names. 

@darikg Any thoughts that jump out?  

 @drocco007 I remember you made a change to the fuzzy completion recently, is this behavior expected?

**Comment by darikg** [comment]
Wow that's weird. If you delete your history file, does the effect persist?

**Comment by amjith** [comment]
I deleted the history and started pgcli. Here's a screenshot. 

![1__1_0_python2_7_-__pgcli___users_amjith_dropbox_code_python_pgcli____tmux_](https://cloud.githubusercontent.com/assets/49260/13726589/f1436224-e883-11e5-9060-3dbfb8806712.png)

**Comment by drocco007** [comment]
Interesting. I'll have a look over the PR later today :)
