### ISSUE TITLE
\i filename

### ISSUE THREAD

**Issue by xinxingzhao** [dbcli/pgcli#484]
I execute command 

`
pgcli database
`
`
 \i filename
`

nothing output 

then I exeute command

`
psql database
`
`
\i filename
`

I like something output then I know pgcli is working!

**Comment by amjith** [comment]
I don't fully understand this issues. Can you please tell me what version of pgcli you're using? 

The \i command was added in pgcli 0.19.0. So if you have an older version please try upgrading using `pip install -U pgcli`. 

If you're using a newer version and you're still having difficulty with this, please paste the output of your logfile. The log file is usually located in ~/.pgcli.log or ~/.config/pgcli/log.

**Comment by xinxingzhao** [comment]
use pgcli

![selection_008](https://cloud.githubusercontent.com/assets/13712791/14417622/203cd484-ffea-11e5-9def-9659a4c3d24d.png)

use psql

![selection_009](https://cloud.githubusercontent.com/assets/13712791/14417652/63ada144-ffea-11e5-8910-c6f2a057eeee.png)

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
