### ISSUE TITLE
How can I change text color in query

### ISSUE THREAD

**Issue by tienhm0202** [dbcli/pgcli#493]
![screenshot from 2016-05-11 11-15-23](https://cloud.githubusercontent.com/assets/13783097/15169912/c46da910-176a-11e6-95d6-1e31df3b4afb.png)
 How can I change this red text to another color. It look so dark and so `error-like`

**Comment by amjith** [comment]
There are many syntax color schemes available. Open up your config file (~/.config/pgcli/config) and look for `syntax`. The comment above that should have a list of all possible color schemes. 

If you're using an older version of pgcli, you might have to check ~/.pgclirc file.
