### ISSUE TITLE
PGCli initialization issue

### ISSUE THREAD

**Issue by klonuo** [dbcli/pgcli#499]
On [PGCli](https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L109) initialization [`write_default_config()`](https://github.com/dbcli/pgcli/blob/master/pgcli/config.py#L33) is called with non-optional `destination` argument, which indicates that in PGCli constructor `pgclirc_file` argument should not be optional, as it is now set.
That argument is later again called by other functions in constructor.

**Comment by amjith** [comment]
@klonuo I can make that a non-optional value for strictness sake or you're welcome to submit a PR to do that.

**Comment by klonuo** [comment]
Ok, done :)

**Comment by klonuo** [comment]
OTOH, now that I've made PR I'm thinking that maybe we should leave `pgclirc_file` argument optional and add some code to resolve to default value before it is called by other functions. 

For example, now as is, issuing `pgcli = PGCli()` raises:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python35\lib\site-packages\pgcli\main.py", line 87, in __init__
    write_default_config(default_config, pgclirc_file)
  File "C:\Python35\lib\site-packages\pgcli\config.py", line 22, in write_default_config
    destination = expanduser(destination)
  File "C:\Python35\lib\ntpath.py", line 312, in expanduser
    if not path.startswith(tilde):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

And this is actual code in pgcli's `magic.py` - https://github.com/dbcli/pgcli/blob/master/pgcli/magic.py#L33

Do you agree?

**Comment by amjith** [comment]
@klonuo Can you tell me what problem we were trying to originally solve? Was there a problem with setting a default value for pgclirc file? 

If so can you tell me how it manifested? I may have give you answers hastily. So can you please give me a little background?

**Comment by klonuo** [comment]
Well, as in opening post, on `PGCli` initialization `write_default_config` is called with non-optional `pgclirc_file`. For example try this: `pgcli = PGCli()`

So I made PR to make `pgclirc_file` not optional, but I think that it is better to leave the code as is and add for example this line in PGCli init, before `write_default_config()` is called:

```python
pgclirc_file = pgclirc_file or os.path.expanduser('~/.pgclirc')
```

That way user can instantiate PGCli without arguments.

Hopefully it is clear now?

**Comment by amjith** [comment]
👍 

Will you be updating the existing PR?

**Comment by klonuo** [comment]
I closed existing PR and made new one
