### ISSUE TITLE
Add configuration option to disable startup and exit messages

### ISSUE THREAD

**Issue by mkataja** [dbcli/pgcli#518]
Add a configuration option to disable some or all of the following startup and exit messages to reduce the amount of output:

> Version: 0.20.1
> Chat: https://gitter.im/dbcli/pgcli
> Mail: https://groups.google.com/forum/#!forum/pgcli
> Home: http://pgcli.com

> Goodbye!

The messages could still be enabled by default.

**Comment by amjith** [comment]
This is now available in v1.0. Please upgrade. 

```
pip install -U pgcli
```
