### ISSUE TITLE
Make the "more than 1000 rows" warning limit configurable

### ISSUE THREAD

**Issue by mkataja** [dbcli/pgcli#519]
Add a configuration option to change the number of rows that causes the following warning to be shown:

> The result set has more than 1000 rows.
> Do you want to continue? [y/N]:

Setting the option to 0 should disable the warning altogether.

**Comment by drocco007** [comment]
@amjith Do you have an opinion about this being an option in the configuration file vs. a command line argument vs. both? The PR from @Smotko implements a command line argument.

**Comment by amjith** [comment]
I don't have a strong opinion. If I had implemented I'd probably have picked the config file.

**Comment by Smotko** [comment]
I've added it to the config file as well.
