### ISSUE TITLE
'@' in password

### ISSUE THREAD

**Issue by timothyjlaurent** [dbcli/pgcli#52]
I have an '@' symbol in a password. I tried escaping it with '\@' but this also didn't work.

**Comment by amjith** [comment]
That's most definitely a bug. I wonder how psql handles this. 

In the meantime you can try using the command line switches to prompt for the password instead of using the postgres:// style url. 

```
pgcli -h localhost -p 5432 -U amjith -W app_db
```

Launching that way will prompt for the password.

**Comment by jackmaney** [comment]
Have you tried URL-escaping the `@` to `%40`?

**Comment by drocco007** [comment]
Have you tried with the latest pgcli? I successfully connected using a role with an '@' character using pgcli 0.16.0 against a 9.4 server:

    postgres=# create role atpw LOGIN PASSWORD '@at';
    CREATE ROLE
    postgres=# create database atdb owner atpw;
    CREATE DATABASE
    postgres=# \q
    
    $ pgcli postgres://atpw:@at@localhost:5432/atdb
    Version: 0.16.0
    Chat: https://gitter.im/amjith/pgcli
    Mail: https://groups.google.com/forum/#!forum/pgcli
    Home: http://pgcli.com
    atdb>

**Comment by amjith** [comment]
Previously I was using my own custom built parsing routine for extracting the password and username from the postgres url. I've replaced that routine with `urlparse` from python stdlib. So this might not be an issue anymore. 

Thanks @drocco007 for testing it. I'll close the issue.

**Comment by catando** [comment]
The issue seems to persist/have returned:

```bash
pgcli postgres://atpw:@at@localhost:5432/atdb
could not translate host name "at@localhost" to address: nodename nor servname provided, or not known
```

A workaround is to escape the `@`s with sed:
```bash
pgcli postgres://atpw:"$(echo '@at'|sed -e s/@/\%40/g)"@localhost:5432/atdb
```
```

**Comment by j-bennet** [comment]
@catando What is your `pip freeze` output?

**Comment by j-bennet** [comment]
@przdev A note in readme would be good, or better yet, in the docs on the `pgcli.com` website. Here is the link to docs source:

https://github.com/dbcli/pgcli.com/blob/master/content/pages/3.docs.md
