### ISSUE TITLE
Filter out PG trigger implementation functions

### ISSUE THREAD

**Issue by drocco007** [dbcli/pgcli#520]
Using master checkouts for pgcli & pgspecial on PG 9.3.5, the Postgres internal trigger functions are being pulled in to the suggestions:

![image](https://cloud.githubusercontent.com/assets/1424858/15754619/fc388668-28c6-11e6-9ed4-d5b9f4105b07.png)

Since they're capitalized, they're also floating to the top of the suggestion list. I'm guessing this was inadvertent; it makes the completion list feel cluttered to me.

Perhaps we should exclude functions with the `RI_FKey` the way we currently do for `pg_` items?

@amjith

**Comment by koljonen** [comment]
I think we should just filter out any functions where **prorettype::regtype = 'trigger'** in pgexecute.

**Comment by drocco007** [comment]
I've created a PR that implements @koljonen's suggestion :)

Tested on PostgreSQL server versions 9.3.5 & 8.4.22
