### ISSUE TITLE
Please sign your releases and/or git tags

### ISSUE THREAD

**Issue by AdamMajer** [dbcli/pgcli#542]
Is it possible for your to sign release tags? This way it would be possible to verify that the source code releases come from the same source.

   http://stackoverflow.com/questions/5663733/signing-tags-in-git

Thanks in advance.

**Comment by amjith** [comment]
Just a few days ago my coworker showed me that it's possible to sign commits. I was going to look into it, this is a nice excuse for me to do so. :)

**Comment by AdamMajer** [comment]
On 07/05/2016 04:08 PM, Amjith Ramanujam wrote:
> Just a few days ago my coworker showed me that it's possible to sign
> commits. I was going to look into it, this is a nice excuse for me to do
> so. :)

Very good! Signing commits is good too but for most people just
downloading software, signed release tags

    git tag -s release_tag

are more than good enough. These verify the entire source tree is 
authentic up to that point.

Cheers,
Adam

**Comment by j-bennet** [comment]
Release script is updated to do this. Closing.
