### ISSUE TITLE
Implement \copy (...) TO PROGRAM '...'

### ISSUE THREAD

**Issue by thalesmello** [dbcli/pgcli#558]
Hello.

Excellent project! So far, pgcli replaced the old `psql` except for this one feature.

`psql` allows you to use the `\copy` command to pipe a query into a shell command, which might be useful to copy the results of a query to the system clipboard (using pbcopy on a Mac, though there are similar utilities for GNU/Linux and Windows). Therefore, if I do something like:

`\copy (SELECT name, age FROM Users) TO PROGRAM 'pbcopy' DELIMITER e'\t' CSV HEADER`

It copies the result of the query to the clipboard and then I can easily paste it into a spreadsheet application.

I would like to be able to do something like this on `pgcli` as well.

How difficult would it be to implement this?

**Comment by assembler** [comment]
In `psql` we can also do `\g | pbcopy` which would basically copy the results from last query to clipboard. I really miss this in pgcli.

**Comment by frankyjuang** [comment]
Any updates? wonder how people export query result to clipboard or external editors like vscode

**Comment by lordlycastle** [comment]
Clipboard should be an optional solution because you could use this tool to export large volume of data which should not be stored in clipboard. 

Export to disk like currently with `\o filename` except in structured format e.g. CSV, JSONL etc. would amazing to have!

**Comment by radoslawklak** [comment]
+1 copy results to clipboard `select id from table`

**Comment by rklak** [comment]
any chance on this ?
