### ISSUE TITLE
"alias timestamptz not supported" when connecting to Redshift instance

### ISSUE THREAD

**Issue by LiraNuna** [dbcli/pgcli#560]
I am getting the error `alias timestamptz not supported` when I attempt to connect to a Redshift instance.

According to https://github.com/dbcli/pgcli/issues/282, Redshift is supported since v1.0 and accoding to http://pgcli.com/v1.0.0.html `timestamptz` was added as a DATE custom extension.

```
$ pgcli --version
Version: 1.1.0
```

**Comment by LiraNuna** [comment]
NOTE: This seems fixed in master but not in 1.1.0.

**Comment by amjith** [comment]
You're right this was recently fixed https://github.com/dbcli/pgcli/pull/546. I haven't made a release since then.

**Comment by amjith** [comment]
Released in version 1.4. Please upgrade. 

```
pip install -U pgcli
```
