### ISSUE TITLE
Pasting a "COPY ... FROM stdin" command freezes the program indefinitely

### ISSUE THREAD

**Issue by danielyli** [dbcli/pgcli#564]

**Comment by j-bennet** [comment]
@danielyli Some reproduction steps would be helpful. Also, what OS are you running on?

**Comment by j-bennet** [comment]
I didn't try `COPY ... FROM STDIN` before, but now I did, I can see what you are talking about. They work differently in `psql` and `pgcli`.

Assuming I selected database `boo` and created table `create table xxx (x int, y text);`:

In `psql`:

```
boo=# copy xxx (x, y) from stdin delimiter ',' csv;
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself.
>> 1,a
>> 2,b
>> \.
COPY 2
```

In pgcli, `\copy` is a "special command" - one of the "backslash" commands:

```
boo> \copy xxx from stdin with csv
3,c
^D
Time: 9.942s (9 seconds)
boo>
```

Here, I had to press `Ctrl + D` twice to signal EOF.

Also, if I try to run this command again in pgcli, nothing happens. It will not let me enter csv data:

```
boo> \copy xxx from stdin with csv

Time: 0.002s
boo>
```

This 2nd issue looks like a bug. First one is more of an implementation difference.

@amjith and @catherinedevlin, is this how `\copy` was supposed to work in pgcli?

**Comment by danielyli** [comment]
@j-bennet Ah, apologies for the late response! I've been very busy lately. Thank you for filling in the reproduction steps!

**Comment by elenigen** [comment]
Actually, the same "freeze" problem happen with the 
```
COPY ... TO STDOUT
```
But, again if we do like j-bennet  suggested, then it works fine:
```
\copy xxx TO STDOUT
```

**Comment by danielyli** [comment]
If pgcli isn't intended to be an identical-behavior replacement for psql, I don't think there's much harm in mandating the `\copy` syntax.  In that case, can I suggest an error message upon using `COPY`?

**Comment by j-bennet** [comment]
@danielyli I agree, that would be more graceful as a temporary solution, even if we want to align these behaviors in future. Let's keep the issue open.
