### ISSUE TITLE
pgcli get stuck indefinitely on Windows

### ISSUE THREAD

**Issue by kumarharsh** [dbcli/pgcli#565]
I'm using Powershell on ConEmu to run pgcli after installing it via pip, and it just gets stuck when I run `pgcli`. Only `pgcli --help` outputs the help, nothing else works.

**Comment by darikg** [comment]
You can connect successfully with psql though? I've had issues on Windows before with a bad connection where psycopg2 just hangs instead of timing out.

**Comment by kumarharsh** [comment]
Yes, psql works. Actually, I missed out one important thing: My postgres is running in a docker container, and I've already configured port-forwarding, etc, so that my applications in windows can connect to the postgres database inside the docker container. Manually specifying the port in `pgcli` did not help.

**Comment by darikg** [comment]
Do you mind running this at the command line to see if it hangs so we can confirm it's a problem specific to psycopg2:

```
 python -c "import psycopg2; psycopg2.connect(database='mydb', user='username', password='secret', port=5432)"
```
with the obvious values replaced with your specifics?

**Comment by kumarharsh** [comment]
That line works, but it gave no output (and no error, so I'm assuming it ran fine)

**Comment by darikg** [comment]
Huh well I guess psycopg2 is working fine then. So the problem really is with pgcli. Do you mind editing `AppData\Local\dbcli\pgcli\config` to set `log_level = DEBUG` and then running pgcli again and copying the last few lines from `AppData\Local\dbcli\pgcli\log` and maybe we can figure out where it's hanging?

**Comment by kumarharsh** [comment]
This is all:
```
2016-08-24 13:16:17,641 (9796/MainThread) pgcli DEBUG - Initializing pgcli logging.
2016-08-24 13:16:17,641 (9796/MainThread) pgcli DEBUG - Log file u'C:\\Users\\kumar\\AppData\\Local\\dbcli\\pgcli\\log'.
2016-08-24 13:16:17,651 (9796/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
```

**Comment by kumarharsh** [comment]
I've tested pgcli with cmd.exe, git bash, powershell on conemu and even vanilla CMD.exe - all of them get stuck in the same way.

**Comment by darikg** [comment]
I'm able to replicate something like this when running `pgcli` with no connection details, and pgcli defaults to try to connect to localhost, when I don't have postgresql server running. pgcli hangs and the debug log stops at the same point as yours.

Can you connect successfully if you specify all the connection details, like 
```
pgcli postgresql://user:password@host/dbname
```
?

**Comment by kumarharsh** [comment]
I've tried these, which don't work:
I don't have a password set for my database, hence no `:password`.
```
pgcli postgres://postgres@localhost:5432/pl_core
pgcli postgresql://postgres@localhost:5432/pl_core
```

**Comment by darikg** [comment]
So sorry for all the hassle @kumarharsh 
I've (I think) fixed a problem where pgcli will hang in a connection error. I have a fix here: #571
I don't think it will fix your problem directly, but it should at least report an error message instead of freezing. 
Could you please try it out with
```
 pip install git+https://github.com/dbcli/pgcli.git@darikg/no-hang-wait-select
```

**Comment by kumarharsh** [comment]
no problems! I'll give it a try

**Comment by kumarharsh** [comment]
@darikg it's still the same

**Comment by darikg** [comment]
I'm sorry! I'm completely stumped then. I will try to get postgresql running in a docker instance to see if I can replicate it. Might not happen real soon though.

**Comment by j-bennet** [comment]
@kumarharsh Are you specifying host explicitly? `pgcli` will default to `localhost` if you aren't, and on Windows you may need to use docker machine IP instead.

**Comment by kumarharsh** [comment]
@darikg I got it working using @j-bennet's suggestion:
```
pgcli postgresql://<username>@192.168.99.100:5432/<my_db>
```

However, after I write the first word in the cli, say `SEL..<ENTER>' to select the 'SELECT' keyword and then I press <kbd>Space</kbd>, there is an error thrown:

```
Traceback (most recent call last):
  File "c:\langs\python27\lib\threading.py", line 551, in __bootstrap_inner
    self.run()
  File "c:\langs\python27\lib\threading.py", line 504, in runode
    self.__target(*self.__args, **self.__kwargs)
  File "c:\langs\python27\lib\site-packages\prompt_toolkit\interface.py", line 836, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "c:\langs\python27\lib\site-packages\pgcli\pgcompleter.py", line 332, in get_completions
    suggestions = suggest_type(document.text, document.text_before_cursor)
  File "c:\langs\python27\lib\site-packages\pgcli\packages\sqlcompletion.py", line 115, in suggest_type
    return suggest_based_on_last_token(stmt.last_token, stmt)
  File "c:\langs\python27\lib\site-packages\pgcli\packages\sqlcompletion.py", line 247, in suggest_based_on_last_token
    token_v = token.value.lower()
AttributeError: 'tuple' object has no attribute 'value'
```

I can, however, keep writing the rest of the command. But the autocomplete breaks after that, and never triggers.

**Comment by amjith** [comment]
@kumarharsh This latest exception you're seeing is due to a known bug that is fixed in master. Can you try upgrading directly from master using the following command? 

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

**Comment by kumarharsh** [comment]
Works like a charm!

**Comment by kumarharsh** [comment]
Is there a way to throw some error or warning when pgcli can't connect to databases? 
For example like I had done at the beginning of this issue? Just writing `pgcli` makes the console stuck and Ctrl+C also doesn't work after that. I have to manually kill the console instance - which made me think this might be a bug.

**Comment by amjith** [comment]
@kumarharsh It was a bug, we have a fix for that in master (as of 5 minutes ago). Thanks @darikg. 

I'd recommend rerunning that update command and see if that works for you. 

Sorry about the bug, we will release the next version pretty soon.

**Comment by kumarharsh** [comment]
Yes, it works with the latest fix. Thanks @amjith  @darikg

**Comment by darikg** [comment]
Glad to hear it!
