### ISSUE TITLE
Allow autocomplete to lowercase/smartcase

### ISSUE THREAD

**Issue by dkarter** [dbcli/pgcli#569]
Many people prefer writing SQL in lowercase. 

When I try to autocomplete a query in pgcli it always autocompletes uppercase. I asked in gitter if there is a way to configure that and was told to open an issue on the repo.

Auto complete lowercase example:
For example `sel<TAB>` should be `select` not `SELECT`.

Auto complete smartcase  example:
`sel<TAB>` should be `select`
 `SEL<TAB>` should be `SELECT`.

Thanks

**Comment by amjith** [comment]
@darikg I think this validates your request (from a while back) to have either casing controlled via the config file. 

I actually like this idea of having it smart cased, so this is not configured via the pgclirc. But I'll leave this up to you to decide how you want to implement it.

If you're not too keen on taking this on, let me know and I'll see what I can do.

**Comment by darikg** [comment]
I like the smart casing idea! I'll take a stab at it.

**Comment by amjith** [comment]
This was implemented a while back and now available in pgcli version 1.4 and above. Please upgrade. 

`pip install -U pgcli`
