### ISSUE TITLE
Connat install - Ubuntu

### ISSUE THREAD

**Issue by PauloDanielCarneiro** [dbcli/pgcli#570]
I can't install pgcli after I remove it by accident. When I try, I get the error: 

```
Collecting pgcli
  Downloading pgcli-1.1.0.tar.gz (53kB)
Requirement already satisfied (use --upgrade to upgrade): pgspecial>=1.5.0 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): click>=4.1 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=2.0 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Requirement already satisfied (use --upgrade to upgrade): prompt_toolkit<1.1.0,>=1.0.0 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Collecting psycopg2>=2.5.4 (from pgcli)
  Downloading psycopg2-2.6.2.tar.gz (376kB)
Requirement already satisfied (use --upgrade to upgrade): sqlparse==0.1.19 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Collecting configobj>=5.0.6 (from pgcli)
  Downloading configobj-5.0.6.tar.gz
Collecting humanize>=0.5.1 (from pgcli)
  Downloading humanize-0.5.1.tar.gz
Requirement already satisfied (use --upgrade to upgrade): wcwidth>=0.1.6 in /usr/local/lib/python2.6/dist-packages (from pgcli)
Collecting setproctitle>=1.1.9 (from pgcli)
  Downloading setproctitle-1.1.10.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in /usr/local/lib/python2.6/dist-packages (from prompt_toolkit<1.1.0,>=1.0.0->pgcli)
Installing collected packages: psycopg2, configobj, humanize, setproctitle, pgcli
  Running setup.py install for psycopg2: started
    Running setup.py install for psycopg2: finished with status 'error'
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-foEXxJ/psycopg2/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-pIdxrC-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.6
    creating build/lib.linux-x86_64-2.6/psycopg2
    copying lib/errorcodes.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/pool.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/__init__.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/extensions.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/extras.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/tz.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/_json.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/psycopg1.py -> build/lib.linux-x86_64-2.6/psycopg2
    copying lib/_range.py -> build/lib.linux-x86_64-2.6/psycopg2
    creating build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_extras_dictcursor.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_psycopg2_dbapi20.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_copy.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_async.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_bug_gc.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_types_basic.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/testutils.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_with.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_cursor.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/testconfig.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_quote.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_cancel.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_errcodes.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_green.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_types_extras.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_lobject.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_notify.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_bugX000.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_connection.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_transaction.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/dbapi20_tpc.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_dates.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/test_module.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    copying tests/dbapi20.py -> build/lib.linux-x86_64-2.6/psycopg2/tests
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.linux-x86_64-2.6
    creating build/temp.linux-x86_64-2.6/psycopg
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DPSYCOPG_DEFAULT_PYDATETIME=1 -DPSYCOPG_VERSION="2.6.2 (dt dec pq3 ext lo64)" -DPG_VERSION_HEX=0x090504 -DHAVE_LO64=1 -I/usr/include/python2.6 -I. -I/usr/include/postgresql -I/usr/include/postgresql/9.5/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-2.6/psycopg/psycopgmodule.o -Wdeclaration-after-statement
    In file included from psycopg/psycopgmodule.c:27:0:
    ./psycopg/psycopg.h:30:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
```

What can I do?

**Comment by amjith** [comment]
Looks like you don't have python-dev package on your machine. Try installing: 

```
sudo apt-get install python-dev
```

**Comment by PauloDanielCarneiro** [comment]
Yes, I have. And when I try to install again, shows "python-dev is already
the newest version (2.7.11-1). ", as expect. Any other thing? TT_TT

Off.:
When I install with apt-get, it works, but the auto-complete function don't
work.

**Comment by amjith** [comment]
The install is failing on psycopg2. Try pip installing psycopg2 separately and see if that passes. If it doesn't, it probably means that the python you're using to install psycopg2 is different from the system python. The python-dev that you have is matched with the system python, since you're using a different python than the system python, it can't find the python headers for your python, even though the system python headers are available. 

My recommendation would be to use your system python. I believe the system python is installed at /usr/bin/python. You can try: 

```
/usr/bin/python -m pip install pgcli
```

BTW, I'm not sure why auto-completion doesn't work with the apt-get installed version. Can you check the version number of pgcli that is installed via apt-get? 

One way to debug would be to set the `log_level` to `debug` in your config file (~/.config/pgcli/config) and launch pgcli. Then send me the log file (~/.config/pgcli/log).

**Comment by PauloDanielCarneiro** [comment]
It failed to instal psycopg2. And `/usr/bin/python -m pip install pgcli`
returns "/usr/bin/python: pip is a package and cannot be directly
executed". I think it's a problem with python and the python's OS. Maybe of
I reinstall the OS...

On Wed, Aug 24, 2016 at 10:14 AM, Amjith Ramanujam <notifications@github.com

**Comment by amjith** [comment]
I believe you have python 2.6 as the default version of python on this system. Which doesn't allow pip to be called as a module.

Can you tell me how you installed the new version of python on your system? 

I think the easiest solution at the moment would be to find out why apt-get install pgcli doesn't do what you want. Can you install pgcli via apt-get install pgcli and then launch pgcli and see if that works? 

If it fails on auto-completion then can you set the log_level to debug and send me the log files?

**Comment by PauloDanielCarneiro** [comment]
I instaled pgcli, and it works. Everything, but the auto-completion.(This
is the version of the repo)

Here the log file

On Fri, Aug 26, 2016 at 12:04 PM, Amjith Ramanujam <notifications@github.com

**Comment by PauloDanielCarneiro** [comment]
Any problem in the log files?

**Comment by amjith** [comment]
@PauloDanielCarneiro The log file gave me some clues. I'm guessing that the database that you're connecting to has a lot of tables or it is located in a network that is far away (high latency). 

When you launch pgcli do you see a message in the status bar at the bottom that says "Refreshing completions....."? When that message is active the autocompletion thread is still gathering data in the background. So while that message is active the completions will be empty. When that message is gone you'll start to see completion working.

The latest stack trace you've posted leads me to believe that the database is on a network with  high latency, so completion thread timed out waiting for the results. 

Can you confirm the following things? 

* Is the database you're connecting really large with many tables? 
* Is the database instance located in a far off place (such as across the world) to cause such high latency? 
* Can you try connecting to a smaller database first to see if the basic completion works?
* What version of pgcli are you running? You can check that by running `pgcli --version`.

**Comment by PauloDanielCarneiro** [comment]
Hello.

Well, the database is in my city, São Paulo. There are very many tables,
really. I can connect normally in my pc(in home, with a VPN) and show the
completions. But in my pc at work, with wired connection(the VPN is in the
router in my work place) they don't show at all. My version is 1.1.0.

There is anything that I can do with the time out?

**Comment by PauloDanielCarneiro** [comment]
I'll take this pc to my home and try in my network, with VPN.

**Comment by PauloDanielCarneiro** [comment]
Hello.

In my house it worked as expect. I think it's the local network in my work.
Thanks. ^^

**Comment by amjith** [comment]
@PauloDanielCarneiro Thanks for taking the time to check this out and report back the results. I'm sorry it is having issues with the work network.

You can try one other thing to see if it helps. 

Launch pgcli with a command line option called `--single-connection`. This forces pgcli to use a single connection to do the autocompletion instead of making multiple connections. 

See if that helps.

**Comment by j-bennet** [comment]
I'm going to close this as there has been no update in a long time. Feel free to reopen if you are still experiencing problems.
