### ISSUE TITLE
Execution time

### ISSUE THREAD

**Issue by elenigen** [dbcli/pgcli#575]
I executed a SQL script with \i file which took a while (many minutes), but at the end it printed:
Time: 27262526.337s (10 months)

**Comment by amjith** [comment]
Wow. That is quite a sql file you must have executed there. 

Sorry about the bug, I'll take a look soon.

**Comment by amjith** [comment]
This is now fixed in master. Try it out by installing using the following command:

```
pip install -U https://github.com/dbcli/pgcli/archive/master.zip
```

I'll release a fix for it soon.

**Comment by elenigen** [comment]
Thanks!

**Comment by amjith** [comment]
This has been fixed for a while. Closing.
