### ISSUE TITLE
How to display time in prompt?

### ISSUE THREAD

**Issue by d33tah** [dbcli/pgcli#580]
I'd like my prompt to be prepended with `[`date "+%d/%m/%y %H:%M:%S"`]` so I could see how long queries take and when they finish. How could I do that most easily?

**Comment by amjith** [comment]
@d33tah We currently don't have that available in the prompt specifiers. But it is trivial to add. Here's the relevant code snippet. https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L687-L694

I wouldn't be opposed to the idea if you want to send a PR. 😄 

ps: We do time the queries and print the results at the end of each query. In fact we fixed a bug recently to fix a bug in the calculation #578.

**Comment by gustavo-castro** [comment]
I would like to be assigned this issue if possible

**Comment by j-bennet** [comment]
@gustavo-castro Absolutely! Thank you for your help!

**Comment by j-bennet** [comment]
@gustavo-castro So looks like we can't assign an issue to a non-collaborator (https://github.com/isaacs/github/issues/100), but go ahead and send a PR anyway. PRs are always welcome.

**Comment by gustavo-castro** [comment]
@j-bennet Great! I'll send it by the week.

**Comment by j-bennet** [comment]
Fixed via https://github.com/dbcli/pgcli/pull/715.
