### ISSUE TITLE
prompt doesn't display only the database name when using database url

### ISSUE THREAD

**Issue by diwu1989** [dbcli/pgcli#584]
if I run pgcli with a database url string such as

```
~ $ pgcli postgres://uk96oqkdlqoiu:********@ec2-52-208-73-133.eu-west-1.compute.amazonaws.com:5432/d1vh7hb3u2qrhp
Version: 1.2.0
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
uk96oqkdlqoiu@ec2-52-208-73-133.eu-west-1.compute.amazonaws.com:d1vh7hb3u2qrhp>
```

the prompt is super long and has the full database url whereas I expect it be just the db name

```
d1vh7hb3u2qrhp>
```

**Comment by amjith** [comment]
@diwu1989 Sorry about that. You can adjust the prompt in your config file located at ~/.config/pgcli/config. 

Take a look at the [prompt specification](https://github.com/dbcli/pgcli/blob/master/pgcli/pgclirc#L101).
