### ISSUE TITLE
pgcli v1.2.0 not working for redshift

### ISSUE THREAD

**Issue by mbarkhau** [dbcli/pgcli#588]
Introduced by https://github.com/dbcli/pgcli/commit/3f310f5070d45852afda29ed50ba656ff1cb7465#diff-8859be39408e4fbeea82b923784d9e65R163

```
> select current_setting('is_superuser')::bool
cannot cast type text to boolean
```

Leaving away the cast

```
> select current_setting('is_superuser')
must be superuser to examine "is_superuser"
```

Which I'm guessing means I'm not a superuser :-)

**Comment by mbarkhau** [comment]
I'll see if I can get a fix working.

**Comment by bobcolner** [comment]
I'm also seeing this issue when trying to connect to redshift on pgcli v1.20

`cannot cast type text to boolean`

**Comment by mbarkhau** [comment]
Yes the version on pypi is still broken, but you can install directly from the repository 
```
pip install "https://github.com/dbcli/pgcli/archive/master.zip"
```
