### ISSUE TITLE
Formatting error with string-typed numbers

### ISSUE THREAD

**Issue by darikg** [dbcli/pgcli#590]
This seems to be an issue with the new comma formatting cc @foxyterkel 

```
dg@z.db:zdb_110z> select '123'
Unknown format code 'd' for object of type 'unicode'
```

**Comment by fpietka** [comment]
@amjith isn't it fixed now? seems the fix got merged.

**Comment by j-bennet** [comment]
You're right - this is not a problem anymore. Closing.
