### ISSUE TITLE
Select bad syntax highlighting

### ISSUE THREAD

**Issue by thomasballinger** [dbcli/pgcli#593]
```
tomb@(none):sqlpractice> SELECT name, salary from employees
```

![badhighlight](https://cloud.githubusercontent.com/assets/458879/19023713/0c9547e2-88c3-11e6-8db9-fdc320886191.png)

For me `name` is highlighted, despite it appearing here not as a keyword but as a column name. Is this something worth fixing? I don't know sql very well, is it standard not to use keywords like `name` as column names?

**Comment by amjith** [comment]
The syntax highlighting provided by Pygments uses a regex based matching algorithm. It doesn't try to parse the structure of the sql to find the appropriate highlighting. 

I haven't dug into changing this behavior.

**Comment by blandonfrank** [comment]
name is a postgresql function/type. Hence it gets highlighted. I don't think this is an issue.

**Comment by j-bennet** [comment]
I agree with @blandonfrank here.
