### ISSUE TITLE
Problem with Python 3.6.0b2

### ISSUE THREAD

**Issue by lelit** [dbcli/pgcli#595]
Hi all,

this is just an alert, because I think the culprit is Python, not pgcli. Nevertheless, digging into the problem I found what seems an _innocent_ glitch, read below.

I quote here a [message](https://mail.python.org/pipermail/python-list/2016-October/715462.html) I just sent to the Python user list:

> Hi all,
> 
> trying out pgcli with Python 3.6.0b2 I got an error related to what seem a
> different behaviour, or even a bug, of re.sub().
> 
> The original intent is to replace spaces within a string with the regular expression
> \s+ (see https://github.com/dbcli/pgcli/blob/master/pgcli/packages/prioritization.py#L11,
> ignore the fact that the re.sub() call seem underoptimal).
> 
> With Python 3.5.2 is straightforward:
> 
>   $ python3.5
>   Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
>   [GCC 6.2.0 20160927] on linux
>   Type "help", "copyright", "credits" or "license" for more information.
>   >>> import re
>   >>> re.sub(r'\s+', r'\s+', 'foo bar')
>   'foo\\s+bar'
> 
> While Python 3.6.0b2 gives:
> 
>   $ python3.6
>   Python 3.6.0b2+ (default, Oct 11 2016, 08:30:05) 
>   [GCC 6.2.0 20160927] on linux
>   Type "help", "copyright", "credits" or "license" for more information.
>   >>> import re
>   >>> re.sub(r'\s+', r'\s+', 'foo bar')
>   Traceback (most recent call last):
>     File "/usr/local/python3.6/lib/python3.6/sre_parse.py", line 945, in parse_template
>       this = chr(ESCAPES[this][1])
>   KeyError: '\\s'
> 
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "<stdin>", line 1, in <module>
>     File "/usr/local/python3.6/lib/python3.6/re.py", line 191, in sub
>       return _compile(pattern, flags).sub(repl, string, count)
>     File "/usr/local/python3.6/lib/python3.6/re.py", line 326, in _subx
>       template = _compile_repl(template, pattern)
>     File "/usr/local/python3.6/lib/python3.6/re.py", line 317, in _compile_repl
>       return sre_parse.parse_template(repl, pattern)
>     File "/usr/local/python3.6/lib/python3.6/sre_parse.py", line 948, in parse_template
>       raise s.error('bad escape %s' % this, len(this))
>   sre_constants.error: bad escape \s at position 0
> 
> Accordingly to the documentation (https://docs.python.org/3.6/library/re.html#re.sub) 
> “unknown escapes [in the repl argument] such as \& are left alone”.
> 
> Am I missing something, or is this a regression?
> 

That said, I think the mentioned `_compile_regex()` should call the `sub()` method on the already compiled pattern `white_space_regex`, instead of passing it to the `re.sub()` function: in other words, the line:
```
  pattern = '\\b' + re.sub(white_space_regex, '\\s+', keyword) + '\\b'
```
could/should be written as
```
  pattern = '\\b' + white_space_regex.sub('\\s+', keyword) + '\\b'
```

**Comment by lelit** [comment]
The mentioned thread clarified the issue: Python 3.6+ makes a shift toward rejecting _unknown_ escaped chars.

The simplest fix is to use a _raw string_ for the replacement above, containing **two** backslashes. The line should then be something like
```
pattern = '\\b' + re.sub(white_space_regex, r'\\s+', keyword) + '\\b'
```

I tested it on Python 2.7, 3.5 and 3.6.0b2 and verified that it works flawlessly:
```
$ python2.7
Python 2.7.12+ (default, Sep  1 2016, 20:27:38) 
[GCC 6.2.0 20160927] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> keyword_name = 'create database'
>>> kn_regexp = re.sub(r'\s+', r'\\s+', keyword_name)
>>> re.match(kn_regexp, keyword_name)
<_sre.SRE_Match object at 0x7fe892c57648>
>>> re.match(kn_regexp, 'create    database')
<_sre.SRE_Match object at 0x7fe892c576b0>

$ python3.5
Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> re.sub(r'\s+', r'\s+', 'foo bar')
'foo\\s+bar'
>>> keyword_name = 'create database'
>>> kn_regexp = re.sub(r'\s+', r'\\s+', keyword_name)
>>> re.match(kn_regexp, keyword_name)
<_sre.SRE_Match object; span=(0, 15), match='create database'>
>>> re.match(kn_regexp, 'create    database')
<_sre.SRE_Match object; span=(0, 18), match='create    database'>

$ python3.6
Python 3.6.0b2+ (default, Oct 11 2016, 08:30:05) 
[GCC 6.2.0 20160927] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> keyword_name = 'create database'
>>> kn_regexp = re.sub(r'\s+', r'\\s+', keyword_name)
>>> re.match(kn_regexp, keyword_name)
<_sre.SRE_Match object; span=(0, 15), match='create database'>
>>> re.match(kn_regexp, 'create    database')
<_sre.SRE_Match object; span=(0, 18), match='create    database'>
```

**Comment by amjith** [comment]
Awesome! Thank you for following up on this and staying on the forefront of the bleeding edge. 

Would you mind opening a PR with the changes you recommended?

**Comment by lelit** [comment]
Amjith Ramanujam <notifications@github.com> writes:

> Would you mind opening a PR with the changes you recommended? 

Yes, sure!
