### ISSUE TITLE
better handling of non-reserved keywords?

### ISSUE THREAD

**Issue by darikg** [dbcli/pgcli#597]
I've been working in a database that uses the word 'session' as a column name everywhere. It's pretty annoying that pgcli wants to escape it as `"session"` in suggestions, and even more annoying that suggestions will break if it's used without being escaped earlier. E.g. 
`select * from sessions where session = 1 and`
 fails to suggest columns as it should. According to [the postgresql docs](https://www.postgresql.org/docs/9.4/static/sql-keywords-appendix.html) session is a non-reserved keyword, so this seems non-ideal. I'm not sure how best to address it though.

There's two pain points to address:
1. sqlparse lists `SESSION` as a keyword [here](https://github.com/andialbrecht/sqlparse/blob/1e4a4775d1f1c82cecc297938e9b29287c52014d/sqlparse/keywords.py#L492)
   - I think this could be handled by introducing a new sqlparse token subclass `Token.Keyword.Nonreserved`
   - Then `pgcli.packages.parseutils.utils.find_prev_keyword` would skip over non-reserved keywords
2. We list `SESSION` in [pgliterals.json](https://github.com/dbcli/pgcli/blob/1b6fee1f6e5ad1686f622758d6cecf2996dd3050/pgcli/packages/pgliterals/pgliterals.json#L117)
   - Add a field to pgclirc that points to a non-default pgliterals.json file where the user can remove keywords at will?

Any better ideas?

**Comment by darikg** [comment]
Ahh, I think the solution is much less complicated than I was making it out to be here

**Comment by j-bennet** [comment]
Looks like this was fixed a while ago.
