### ISSUE TITLE
"connection already closed"

### ISSUE THREAD

**Issue by msztolcman** [dbcli/pgcli#600]
When I leave pgcli running for a few hours, but without any actions/queries, it disconnect silently from server and cannot connect again. I observed it only after putting laptop in sleep mode, in other case I didn't leave computer not used for so long time :)

After wake up, I go to pgcli, and there:

> eden> table brand_smtp_config
> could not receive data from server: Operation timed out
> 
> eden> table brand_smtp_config
> connection already closed
> eden> \?
> connection already closed
> eden> \c eden
> connection already closed
> eden>

I must exit from pgcli and run it again, then everything works OK.

**Comment by amjith** [comment]
This is now fixed in pgcli 1.5. Can you upgrade and try again? 

```
pip install -U pgcli
```

**Comment by msztolcman** [comment]
@amjith verified, working fine, thanks :)
