### ISSUE TITLE
Option to see all column names during autocomplete

### ISSUE THREAD

**Issue by Gollum999** [dbcli/pgcli#604]
One thing that I miss from the official PSQL client is that, if I am mid-query and I forget the column names for the current table, (e.g. right after typing **WHERE**,) I can double-tab TAB to see all possibilities listed out.

Unfortunately, the pgcli autocomplete popup lists not only column names, but function names and keywords as well.  On a production database with hundreds of functions defined, autocomplete is basically worthless until I have typed the first 2 or 3 characters of what I want (which of course is difficult if I don't remember the column names in the first place.)

Right now I handle this by backing out of my current query, running `\d <table name>`, and then typing my query again, but this is quite clumsy.  I think a hotkey to either

a) toggle some sort of "column-only"  autocomplete mode, or
b) simply print out available columns

would be very helpful in terms of usability.

(Technically this should be context sensitive, e.g. it should use table names instead of column names after a **FROM**, but column names are the only case I personally care about.  :smile: )

**Comment by amjith** [comment]
@Gollum999 Can you tell me what version of pgcli you're using? 

You should see all the columns listed before we move on to listing functions. I know this was temporarily broken in version 1.0.0 but we've fixed it in the latest version. Can you try the newer version and let us know if the problem still persists? 

You can upgrade using `pip install -U pgcli`

**Comment by Gollum999** [comment]
@amjith I am currently on version 1.1.0.  I'm having SSL issues while trying to upgrade; I'll let you know when I get it working and am able to test.

I like the idea to list columns before functions; that sounds much better than my suggestion.

**Comment by Gollum999** [comment]
Got it working.  Yes, this is fixed in version 1.2.0.

Thanks for the help!  Really excited to see that this is already available.  I'll close this issue.
