### ISSUE TITLE
Using an external editor other than Vim

### ISSUE THREAD

**Issue by CodeMonkeyMike** [dbcli/pgcli#610]
Is it possible to use an editor other than vim as the external editor, the one which is opened with the \e command. I would like to use NeoVim without having to mess with Vim which is installed on my system, the command which I use to launch NeoVim is "nvim"

**Comment by amjith** [comment]
The default editor is controlled by the `$EDITOR` variable in your shell. So if you set you`$EDITOR` to `nvim` then the `\e` will respect that setting and launch the appropriate editor for you.

**Comment by CodeMonkeyMike** [comment]
Thank you
