### ISSUE TITLE
Can't connect to postgres database.

### ISSUE THREAD

**Issue by argentum47** [dbcli/pgcli#616]
Either its my mistake or lack of docs. I installed with pip `pip install --user pgcli`. Added the `~/Python2.7/lib/python/site-packages` to `PATH`.

This is how I normally connect:
```
authentication-service git:master ❯ psql -U postgres -d authentication_service                                                                               psql (9.5.3)
Type "help" for help.

authentication_service=# \q
```

I did this: (but none worked)

```
authentication-service git:master ❯ pgcli postgres://postgres:5432/authentication_service
zsh: permission denied: pgcli

authentication-service git:master ❯ pgcli postgres://postgres::5432/authentication_service 
zsh: permission denied: pgcli

authentication-service git:master ❯ pgcli -U postgres -d authentication_service 
zsh: permission denied: pgcli
```

**Comment by amjith** [comment]
Looks like pgcli is not executable. 

Can you run ```ls -l `which pgcli` ```? That should tell you if the executable permissions are set correctly. If it is not, I'd recommend reinstalling pgcli. 

`pip uninstall pgcli && pip install -U pgcli`

**Comment by j-bennet** [comment]
It's been a while with this issue and no update. I'm going to close it. Feel free to reopen if you're still experiencing it @argentum47 .
