### ISSUE TITLE
Numeric output is not showed correctly

### ISSUE THREAD

**Issue by MrOutis** [dbcli/pgcli#617]
I'm using `pgcli` version: 1.3.1

This is the output using `pgcli`:
![1480184973](https://cloud.githubusercontent.com/assets/7363250/20642431/2cf60846-b3d4-11e6-9f0e-cf58c174da7b.png)

And the output for the same query, using `psql`:
![1480184890](https://cloud.githubusercontent.com/assets/7363250/20642430/289aee7e-b3d4-11e6-8b1d-ffa81e8990fd.png)

------------------------

This is a better test that anyone can replicate:

`pgcli`:
![1480185134](https://cloud.githubusercontent.com/assets/7363250/20642444/9a85ebe2-b3d4-11e6-8c2a-67ff6d04905b.png)

`psql`:
![1480185172](https://cloud.githubusercontent.com/assets/7363250/20642449/a245f20a-b3d4-11e6-8642-bb71107c0ec6.png)

------------------------

The behavior is new; at least 4 months ago it was working as intended.

**Comment by MrOutis** [comment]
I didn't found any relevant commit that could change that behaivour, just this one: https://github.com/dbcli/pgcli/pull/591

**Comment by j-bennet** [comment]
Formatting in `pgcli` is done by `tabulate`. `pgcli` keeps its own slightly tweaked version of tabulate [here](https://github.com/dbcli/pgcli/blob/master/pgcli/packages/tabulate.py). Tabulate tries to be smart about formatting numbers.

```
>>> print tabulate.tabulate([['x'], [1.00000000]], headers='firstrow')[0]
  x
---
  1
```

**Comment by MrOutis** [comment]
Thank you, @j-bennet, I'll give it a check.

**Comment by j-bennet** [comment]
I'm not sure what the good solution is here, have to think about it. In a lot of cases, "simplifying" numbers like tabulate does is a good thing, but not when you explicitly format it to certain precision.

**Comment by MrOutis** [comment]
Maybe putting an option in the configuration file to turn off _numeric_simplification_.

**Comment by MrOutis** [comment]
Also, it would be nice to have a bullet about this simplification in the [features section](https://github.com/dbcli/pgcli#features).

**Comment by evanslify** [comment]
Just spend a couple of hours trying to figure out why values become rounded. This option (or at least explicitly written on README.md) could be helpful!

**Comment by MrOutis** [comment]
👍 thanks!

**Comment by shaib** [comment]
Hi, I got to this issue from the readme, where I'm guessing it shouldn't be mentioned anymore...

**Comment by j-bennet** [comment]
@shaib good catch - thanks!
