### ISSUE TITLE
copy (select 1) to stdout blocks.

### ISSUE THREAD

**Issue by amosbird** [dbcli/pgcli#623]
`copy (select 1) to stdout` works fine in psql while blocking in pgcli.

Version: 1.3.1

**Comment by j-bennet** [comment]
In pgcli, copy is implemented as a "special command" (part of [pgspecial](https://github.com/dbcli/pgspecial)). This will work:

```
\copy (select 1) to stdout
```

**Comment by amjith** [comment]
Actually there is a subtle difference between `\copy` and `copy`. `\copy` runs on the client filesystem whereas `copy` statement runs on the server. The difference is only apparent if you're running your server elsewhere and trying to connect from your local machine.
