### ISSUE TITLE
When I type non-ASCII characters they appear as question marks

### ISSUE THREAD

**Issue by sryze** [dbcli/pgcli#634]
When I try to do an insert or other query with some string written in Russian pgcli displays each character as a `?` as I type it or after pasting from the clipboard, but the same query is rendered correctly inside psql.

I'm using WIndows 10 and pgcli 1.4.0 (installed via pip).

**Comment by j-bennet** [comment]
@sryze What terminal are you using? Are you able to type in Russian in your terminal outside of pgcli? (for example, `echo "русский"`).

**Comment by sryze** [comment]
Yes, I can type in Russian outside of pgcli. I'm using ConEmu (tried various shells there with no luck).

**Comment by darikg** [comment]
What version of python are you using? If you're not using 3.6, can you try that? It recently improved unicode handling in Windows.

**Comment by sryze** [comment]
Indeed it does work with Python 3.6.
