### ISSUE TITLE
Crazy behavior: "v" key results in new line 😕

### ISSUE THREAD

**Issue by cristoforo** [dbcli/pgcli#636]
I'm using pgcli 1.4.0 on Windows 10

Everything works fine, I can connect to my Postgres DB, but **when I type the "v" letter I get a new line/carriage return, the same as if I press "Enter"** !!?!

Please note that:
- same happens if I just past the "v" letter inside pgcli 
- capital "V" works fine!!

Already tried with no success:
- run pgcli under cmd, Powershell, git bash, Windows 10 bash: "v" key works as expected inside any of these shells, but inside pgcli it turns into "Enter".
- reboot workstation
- full reinstall of pgcli with `pip install --upgrade --force-reinstall -I --ignore-installed pgcli`

Any ideas?!?? This is driving me crazy

**Comment by azinoviev** [comment]
Same here. On macOS typing "v" letter makes pgcli 1.4.0 open vim, just like \e, but without "# Type your query above this line." line.

**Comment by azinoviev** [comment]
This bug is somewhere in prompt_toolkit 1.0.10. @cristoforo you can do "pip install prompt_toolkit==1.0.9" to avoid "v" bug.

**Comment by amjith** [comment]
@azinoviev Thanks for digging into that. I just reproduced the same bug with the latest prompt_toolkit. I'll file a bug with prompt_toolkit. In the meantime, your workaround is the best way to get around this issue.

**Comment by cristoforo** [comment]
@azinoviev Thank you very much, your workaround solves the issue!

**Comment by amjith** [comment]
Bug filed: https://github.com/jonathanslenders/python-prompt-toolkit/issues/460

**Comment by jonathanslenders** [comment]
Hi everyone, the bug should now be fix. Try upgrading to ``prompt_toolkit==1.0.11``.
Please let me know if you still experience any issues.
And excuse me for the inconvenience.

**Comment by amjith** [comment]
Thanks @jonathanslenders. That fixed the issue for me.
