### ISSUE TITLE
issues when the database password contains "!"

### ISSUE THREAD

**Issue by blandonfrank** [dbcli/pgcli#640]
When the database password contains "!" the connection won't work. I tried escaping it, without any success.
`$ pgcli postgres://tester:test123!@localhost:5432/test`
`-bash: !@localhost: event not found`

**Comment by j-bennet** [comment]
@blandonfrank Did you find a way to resolve this?

**Comment by msztolcman** [comment]
It's bash issue (in fact, it's feature - ! has special meaning in bash), not pgcli. Just put dsn into single quotes, and it will work.

**Comment by blandonfrank** [comment]
> It's bash issue (in fact, it's feature - ! has special meaning in bash), not pgcli. Just put dsn into single quotes, and it will work.

You're completely right. I figured that out right after opening the issue. Hence I closed it right away.

**Comment by blandonfrank** [comment]
Also, it turns out that I was escaping it incorrectly.  Using "\" to escape it works just fine. Not sure why it didn't work for me at first.
`pgcli postgres://tester:test123\!@localhost:5432/test`

Anyway, this is a non-issue.

**Comment by j-bennet** [comment]
Thanks, good to know!
