### ISSUE TITLE
Decode error for non-ASCII of certain types in expanded mode

### ISSUE THREAD

**Issue by koljonen** [dbcli/pgcli#651]
I've tried to debug this but haven't really gotten anywhere, so I'm hoping someone else has a better understanding of these things. It crashes in [expanded.py](https://github.com/dbcli/pgcli/blob/2fb030b72ac4cf1cfe8e1d6a875fb8393b82674e/pgcli/packages/expanded.py#L16) in the call to `_text_type()`.
```
vagrant@vagrant:vagrant> \x on; select 'ö'::tsvector
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```
```
vagrant@vagrant:vagrant> \x on; select 'ö'::tsquery
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

This is on Python 2.7.12 on Mac OS, on the latest master of pgcli.

**Comment by amjith** [comment]
I'm on it.
