### ISSUE TITLE
port shouldn't be required for DSN's in alias_dsn section

### ISSUE THREAD

**Issue by msztolcman** [dbcli/pgcli#657]
Currently dsn in form:

    somename = postgresql://postgres:password@host/eden

is invalid, after running pgcli `pgcli -D somename` it prints:

    invalid port number: "None"

It should be required (wasn't in previous versions). I didn't verified other fields.

**Comment by j-bennet** [comment]
Looks like this is also caused by latest psycopg2. See if this fixes it:

`pip install psycopg2==2.6.2`

**Comment by j-bennet** [comment]
Aha. Found it. https://github.com/psycopg/psycopg2/issues/524

**Comment by msztolcman** [comment]
Yep, after downgrading psycopg it's better now, thanks :)

**Comment by amjith** [comment]
Sigh. We should fix this. ☹️

**Comment by j-bennet** [comment]
Fixed in 1.5.1.
