### ISSUE TITLE
pset command missing

### ISSUE THREAD

**Issue by jontsai** [dbcli/pgcli#662]
`\pset format wrapped` works on `psql` but not `pgcli`

**Comment by amjith** [comment]
@jontsai You're right we don't yet support that. In fact the only `\pset` that is supported is pager. 

There are a couple of problems with the wrapped mode. First, we need to rewrite the output with newlines based on the terminal size, which sounds a bit complicated. Second, the tabulate library that we're using doesn't support multi-line values, so even if we manage to achieve the first goal the table will render really weird. 

So this is a hard problem but not impossible. I'm currently working on replacing our tabulate library with one that does support multi-line values. Once that is done we'll revisit the idea of auto-wrapping. I hope that gives you an idea of where the priorities are right now.

**Comment by benjamin-demarteau** [comment]
I'd like to add that the `\pset pager` that's supposedly supported does not have the expected behavior (setting paging to `on`, `off` or `always`). Instead, it tries to set the pager program to invoke.
