### ISSUE TITLE
,

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#672]
## Your environment

- [ ] Please provide your OS and version information.
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

**Comment by jose2190** [comment]
- MacOS 10.12.3
- Version: 1.5.1
- `pip freeze output`:
-- appdirs==1.4.3
-- click==6.7
-- configobj==5.0.6
-- humanize==0.5.1
-- packaging==16.8
-- pgcli==1.5.1
-- pgspecial==1.7.0
-- prompt-toolkit==1.0.13
-- psycopg2==2.7.1
-- Pygments==2.2.0
-- pyparsing==2.2.0
-- setproctitle==1.1.10
-- six==1.10.0
-- sqlparse==0.2.3
-- wcwidth==0.1.7

**Comment by amjith** [comment]
@jose2190 I think you forgot to describe your issue. LOL. 

You wanna tell us what problem you're having?

**Comment by amjith** [comment]
I'm confused by this issue. It says I created it but I don't remember creating it and there is a comment by @jose2190.

**Comment by jose2190** [comment]
Hahaha, i was think you opened this question for data analysis or something else.
I don't have any problem, pgcli is awesome!

**Comment by amjith** [comment]
Haha. My bad. I'll close this issue. 

> I don't have any problem, pgcli is awesome!

Awww. Pgcli has the best users ever. 😃
