### ISSUE TITLE
GNOME Terminal Colors

### ISSUE THREAD

**Issue by zafer06** [dbcli/pgcli#682]
## Description
Hi, Thank you for this project. How do I change the color of the green, gray and red text? Gnome terminal appearance is below.

![pgcli-screen](https://cloud.githubusercontent.com/assets/1070077/24992287/3ce5502e-2029-11e7-93e9-df770dd24570.png)

## My environment

- Linux Mint 18.1 Cinnamon x64
- GNOME Terminal 3.18.3
- PostgresSQL 9.6.1

**Comment by j-bennet** [comment]
Syntax coloring is done by Pigments library. The highlight colors depend on the style you specify in `pgclirc`:

https://github.com/dbcli/pgcli/blob/e5d3d5d63f404df4478de6201a36bf380cdb4b1f/pgcli/pgclirc#L86-L89

**Comment by amjith** [comment]
The config file is located in `~/.config/pgcli/config`. 

If you'd like to see a preview of various themes, check out: http://mycli.net/syntax

**Comment by zafer06** [comment]
Thanks @j-bennet  and @amjith. This color themes are very good.
