### ISSUE TITLE
Missing dependency when upgrading through Homebrew

### ISSUE THREAD

**Issue by bl-nero** [dbcli/pgcli#690]
## Description
I'm trying to run `brew upgrade pgcli`, but I'm getting a following error: `Error: No available formula with the name "postgresql93" (dependency of pgcli)`

## Your environment
OS X El Capitan 10.11.6
pgcli version 1.0.0
postgresql: stable 9.6.2 (bottled), HEAD (installed via Homebrew)
pip freeze:
```
appdirs==1.4.3
asn1crypto==0.22.0
backports.functools-lru-cache==1.2.1
boto==2.38.0
cffi==1.10.0
cryptography==1.8.1
datadog==0.13.0
decorator==4.0.10
enum34==1.1.6
Fabric==1.13.1
flake8==2.5.1
futures==3.0.5
gitpath==0.2
idna==2.5
ipaddress==1.0.18
mccabe==0.3.1
mercurial==3.7.3
msgpack-python==0.4.7
packaging==16.8
paramiko==2.1.2
pbr==1.10.0
pep8==1.7.0
powerline-status==2.3
psycopg2==2.7.1
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pyflakes==1.0.0
pyparsing==2.2.0
python-dateutil==2.5.3
readline==6.2.4.1
requests==2.11.1
shopspring==0.1
simplejson==3.8.2
six==1.10.0
stevedore==1.18.0
trollius==2.1
vboxapi==1.0
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
```

**Comment by j-bennet** [comment]
@bl-nero Did you try `brew update`?

Also, please be aware of this: https://github.com/dbcli/pgcli/issues/718.

It is not fixed yet. Until we fix it, I would advise to `pip install pgcli`, instead of using the brew formula.

Sorry about the inconvenience.

**Comment by j-bennet** [comment]
We have now switched to hosting our own brew formula (courtesy of @tsroten, hosted at https://github.com/dbcli/homebrew-tap). The new formula will not try to install or update postgresql if you already have it. This is how you would install pgcli using our repo, instead of the default homebrew repo:

`brew tap-pin dbcli/tap && brew install pgcli`

Hope this helps.
