### ISSUE TITLE
document named query parameters

### ISSUE THREAD

**Issue by bobcolner** [dbcli/pgcli#704]
## Description
I'm trying to use named query bind parameters. I can't find any documentation on the correct syntax to use in my query to define a parameter.

**Comment by bobcolner** [comment]
I have tried parameterizing my query with the common syntax `{{variable}}`. 

This does not seem to be the correct syntax. Does anyone know the correct syntax?

**Comment by msztolcman** [comment]
Did you mean:

`mysz@(none):mysz> \ns test select %s, %s
Saved.
Time: 0.001s
mysz@(none):mysz> \n test 1 2
> select %s, %s
+------------+------------+
| ?column?   | ?column?   |
|------------+------------|
| 1          | 2          |
+------------+------------+
SELECT 1
Time: 0.001s
`

**Comment by bobcolner** [comment]
Yes, this is what I was looking for. Thank you.

I will try to find a place to document this nice feature.

**Comment by michaeljones** [comment]
I've been struggling with this. I've been unable to find clear reference on creating them or using parameters. I have a situation where I'd like to repeat one parameter in the query but '%s' doesn't support that so I have to write the argument twice. Not the end of the world but it would be nice to work around it.

But then I wanted the parameter substituted inside a json blob and then single quotes  added around the parameter cause problems. 

This is what I was trying to do:
```
addPermission = '''update users set privs = jsonb_set(privs::jsonb, array['%s'], (privs->'%s')::jsonb || '["%s"]'::jsonb) where email = '%s';'''
```
It would be nice to call it with:
```
\n addPermission section myPermission email@example.com
```
Perhaps someone will be able to help me.

I don't want to complain though. I love love love this project. Such a nice user experience especially for someone like me that is unfamiliar with SQL.
