### ISSUE TITLE
unexpected /copy syntax error

### ISSUE THREAD

**Issue by bobcolner** [dbcli/pgcli#705]
## Description
When using the `/copy` command as documented I get a syntax error.

```
> \copy myschema.mytable to './out.csv'
syntax error at or near "STDOUT"
LINE 1: copy myschema.mytable to  STDOUT
                                 ^
Time: 0.097s
```

```
> \copy (select 1) to stdout
syntax error at or near "("
LINE 1: copy (select 1) to  STDOUT
             ^

Time: 0.096s

```

## Your environment
macOS, python3.6, redshift pgcli Version: 1.5.1

**Comment by j-bennet** [comment]
I'll see if I can reproduce this, but in the meantime, your pgcli version is pretty old. Are you able to update it to the latest release?

`pip install -U pgcli`

**Comment by j-bennet** [comment]
I'll see if I can reproduce this.

**Comment by j-bennet** [comment]
I never used redshift before, but from what I see, it is based on postgresql 8.0.2. That version of postgresql allows copying table -> file (or table -> stdout), but not query -> file (or query -> stdout). Documentation for 8.0:

https://www.postgresql.org/docs/8.0/static/sql-copy.html

Vs current:

https://www.postgresql.org/docs/current/static/sql-copy.html

I tried connecting to an 8.0.2 database (in docker) using `psql`. Here is what I get:

```
docker=> \copy abc to stdout;
1	a
2	b
3	c
docker=> \copy abc to 'aaa.txt';
COPY
docker=> copy (select 1) to stdout;
ERROR:  syntax error at or near "("
LINE 1: copy (select 1) to stdout;
             ^
docker=>
```

If I use `pgcli`, I get exactly the same result:

```
docker@127.0.0.1:docker> \copy abc to 'aaa.txt'

Time: 0.002s
docker@127.0.0.1:docker> \copy abc to stdout
1	a
2	b
3	c

Time: 0.001s
docker@127.0.0.1:docker> \copy (select 1) to stdout
syntax error at or near "("
LINE 1: copy (select 1) to  STDOUT
             ^

Time: 0.003s
docker@127.0.0.1:docker>
```

`abc` is the name of my test table.

**Comment by bobcolner** [comment]
This is redshift limitation and not an pgcli bug. I also confirmed that the `\copy` does not with with redshift when using the `psql` client either.
