### ISSUE TITLE
alias_dns not loading from custom PGCLIRC

### ISSUE THREAD

**Issue by OmeGak** [dbcli/pgcli#717]
## Description

I'm loading the config specifying `PGCLIRC` in the environment. The DNS aliases defined in the custom location pgclirc are ignored and loaded from the standard location pgclirc instead (`~/.config/pgcli/config`). Other config options like `multi_line` are successfully loaded from custom location pgclirc. The same thing happens when specifying pgclirc from CLI options.

## Your environment

```console
$ uname -v
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
```

```console
$ pgcli --version
Version: 1.5.1
```

```
$ pip freeze
pipg freeze
alabaster==0.7.6
appnope==0.1.0
argcomplete==0.8.9
Babel==1.3
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
blindspin==2.0.0
certifi==2015.4.28
click==6.7
click-completion==0.2.1
colorama==0.3.7
configparser==3.5.0
crayons==0.1.2
cycler==0.10.0
decorator==4.0.10
delegator.py==0.0.8
docutils==0.12
enum34==1.1.6
filemagic==1.6
flake==0.1.9
flake8==3.2.1
flake8-docstrings==1.0.2
functools32==3.2.3.post1
gnureadline==6.3.3
httpie==0.9.4
icalendar==3.0
ipykernel==4.2.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==4.1.1
jedi==0.9.0
Jinja2==2.7.3
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.1.1
jupyter-console==4.0.3
jupyter-core==4.0.6
kaptan==0.5.8
libtmux==0.6.3
log-colorizer==1.6
Mako==1.0.6
MarkupSafe==0.23
matplotlib==1.5.1
mccabe==0.5.2
mistune==0.7.1
nbconvert==4.1.0
nbformat==4.0.1
nodeenv==0.13.3
nose==1.3.7
notebook==4.0.6
numpy==1.11.0
numpydoc==0.5
parse==1.6.6
path.py==8.1.2
pathlib==1.0.1
pathlib2==2.1.0
pbr==3.0.0
pep8==1.5.7
pew==0.1.26
pexpect==4.2.1
pickleshare==0.7.4
Pillow==3.4.2
pipenv==3.3.6
pipfile==0.0.1
pojson==0.3
powerline-status==2.3
prompt-toolkit==1.0.9
protobuf==3.2.0
psutil==3.0.1
ptyprocess==0.5.1
pyatom==1.4
pycodestyle==2.2.0
pydocstyle==1.1.1
pyflakes==1.3.0
Pygments==2.1.3
pync==1.6.1
pyparsing==2.1.1
pyPdf==1.13
python-dateutil==2.5.0
pythonz-bd==1.11.4
pytz==2015.4
PyYAML==3.12
pyzmq==14.7.0
qtconsole==4.1.1
requests==2.10.0
requirements-parser==0.1.0
shutilwhich==1.1.0
simplegeneric==0.8.1
simplejson==3.10.0
six==1.10.0
snowballstemmer==1.2.0
Sphinx==1.3.1
sphinx-rtd-theme==0.1.8
stevedore==1.21.0
terminado==0.5
tmuxp==1.2.6
toml==0.9.2
tornado==4.2
tornado-systemd==1.0.1
traitlets==4.3.1
virtualenv==15.1.0
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.2
wcwidth==0.1.7
wdb==2.1.2
wdb.server==2.1.2
xkcdpass==1.9.5
zc.queue==2.0.0a1
```

**Comment by j-bennet** [comment]
@OmeGak `pgcli` reads one standard config file and one custom config file. It looks for the custom file in two locations, in this order of preference:

* location specified in `--pgclirc` file. 
* location specifies in `PGCLIRC` environment variable

So you can use either `PGCLIRC` environment variable or `--pgclirc` option to specify the custom configuration file location, but not both of them. If both are specified, `--pgclirc` will be used.

**Comment by OmeGak** [comment]
@j-bennet, maybe I explained myself wrong.

I have a custom `pgclirc` file that gets successfully loaded by specifying it in `PGCLIRC` env var. I know it is loaded because I can see the configuration options (`multi_line`, for instance) being reflected when I invoke `pgcli`.

Now, when I specify DNS aliases in my custom config file, they are completely ignored.

```ini
[alias_dsn]
docker = postgresql://postgres@localhost:15432
```

```console
$ pgcli -D docker
Invalid DSNs found in the config file. Please check the "[alias_dsn]" section in pgclirc.
```

Conversely, if I specify the same DNS alias in the standard config file `~/.config/pgcli/config`:

```console
$ pgcli -D docker
Version: 1.5.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
postgres@localhost:postgres>
```

I don't know if I'm doing anything wrong, but it looks like a bug to me.

**Comment by j-bennet** [comment]
@OmeGak Got it, thanks for the clarification. I'll look into it.

**Comment by j-bennet** [comment]
This was fixed in master and will be available in the next release.

To install pgcli from master:

`pip install -U https://github.com/dbcli/pgcli/archive/master.zip`

**Comment by OmeGak** [comment]
Great, thanks!
