### ISSUE TITLE
PostgreSQL update during pgcli installation via Homebrew

### ISSUE THREAD

**Issue by pboschmann** [dbcli/pgcli#718]
## Description
Hi there,

I discovered pgcli yesterday and gave it a shot (like it so far).
I installed it via Homberew and unfortunately it seems that Homebrew also updated Postgres during the installation process. I can not start the Postgres server with my existing database files anymore. PostgreSQL server log says:
```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.4, which is not compatible with this version 9.6.3.
```
I've checked my ``/usr/local/bin`` directory - the timestamps of the pgcli and postgres symlinks are equal, whereas Python related symlinks and all of my other Homebrew installed programs are of an older date.
Could it be, that there is a bug in the Homebrew formula and Postgres will be always installed in bundle with pgcli? I couldn't find the formula for pgcli in this repository and don't have time ATM to investigate further.

## Your environment
macOS 10.12.4
pgcli 1.5.1
PostgreSQL 9.4 yesterday, and 9.6.3 today 🙈 
pip freeze says:
```
backports-abc==0.4
certifi==2016.8.31
click==6.6
Jinja2==2.8
livereload==2.4.1
Markdown==2.6.6
MarkupSafe==0.23
mkdocs==0.15.3
mkdocs-bootstrap==0.1.1
mkdocs-bootswatch==0.4.0
PyYAML==3.12
singledispatch==3.4.0.3
six==1.10.0
tornado==4.4.1
vboxapi==1.0
wheel==0.26.0
```

**Comment by j-bennet** [comment]
`pgcli` brew formula [specifies postgresql as a dependency](https://github.com/Homebrew/homebrew-core/blob/master/Formula/pgcli.rb#L16), but without attaching to any particular version. I'm not sure if that is the source of the problem; have to look into it.

**Comment by j-bennet** [comment]
So for `pgcli` in the brew formula, we specify `python`, `openssl` and `postgresql` as dependencies. For `mycli`, we only specify `python` and `openssl`. Looks like we could safely leave out `postgresql` from `pgcli` formula.

**Comment by j-bennet** [comment]
Some context from @amjith:

> So the reason for having postgresql as a dependency is because otherwise the formula won’t pass in their pull request tests. You’re welcome to remove it and give it a shot. Things have changed with homebrew since I originally created that formula.
> mycli uses pymysql which is a pure python implementation of the mysql driver. So we don’t need mysql installed on the system. But pgcli uses psycopg2 which uses libpq which is a C-binding for postgresql driver. That libpq is only installed if it has postgresql on that system.

**Comment by j-bennet** [comment]
I tried removing `postgresql` from formula completely, but that does not work, fails on `brew install --build-from-source pgcli`. So instead, I specified postgresql as dependency that has to be present at runtime: https://github.com/Homebrew/homebrew-core/pull/13659. This seem to have the desired effect of homebrew not updating the existing installation.

**Comment by pboschmann** [comment]
Wow, didn't expect the fix so fast. Thank you very much.
Should I try to reproduce the mentioned behavior later when a new version of PostgreSQL is released? Do you wish any feedback for it?

**Comment by j-bennet** [comment]
@pboschmann Yes, it would be great to hear about your experience after the formula is merged. Thank you!

**Comment by j-bennet** [comment]
Attempt #2: https://github.com/Homebrew/homebrew-core/pull/14004.

**Comment by j-bennet** [comment]
@pboschmann Did you use `brew install --build-from-source pgcli`, or `brew install pgcli`? Supposedly, the latter should not have updated your postgresql.

**Comment by pboschmann** [comment]
My zsh history says it was `brew install pgcli` I've used.
I have an another machine with Postgres 9.4 installed. If you wish: I could try to reproduce (in a couple of hours) the behavior by executing `brew install pgcli` on it.

**Comment by j-bennet** [comment]
No need, thanks! I already verified that the update is happening when you run `brew install pgcli`.

**Comment by j-bennet** [comment]
So after an unproductive back and forth with the Homebrew developers, we switched to hosting our own brew formula (courtesy of @tsroten, hosted at https://github.com/dbcli/homebrew-tap). This is how you would install pgcli using our repo, instead of the default homebrew repo:

```
brew tap-pin dbcli/tap && brew install pgcli
```

Hope this helps.

**Comment by lifeiscontent** [comment]
@j-bennet the tap doesn't work for me.

```
Error: No available tap dbcli/tap.
```

**Comment by tsroten** [comment]
@lifeiscontent It's possible you have to do a `brew update` first.

**Comment by pboschmann** [comment]
@lifeiscontent 
Works for me if I run `brew update` and tap the formula repo first:
`brew tap dbcli/tap && brew tap-pin dbcli/tap && brew install pgcli`

@j-bennet @tsroten 
This also installed pgcli 1.5.1 on a machine with Postgres 9.4.5 **without** updating Postgres itself.
Thank you very much for your effort and have a nice week. :)

**Comment by j-bennet** [comment]
Perfect! Thanks for the feedback!

**Comment by j-bennet** [comment]
The homebrew developers updated `pgcli` formula in homebrew-core to not depend on postgresql anymore (see https://github.com/Homebrew/homebrew-core/pull/15725 - thanks to @ilovezfs). This removes the need for us to host our own formula. `pgcli` can now be installed from `homebrew-core`.

cc @tsroten @amjith

**Comment by amjith** [comment]
Let's update the readme and the website.

**Comment by ilovezfs** [comment]
@j-bennet just saw this now. You're welcome! :) And thanks for updating the readme.

If at least one more formula needs just `libpq`, we may even make `libpq` its own formula.

**Comment by ruth09** [comment]
Thanks @pboschmann  it just worked for me ! i was facing the same error but lucky i found the solution. Thanks once again.
