### ISSUE TITLE
Reopen lowercase autocompletion issue #569

### ISSUE THREAD

**Issue by darthunix** [dbcli/pgcli#720]
Hi!
I am using pgcli 1.5.1 on ubuntu trusty from pip and still lowercase autocompletion doesn't work for me. 
I found that this problem seems to be fixed in issue #569 but it still doesn't work for me.
```
s<tab>SELECT
S<tab>SELECT
```
Was this issue really implemented? Or may be I am doing something wrong?

**Comment by darthunix** [comment]
it was easy... keyword_casing = auto in pgclirc solved my problem

**Comment by j-bennet** [comment]
👍
