### ISSUE TITLE
Running queries from vim

### ISSUE THREAD

**Issue by cazgp** [dbcli/pgcli#736]
## Description
I often write a query, run it, check the results, then type "\e" to repeat.
If it all possible, is there a command one could run that would send the text to SQL, output it in the pager, and then "q" to take you back into vim?

## Your environment

- [X] Please provide your OS and version information.
Linux lubuntu 16.04

- [x] Please provide your CLI version.
1.5.1

- [x] What is the output of ``pip freeze`` command.
```
chardet==2.3.0
click==6.7
colorama==0.3.9
command-not-found==0.3
defer==1.0.6
distro-info===0.14build1
docopt==0.6.2
feedparser==5.2.1
gitsome==0.7.2
greenlet==0.4.11
language-selector==0.1
lightdm-gtk-greeter-settings==1.2.1
lxml==3.6.4
Mako==1.0.4
MarkupSafe==0.23
msgpack-python==0.4.8
neovim==0.1.12
numpydoc==0.6.0
pexpect==4.2.0
Pillow==3.3.1
ply==3.10
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.22.0
python-apt==1.1.0b5
python-debian==0.1.29
pytz==2016.10
pyxdg==0.25
PyYAML==3.11
reportlab==3.3.0
requests==2.10.0
six==1.10.0
ssh-import-id==5.6
ubuntu-drivers-common==0.0.0
ufw==0.35
uritemplate==3.0.0
uritemplate.py==3.0.2
urllib3==1.15.1
usb-creator==0.3.3
wcwidth==0.1.7
xkit==0.0.0
```

**Comment by meeuw** [comment]
Instead of using vim to edit your queries you can set pgcli in VI command mode?

Else I'd suggest you use a VIM plugin to execute queries.

**Comment by tsroten** [comment]
dbext is a great VIM plugin for this: https://mutelight.org/dbext-the-last-sql-client-youll-ever-need

**Comment by cazgp** [comment]
dbext + pgcli is delightful. Thank you for the suggestion.
