### ISSUE TITLE
pgcli 1.6.0 crashes saying it requires pgcli 1.5.1

### ISSUE THREAD

**Issue by serge1peshcoff** [dbcli/pgcli#737]
I've recently upgraded from Debian to Debian 9 and suddenly pgcli stopped working. I tried to reinstall it, reinstall pip3, delete and reinstall all packages, but in all cases it resulted in the same error:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
        ws.require(__requires__)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 963, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 854, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (pgcli 1.6.0 (/home/webuser/.local/lib/python3.5/site-packages), Requirement.parse('pgcli==1.5.1'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/pgcli", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
        working_set = WorkingSet._build_master()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 657, in _build_master
        return cls._build_from_requirements(__requires__)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 670, in _build_from_requirements
        dists = ws.resolve(reqs, Environment())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 849, in resolve
        raise DistributionNotFound(req, requirers)
    pkg_resources.DistributionNotFound: The 'pgcli==1.5.1' distribution was not found and is required by the application

(this error occurs whatever CLI args are specified).

Debian 9 x64, python3 version 3.5.3, pgcli version 1.6.0

`pip3 freeze` output:

    chardet==2.3.0
    click==6.7
    colorama==0.3.7
    configobj==5.0.6
    cryptography==1.7.1
    distlib==0.2.4
    html5lib==0.999999999
    httplib2==0.9.2
    humanize==0.5.1
    idna==2.2
    iotop==0.6
    keyring==10.1
    keyrings.alt==1.3
    pgcli==1.6.0
    pgspecial==1.8.0
    prompt-toolkit==1.0.14
    psycopg2==2.7.1
    pyasn1==0.1.9
    pycrypto==2.6.1
    pycurl==7.43.0
    Pygments==2.2.0
    pygobject==3.22.0
    python-apt==1.4.0b3
    python-debian==0.1.30
    python-debianbts==2.6.1
    pyxdg==0.25
    reportbug==7.1.7
    requests==2.12.4
    SecretStorage==2.3.1
    setproctitle==1.1.10
    six==1.10.0
    sqlparse==0.2.3
    unattended-upgrades==0.1
    urllib3==1.19.1
    wcwidth==0.1.7
    webencodings==0.5

It probably has something to do with my environment, as it was working before the upgrade, but still, can somebody tell me what's going on and why it won't run?

**Comment by amjith** [comment]
@serge1peshcoff Sorry about the trouble. 

Did you install pgcli previously using apt-get? 

Here are some methods to verify. First uninstall pgcli that was installed using pip. 

`pip uninstall pgcli`

Then check if pgcli is installed: 

```
which pgcli
```

Check to make sure it is absolutely not installed on your system: 

```
locate pgcli
```

If is it is installed via apt-get you can remove it using `sudo apt-get remove pgcli`. 

Once you've thoroughly cleansed your system of all traces of pgcli, you can try again to install pgcli using pip. 

```
pip3 install pgcli
```

I hope that helps.

**Comment by serge1peshcoff** [comment]
@amjith yep, that totally worked! Apparently I had some stuff left from python-3.4 (there was the pgcli folder in python3.4 folder), while I was using python-3.5. I've removed it and everything is working now.
Thanks for help!
