### ISSUE TITLE
Can't run on Cygwin

### ISSUE THREAD

**Issue by Wirone** [dbcli/pgcli#745]
## Description

I've been struggling with installation of `pgcli` because it was failing on building wheel for `psycopg2`. After environment fixes (`pg_config`) I've managed to install it.

However, when I want to run pgcli I get:

```
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 7, in <module>
    from pgcli.main import cli
  File "/usr/lib/python3.6/site-packages/pgcli/main.py", line 39, in <module>
    from pgspecial.main import (PGSpecial, NO_QUERY, content_exceeds_width)
  File "/usr/lib/python3.6/site-packages/pgspecial/__init__.py", line 12, in <module>
    from . import iocommands
  File "/usr/lib/python3.6/site-packages/pgspecial/iocommands.py", line 9, in <module>
    import psycopg2
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: No such file or directory
```

There is `_psycopg.cpython-36m-x86_64-cygwin.dll` under `/usr/lib/python3.6/site-packages/psycopg2`

## Your environment
Windows 7
Cygwin 2.8.2(0.313/5/3)

`pip freeze` output:
```
ansible==2.2.2.0
appdirs==1.4.3
asn1crypto==0.22.0
cffi==1.9.1
chardet==2.3.0
click==6.7
configobj==5.0.6
cryptography==1.8.1
docutils==0.13.1
humanize==0.5.1
idna==2.5
Jinja2==2.9.6
lockfile==0.12.2
lxml==3.7.3
MarkupSafe==1.0
packaging==16.8
paramiko==2.1.2
pgcli==1.6.0
pgspecial==1.8.0
Pillow==4.1.1
ply==3.9
prompt-toolkit==1.0.14
psycopg2==2.7.1
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
Pygments==2.2.0
pyOpenSSL==16.2.0
pyparsing==2.1.10
PyYAML==3.12
requests==2.13.0
six==1.10.0
sqlparse==0.2.3
urllib3==1.20
wcwidth==0.1.7
```

**Comment by fpietka** [comment]
Although it is problematic, I'm not entirely sure it is related to pgcli.

Can you try and see what happen if you try to run `import psycopg2` right out of a python shell?

**Comment by Wirone** [comment]
```
-> % python
Python 3.6.1 (default, Mar 21 2017, 21:49:16)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: No such file or directory
```

Probably it's more `psycopg2` error, but I thought someone could help me with getting `pgcli` running..

**Comment by fpietka** [comment]
I could test to install it on Windows if I can get my hands on one (having Windows 10 ATM, although I do not dev on it), but your issue seems related to psycopg2 itself. 

I did run a search on their github, but couldn't find anything related to your issue, but I think they will be more skilled than me to handle this.

Anyway, if I can manage to test it on Win7 + 3.6.1 I'll let you know if I have the same issue.

**Comment by amjith** [comment]
@Wirone I have sent this http://www.stickpeople.com/projects/python/win-psycopg/ to the users to try in the past.

**Comment by Wirone** [comment]
FYI I no longer develop on Windows, so I won't be helpful on this anymore. Feel free to close it.

**Comment by j-bennet** [comment]
Closing. We can always reopen this if someone else is affected.
