### ISSUE TITLE
Win10 / Git Bash / winpty - Several "graphical" issues

### ISSUE THREAD

**Issue by JaschaK** [dbcli/pgcli#752]
Hi,

## Description

I am running pgcli in Windows 10 within Git Bash (specifications and versions below).
I am having some - what I call - graphical issues. They seem to appear when I type SQL code and use the auto completion then some parts of the completion just freeze in the screen and only disappear when I press the return key. Here are some snap shots:

![image](https://user-images.githubusercontent.com/4294168/28338188-71a7e6e8-6c08-11e7-8ccc-f59270294ec0.png)
In this image you can see the cursor next to the word 'public' which is actually where he is althoug he should be one line above including the word 'public'. The "information_schema.[...]" was left from auto completion although I did not choose it as well as the teal background color.

![image](https://user-images.githubusercontent.com/4294168/28338312-d62ff3e4-6c08-11e7-8031-712ccc8fffd8.png)
Here is another issue. The "round()" from the autocompletion was left after I chose "count(*)" and it did not disappear.

I can attach further issues if I stumble upon some.

Best regards
Jascha

## Your environment

- Windows 10 Education Version 1607 Build 14393.1480
- pgcli version 1.7.0 within Git Bash using winpty
- Python Version 3.6.1 / winpty version 0.2.2-dev
- pip freeze output:
backports.csv==1.0.5
cli-helpers==0.2.2
click==6.7
configobj==5.0.6
h5py==2.7.0
humanize==0.5.1
numpy==1.13.0
pgcli==1.7.0
pgspecial==1.8.0
prompt-toolkit==1.0.14
psycopg2==2.7.1
Pygments==2.2.0
six==1.10.0
sqlparse==0.2.3
terminaltables==3.1.0
wcwidth==0.1.7

**Comment by amjith** [comment]
That's really odd. 

@JaschaK What terminal program do you use? Is it cmd.exe or [cmder](http://cmder.net/)? 

@darikg  or @jonathanslenders Either of you have any thoughts on this issue?

**Comment by JaschaK** [comment]
I'm using Git Bash from git-scm.com .
I just updated to Version 2.13.3 from 2.7.1 and it seems that by that the problem was solved. I just tried it a little and there where no further immediate issues. If it happens again I will reopen this Issue again.
