### ISSUE TITLE
Completion for polymorphic functions

### ISSUE THREAD

**Issue by qdw** [dbcli/pgcli#753]
## Description

In psql, sometimes I want to edit a function by name using `\ef`, or I want to DROP it, but this is laborious because there are multiple functions with that name.

In pgcli, it would be nice to have an autocomplete list showing each "version" of the function with its type signature. It would be even nicer if I could type, for instance, `my_function(text` and then hit tab to get a list of the subset of type signatures for which the first argument is of type TEXT.

In order for this to work with `\ef` issue #754 would need to be implemented first. But even before that, this would be useful for DROP.

**Comment by koljonen** [comment]
See PR https://github.com/dbcli/pgcli/pull/677
