### ISSUE TITLE
Add support for psql-style \ef

### ISSUE THREAD

**Issue by qdw** [dbcli/pgcli#754]
### Desired behavior

In psql, `\ef my function_name` opens the definition of a function in your text editor, allowing you to change function definitions easily. `\ef` with no function name opens a text editor session pre-populated with a function skeleton for convenience. I think it would be nice to implement both behaviors in pgcli.

### Compatibility note

pgcli too has an `\ef` command, but it appears to be equivalent to pgcli's `\e` (which is substantially like psql's `\e`). So I think it would be good to replace pglcli's current `\ef` behavior with the desired behavior described above, although this would mean an incompatible UI change.

**Comment by j-bennet** [comment]
Handling `\ef` and `\ev` as `\e` was actually a bug just fixed in https://github.com/dbcli/pgspecial/pull/44 (thanks to @fpietka).
