### ISSUE TITLE
Prompt hostname when using `service=`

### ISSUE THREAD

**Issue by cazgp** [dbcli/pgcli#765]
## Description
When connecting with `pgcli` "normally", i.e. `pgcli -h hostname...`, upon connection the prompt usually shows the hostname:app which is extremely useful given that I'm often connected to multiple production databases.

However, when using `service=servicename` with the same details, the prompt instead shows IP address:database. This makes it very difficult to see at a glance which database I'm connected to.

Is there any config that I'm missing or is that the nature of using service to connect -- the hostname information is lost?

## Your environment

- [x] Ubuntu 16.10
- [x] 1.7.0
- [x] What is the output of ``pip freeze`` command.
chardet==2.3.0
click==6.7
colorama==0.3.9
command-not-found==0.3
defer==1.0.6
distro-info===0.14build1
docopt==0.6.2
feedparser==5.2.1
gitsome==0.7.2
greenlet==0.4.12
language-selector==0.1
lightdm-gtk-greeter-settings==1.2.1
lxml==3.6.4
Mako==1.0.4
MarkupSafe==0.23
msgpack-python==0.4.8
neovim==0.1.13
numpydoc==0.6.0
pexpect==4.2.0
Pillow==3.3.1
ply==3.10
prompt-toolkit==1.0.14
ptyprocess==0.5.1
pycups==1.9.73
Pygments==2.2.0
pygobject==3.22.0
python-apt==1.1.0b5
python-debian==0.1.29
pytz==2016.10
pyxdg==0.25
PyYAML==3.11
reportlab==3.3.0
requests==2.10.0
six==1.10.0
ssh-import-id==5.6
ubuntu-drivers-common==0.0.0
ufw==0.35
uritemplate==3.0.0
uritemplate.py==3.0.2
urllib3==1.15.1
usb-creator==0.3.3
wcwidth==0.1.7
xkit==0.0.0

**Comment by fpietka** [comment]
The way we were getting the host (amongst other things) made that we lost the hostname, and only could get the IP.

I made a little patch that is fixing that.

**Comment by cazgp** [comment]
Thanks!
