### ISSUE TITLE
Is there a way to ctrl+p in vim mode?

### ISSUE THREAD

**Issue by cazgp** [dbcli/pgcli#768]
Have recently switched to vi-mode (on dev from a few days ago) and pressing ctrl+p doesn't bring up the previous history like it does in emacs mode. Is there a config setting to bring back that behaviour? esc+k just isn't quite the same muscle memory!

**Comment by meeuw** [comment]
Hmm, this is how vim works, it isn't implemented yet but vim supports `ctrl`-`o` `k` as a single shot command key in insert mode, would that match your muscle memory?

**Comment by amjith** [comment]
@cazgp Looks like C-P brings up the previous history if you're in the normal mode. Are you asking if there is a way to do that in the insert mode?

**Comment by cazgp** [comment]
Yes. When pgcli loads it loads straight into insert mode. I then type Ctrl+p and only USE appears in a pop-up, which is a tad annoying. No worries if it can't be done, I was just wondering! Thank you :)
