### ISSUE TITLE
Request: add support for \pset null?

### ISSUE THREAD

**Issue by jdsutherland** [dbcli/pgcli#778]
There's a [pgcasts episode](https://www.pgcasts.com/episodes/2/a-better-null-display-character/) about setting a more readable null display character using `\pset null 'Ø'`.

**Comparison:**
_pgcli_
```sql
+--------+--------+--------+--------+
| id     | name   | id     | name   |
|--------+--------+--------+--------|
| 1      | Pirate | 2      | Pirate |
| 2      | Monkey | <null> | <null> |
| 3      | Ninja  | 4      | Ninja  |
| 4      | Spaget | <null> | <null> |
| <null> | <null> | 3      | Dv     |
| <null> | <null> | 1      | Rut    |
+--------+--------+--------+--------+
```
_psql_
```sql
 id |  name  | id |  name
----+--------+----+--------
  1 | Pirate |  2 | Pirate
  2 | Monkey |  ø | ø
  3 | Ninja  |  4 | Ninja
  4 | Spaget |  ø | ø
  ø | ø      |  3 | Dv
  ø | ø      |  1 | Rut
```

It possible to add support to for this?

**Comment by tsroten** [comment]
Hi @jdsutherland! This is configurable via the pgcli config file. It doesn't appear to be documented in the config file (we'll get that fixed!). In your `~/.config/pgcli/config` file, add `null_string` to your `[main]` section:
```
[main]
null_string = 'ø'
```

I hope that helps!

**Comment by jdsutherland** [comment]
@tsroten, thanks for the response. After adding the above to the config, the output remains the same. I tried setting to other values such as `null_string = ""` and it remains the same.

Am I missing something?

**Comment by jdsutherland** [comment]
I found the problem. `null_string` is stored in config key value `data_formats` - not`main`
```python
self.null_string = c['data_formats'].get('null_string', '<null>')
```

I'll submit a PR.

**Comment by tsroten** [comment]
@jdsutherland I'm seeing it pulled from `main`:
https://github.com/dbcli/pgcli/blob/master/pgcli/main.py#L154

**Comment by jdsutherland** [comment]
@tsroten I think the way I wrote that was a bit confusing. The problem is that it's currently looking up `main` but the actual config dict should be `data_formats`: https://gist.github.com/anonymous/573f7d1f5f204f39dc506f6ee3605dbf#file-gistfile1-py-L22

**Comment by tsroten** [comment]
@jdsutherland It looks like you might have added `null_string` to the wrong spot in your config file. Could you double-check that you didn't add it beneath the section `[data_formats]`? It needs to be in the section `[main]`. The config file has multiple sections that are indicated by square brackets.

**Comment by jdsutherland** [comment]
@tsroten D'oh. Sorry about that.

**Comment by tsroten** [comment]
@jdsutherland No problem! Easy mistake to make 😄
