### ISSUE TITLE
Function autocomplete do not autocomplete database functions

### ISSUE THREAD

**Issue by fpietka** [dbcli/pgcli#783]
## Description
When using `\df`, autocomplete do not show database function (those displayed in the result of the command.

## Your environment
- OSX 10.12.5
- pgcli master

**Comment by j-bennet** [comment]
Not sure when this was fixed, but it's working in 1.10.3.

<img width="644" alt="pgcli-df" src="https://user-images.githubusercontent.com/637013/43346473-18935a50-91a6-11e8-953c-fc6b843ff8e0.png">
