### ISSUE TITLE
Command results in less in 1.7.0

### ISSUE THREAD

**Issue by azinoviev** [dbcli/pgcli#784]
## Description
Starting from 1.7.0 pgcli show results of every command in less (pager). Rolling back to 1.6.0 or earlier helps to get results "in place". It affects commands like "\l" and results of queries too.

## Your environment
macOS, pgcli 1.7.0, python 3.6.2

**Comment by j-bennet** [comment]
This happens because from 1.7.0, `pgcli` will not interfere with `LESS` environment variable unless it is set, and the default for `less` is not the best.

You may want to set it as follows:

```
$ export LESS="-XFR"
```

More about pager configuration:

https://www.mycli.net/pager

**Comment by azinoviev** [comment]
It helps! Thank you :)
