### ISSUE TITLE
Is there a way to use ENV variables for DSNs in the config file?

### ISSUE THREAD

**Issue by hahuang65** [dbcli/pgcli#787]
## Description
I would like to check in my pgclirc file, but do NOT want to keep sensitive DB URLs in the file.

Wondering if there's a way to support something like
```
[alias-dsn]
mydb = $MYDBURL
```

as opposed to having the actual URL in the config file.

**Comment by ddanieltan** [comment]
+1

**Comment by j-bennet** [comment]
We're using `configobj` module to parse config files, and it looks like it has no support for env variables. There's a feature request open, but I don't see it attempted:

https://github.com/DiffSK/configobj/issues/144

**Comment by hahuang65** [comment]
@j-bennet is there documentation on how to use this, as it's closed as completed?

**Comment by j-bennet** [comment]
@hahuang65 Sorry, just a part of the old issues cleanup. Not completed. We currently have no way of doing this.
