### ISSUE TITLE
Show help for -h option without any parameters

### ISSUE THREAD

**Issue by amjith** [dbcli/pgcli#789]
## Description

It is typical for command-line tools to show the help message when a `-h` is passed in. In pgcli we use the -h switch to pass in the host name. But if now argument is passed after the `-h` option it is a good chance that the user wants to see the help message. So it'll be nice to show the help message instead of presenting an error that says we need a hostname. 

The idea came from [Laura](https://twitter.com/codingcatgirl/status/908393026996797442) via Twitter.

**Comment by fpietka** [comment]
I checked this one a bit, but it seems we can't do this with click.
First I tried to customize help parameter (http://click.pocoo.org/5/documentation/#help-parameter-customization), but it got overloaded by our host parameter.
Then I thought about having an optional parameter for host, to fallback on help message, but it seems click can't do that: https://github.com/pallets/click/issues/528#issuecomment-192224795

**Comment by amjith** [comment]
You're right the limitations of click makes it extremely difficult to implement this. I'm going to close this since it's a nice to have feature.
