### ISSUE TITLE
Build constantly breaks on the same test case in end-to-end tests

### ISSUE THREAD

**Issue by j-bennet** [dbcli/pgcli#795]
pgcli build breaks on `tee` test case all the time:

https://github.com/dbcli/pgcli/blob/915ffb70a70a855bfc8cbc2d3b7ab9828e102775/tests/features/iocommands.feature#L10-L17

We need to figure out how to make that test better.

**Comment by meeuw** [comment]
Maybe we should raise all timeouts to 5 in:
https://github.com/dbcli/pgcli/blob/915ffb70a70a855bfc8cbc2d3b7ab9828e102775/tests/features/steps/iocommands.py

**Comment by j-bennet** [comment]
I haven't seen this one lately. Closing for now.
