### ISSUE TITLE
Autocomplete adds extra quotes to database name

### ISSUE THREAD

**Issue by lazycoder-ru** [dbcli/pgcli#799]
pgcli==1.8.1
Tryin to connect to database:
`\c "Kkar.Billing"`
and get this error:
`FATAL:  database ""Kkar.Billing"" does not exist`

And if I connect this way:
`\c Kkar.Billing`
there is no error

The problem is that database autocomplete adds quotes by default if db name contains mixed case.
![image](https://user-images.githubusercontent.com/6605234/31445033-f8048536-aea5-11e7-8c5c-b492ca89adac.png)

**Comment by amjith** [comment]
This is an oversight on our part. pgcli tries to be helpful by quoting mixed case table names and column names but we didn't think about database names. :disappointed: 

I'll see what I can do about this. Thanks for reporting the bug. :)

**Comment by lazycoder-ru** [comment]
It has appeared in 1.8.1, in 1.8.0 everything was fine.

**Comment by cfournie** [comment]
Fixed by #800
