### ISSUE TITLE
Upgrade cli_helpers dependency to 1.0.0

### ISSUE THREAD

**Issue by vmalloc** [dbcli/pgcli#804]
## Description
https://github.com/dbcli/cli_helpers/issues/25 breaks pip on some environments due to an incorrect `setup.py`. They released version 1.0.0 which fixes the issue...

**Comment by vmalloc** [comment]
Opened PR #803 to address it, but it fails CI. Not sure what to do about that...

**Comment by j-bennet** [comment]
(This was upgraded).
