### ISSUE TITLE
Can't start the app: "AssertionError: Passing an eventloop is required."

### ISSUE THREAD

**Issue by panovitch** [dbcli/pgcli#806]
## Description
On running pgcli -h <host_name> -p 5432 -U <user> -d <database> the app crashes with the following traceback:

```
Traceback (most recent call last):
  File "/usr/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.20.1', 'console_scripts', 'console')()
  File "/home/aleksey/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/aleksey/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/aleksey/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aleksey/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/share/pgcli/pgcli/main.py", line 595, in cli
    pgcli.run_cli()
  File "/usr/share/pgcli/pgcli/main.py", line 278, in run_cli
    self.cli = self._build_cli()
  File "/usr/share/pgcli/pgcli/main.py", line 408, in _build_cli
    cli = CommandLineInterface(application=application)
  File "/home/aleksey/.local/lib/python3.5/site-packages/prompt_toolkit/interface.py", line 69, in __init__
    assert isinstance(eventloop, EventLoop), 'Passing an eventloop is required.'
AssertionError: Passing an eventloop is required.
```

## Environment

- Ubuntu 16.04.3 LTS
- zsh 5.1.1 (x86_64-ubuntu-linux-gnu)
» pip freeze
adium-theme-ubuntu==0.3.4
asn1crypto==0.23.0
astroid==1.5.3
attrs==17.2.0
autobahn==17.9.3
Automat==0.6.0
autopep8==1.3.2
backports.csv==1.0.5
backports.functools-lru-cache==1.4
certifi==2017.7.27.1
cffi==1.11.1
chardet==3.0.4
cli-helpers==0.2.3
click==6.7
configobj==5.0.6
configparser==3.5.0
constantly==15.1.0
cryptography==2.0.3
docutils==0.12
dodgy==0.1.9
enum34==1.1.6
flake8==3.4.1
future==0.16.0
gyp==0.1
hkdf==0.0.3
httpie==0.9.2
httplib2==0.10.3
humanize==0.5.1
hyperlink==17.3.1
idna==2.6
incremental==17.5.0
ipaddress==1.0.18
isort==4.2.15
lazy-object-proxy==1.3.1
logilab-common==1.1.0
M2Crypto==0.22.6rc4
magic-wormhole==0.10.3
mccabe==0.6.1
ndg-httpsclient==0.4.0
pep257==0.7.0
pep8==1.7.0
pep8-naming==0.4.1
pgcli==1.8.1
pgspecial==1.8.0
Pillow==3.1.2
prompt-toolkit==1.0.15
prospector==0.12.7
psycopg2==2.7.3.1
pyasn1==0.3.6
pyasn1-modules==0.1.4
pycodestyle==2.3.1
pycparser==2.18
pydocstyle==2.0.0
pyflakes==1.6.0
Pygments==2.2.0
pygobject==3.20.0
pylint==1.7.2
pylint-celery==0.3
pylint-common==0.2.5
pylint-django==0.7.2
pylint-flask==0.5
pylint-plugin-utils==0.2.6
PyNaCl==1.1.2
pyOpenSSL==17.3.0
pyroma==2.0.0b2
PyYAML==3.12
requests==2.18.4
requirements-detector==0.5.2
roman==2.0.0
salesforce-bulkipy==1.0
service-identity==17.0.0
setoptconf==0.2.0
setproctitle==1.1.10
simple-salesforce==0.73.0
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
spake2==0.7
sqlparse==0.2.4
terminaltables==3.1.0
tqdm==4.19.1.post1
Twisted==17.9.0
txaio==2.8.2
txtorcon==0.19.3
unicodecsv==0.14.1
unity-lens-photos==1.0
urllib3==1.22
virtualenv==15.1.0
vulture==0.8.1
wcwidth==0.1.7
wrapt==1.10.11
yapf==0.18.0
zope.interface==4.4.3

**Comment by meeuw** [comment]
have you tried using a fresh (new) virtualenv? you might need to add `--upgrade` to `pip install` ...

**Comment by j-bennet** [comment]
The latest pgcli version with Prompt Toolkit 1.0 is 1.11.0, and with Prompt Toolkit 2.0 is 2.0.0. I would suggest installing one of those.

The command above, `pgcli -h <host_name> -p 5432 -U -d`, looks malformed. I assume you mean it to be `pgcli -h <host_name> -p 5432 -U <username> -d <database name>`, correct?

**Comment by adrien-berchet-forcity** [comment]
I updated using pip and now it works properly (I got the error using the version installed with apt-get on Ubuntu 16.04).
Thanks
