### ISSUE TITLE
Remove newlines and cut long strings

### ISSUE THREAD

**Issue by lazycoder-ru** [dbcli/pgcli#811]
Is it possible to add two options?
- to replace newline characher to whitespace. (eg /newline);
- to cut very long text values;

It would be very useful, because my app stores tracelogs of errors in db, and it's pretty hard to read results of query.

**Comment by j-bennet** [comment]
2nd option (truncate long text values) sounds like it could be a useful feature. I'd be reluctant to replace anything within the fields though - too easy to break things.

**Comment by EvanCarroll** [comment]
I think this would be a cool feature. Something to make this more readable https://dba.stackexchange.com/q/174513/2639

**Comment by shvechikov** [comment]
I would like to have this feature too. Maybe I could even make a PR for the issue if it still considered useful. BTW `csvlook` utility from `csvkit` has a similar option `--max-column-width` and it's really helpful.

**Comment by meeuw** [comment]
I don't know if this works for you, but if your using the less pager (which is sort of our default) you can enter `-S` and less stops wrapping lines.

**Comment by shvechikov** [comment]
Yeah, I use this trick but it isn't very helpful for really huge
text-cells.

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/cli_helpers/pull/48.
