### ISSUE TITLE
Option to intelligently enable pager based on output size (pset is not working)

### ISSUE THREAD

**Issue by maxrothman** [dbcli/pgcli#813]
## Description
It gets annoying that the pager is either on (set to `less`) or off (set to `cat`). When the query has a large number of output lines, it's helpful to have the pager on, but when doing a bunch of small queries in preparation for a larger query, it's helpful to have the pager off so you can see the query results in scrollback.

Would it be possible to have a pager option similar to `\x auto` that decides whether to use the pager based on the size of the output?

## Your environment

- OS: Mac OS 10.12.6
- pgcli version: 1.8.1

**Comment by j-bennet** [comment]
@maxrothman `export LESS=-XFR` may help here. See [this](http://www.mycli.net/pager) for more information.

**Comment by maxrothman** [comment]
Thanks for the tip, but that doesn't match my use-case. I _want_ the screen to clear after I quit the pager, since the whole point is to avoid queries with lots of output from cluttering my scrollback. `less` doesn't seem to have an option for "exit if less than one screen but leave the file contents on the screen only in that case"

**Comment by j-bennet** [comment]
@maxrothman Oh I see, thanks for clarifying that.

**Comment by lelit** [comment]
@maxrothman: IIUC, that seems possible with `pspg -F`, and I'm effectively surprised that `less -F` does not support that.

https://github.com/okbob/pspg

**Comment by j-bennet** [comment]
I'm going to close the issue, because it's not really a bug in `pgcli`, but something that can be managed with the help of pager(s).

**Comment by maxrothman** [comment]
@j-bennet though you're correct in theory, in practice, I'm not aware of a standard pager that covers this usecase. I think the usecase is probably common enough that it warrants re-opening, and I think there are a few paths to solving it:

* Implement an option in pgcli that only enables the pager for a certain amount of output
* Add documentation for, or ship and point to by default a pager that implements this feature. [This](https://unix.stackexchange.com/questions/107315/less-quit-if-one-screen-without-no-init/205260#205260) is a bash script that might be a good starting point, or writing one in Python might avoid the need for a temp file.
* Contribute to less by fixing [issue 303](http://www.greenwoodsoftware.com/less/bugs.html)

Whatever your preference, I'd be happy to make a pull request.

**Comment by j-bennet** [comment]
Out of the options above, I think I'd select 3. I still think it makes more sense to handle this in the pager.

**Comment by maxrothman** [comment]
FWIW, [psql handles this with an option](https://www.postgresql.org/docs/7.4/static/app-psql.html):

> When the pager is off, the pager is not used. When the pager is on, the pager is used only when appropriate, i.e. the output is to a terminal and will not fit on the screen. (psql does not do a perfect job of estimating when to use the pager.) \pset pager turns the pager on and off. Pager can also be set to always, which causes the pager to be always used.

**Comment by j-bennet** [comment]
@maxrothman `pgcli` also has `pset on/off/auto`. From what I understand, the only behavior you're missing with `pgcli + less` is clearing the screen after long queries, while keeping the output of short queries on screen. Is that right?

**Comment by maxrothman** [comment]
I'm looking for `pgcli` to implement the same behavior for `\pset pager` that `psql` has. For example, in `psql`:
```
postgres> \pset pager on
postgres> SELECT table_name from information_schema.tables;
...pager used...
postgres> SELECT table_name from information_schema.tables LIMIT 1;
...pager not used...
```
As expected, with `\pset pager always`, the pager is always used, and with  `\pset pager off`, the pager is never used. In cases where the pager is used, whether the screen is cleared or not afterwards depends on the pager. In cases where it is not, the pager is never invoked.

However, `\pset pager` seems to be completely ignored by `pgcli`:
```
postgres> \pset pager off
postgres> SELECT table_name from information_schema.tables LIMIT 1;
...pager used...
```
So perhaps this issue would be more accurately titled "pgcli ignores \pset pager value"?

**Comment by maxrothman** [comment]
Are y'all still interested in getting this change? I'm happy to contribute it if so.

**Comment by j-bennet** [comment]
PRs are always welcome - go ahead!

**Comment by maxrothman** [comment]
Looks like the same test failed again. Mind kicking it?
