### ISSUE TITLE
Results are appearing in a new window

### ISSUE THREAD

**Issue by afm-sayem** [dbcli/pgcli#817]
## Description
The result opens in a new window rather than the current window. So every time I run a query I have to close the new window(press `q`) to get back to writing queries. Please see attached screencast. The results used to show in the current window but after a system update a couple of months ago it started showing results in a new window.

## Your environment
python `3.6.3`
![screencast_11-27-2017_03_42_40-pm](https://user-images.githubusercontent.com/6215982/33256045-41d1671a-d38b-11e7-95be-8d082aa2d26f.gif)

Tried it in bash and zsh. Tried using fresh `bashrc`. Tried a different terminal emulator.

-  OS: Arch Linux (4.13.12-1-ARCH)
-  pgcli version: `1.8.1`
-  `pip freeze` output:
```
backports.csv==1.0.5
cli-helpers==0.2.3
click==6.7
configobj==5.0.6
humanize==0.5.1
pgcli==1.8.1
pgspecial==1.9.0
prompt-toolkit==1.0.15
psycopg2==2.7.3.2
Pygments==2.2.0
setproctitle==1.1.10
six==1.11.0
sqlparse==0.2.4
terminaltables==3.1.0
wcwidth==0.1.7
```

**Comment by lutzhorn** [comment]
That's not a new window but your pager, probably `less`, that helps you to scroll through a large result.

What behaviour do you expect?

**Comment by afm-sayem** [comment]
This -> ![pgcli demo](https://github.com/dbcli/pgcli/blob/master/screenshots/pgcli.gif)

Where query results are shown inline instead of a new window.

As you can see in the screencast, even if I'm connecting to a new database(which is a one line output), less is being invoked.

**Comment by amjith** [comment]
Yup. That is the pager. @lutzhorn was right on the money. 
The good news is you can configure that pager to do what the pgcli demo does. 
Looks like you're using the latest version of pgcli. If you open up your config file (~/.config/pgcli/config) you'll see a line that is commented out: https://github.com/dbcli/pgcli/blob/master/pgcli/pgclirc#L79

Just uncomment the line and restart pgcli and viola. 

If that line doesn't exist in your config file just copy that line into the config file and uncomment it, and you'll be good to go. 

Older versions of pgcli used to enforce that config option, but it is generally frowned upon to mess with a user's environment vars. So we decided to make it an option.

I hope that helps.

**Comment by vjpr** [comment]
I ran into this issue too. Is this the new default behavior?

**Comment by j-bennet** [comment]
@vjpr It's just that pgcli and mycli stopped overriding `less` options if those are already set in the environment, because that was intrusive. Now LESS is only set if it's unset. For more information, see here:

http://www.mycli.net/pager

But it's possible to use `export LESS="-XFR"`, or override the pager in `pgclirc` like @amjith mentioned above, to get the same behavior as before.

**Comment by j-bennet** [comment]
I'm going to close the issue - please flee to reopen if you still have problems, @afm-sayem!
