### ISSUE TITLE
Error on connect: ProgrammingError: syntax error at or near "schema_name"

### ISSUE THREAD

**Issue by maiconzucco** [dbcli/pgcli#822]
## Description
After a connection I receive the error below
`night@nights-MacBook-Pro:~$ pgcli postgres://user:pass@host:5432/my_schema
Version: 1.8.1
Chat: https://gitter.im/dbcli/pgcli
Mail: https://groups.google.com/forum/#!forum/pgcli
Home: http://pgcli.com
swpmbc_des> Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in runhing completions...                                                                          
    self.__target(*self.__args, **self.__kwargs)
  File "/Library/Python/2.7/site-packages/pgcli/completion_refresher.py", line 68, in _bg_refresh
    refresher(completer, executor)
  File "/Library/Python/2.7/site-packages/pgcli/completion_refresher.py", line 109, in refresh_tables
    completer.extend_relations(executor.tables(), kind='tables')
  File "/Library/Python/2.7/site-packages/pgcli/pgcompleter.py", line 181, in extend_relations
    data = [self.escaped_names(d) for d in data]
  File "/Library/Python/2.7/site-packages/pgcli/pgexecute.py", line 414, in tables
    for row in self._relations(kinds=['r']):
  File "/Library/Python/2.7/site-packages/pgcli/pgexecute.py", line 408, in _relations
    cur.execute(sql)
ProgrammingError: syntax error at or near "schema_name"
LINE 2:         SELECT  n.nspname schema_name,
                                  ^

my_schema >                                                                                                                                                                                                
my_schema > exit
Goodbye!`

For solve this I prefixed all alias on file /Library/Python/2.7/site-packages/pgcli/pgexecute.py with "AS".
Do I have another way?

Thanks.

## Your environment
- [ ] Please provide your OS and version information.
MacOS 10.13.2
`my_schema > select version();
+-----------------------------------------------------------------------------------------------------------+
| version                                                                                                   |
|-----------------------------------------------------------------------------------------------------------|
| PostgreSQL 8.2.23 on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4) |
+-----------------------------------------------------------------------------------------------------------+
SELECT
Time: 0.005s`

- [ ] Please provide your CLI version.
Version: 1.8.1

- [ ] What is the output of ``pip freeze`` command.
night@nights-MacBook-Pro:~$ pip freeze
altgraph==0.10.2
backports.csv==1.0.5
bdist-mpkg==0.5.0
bonjour-py==0.3
cli-helpers==0.2.3
click==6.7
configobj==5.0.6
humanize==0.5.1
macholib==1.5.1
matplotlib==1.3.1
modulegraph==0.10.4
numpy==1.8.0rc1
pgcli==1.8.1
pgspecial==1.9.0
prompt-toolkit==1.0.15
psycopg2==2.7.3.2
py2app==0.7.3
Pygments==2.2.0
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==1.5
pytz==2013.7
scipy==0.13.0b1
setproctitle==1.1.10
six==1.11.0
sqlparse==0.2.4
terminaltables==3.1.0
wcwidth==0.1.7
xattr==0.6.4
zope.interface==4.1.1

**Comment by j-bennet** [comment]
Thank you for the bug report! PostgreSQL 8.2 is pretty old, and I think it does not support `SELECT <table> <alias>`, only `SELECT <table> AS <alias>`. Should be easy enough to fix. If you already have a fix that's working, don't hesitate to submit a PR!

**Comment by dbaty** [comment]
It should indeed be easy to fix (yeah, "famous last words" ;) ), but I'll note that the `as` keyword is optional since PostgreSQL 8.4, which has been released in 2009 (and that the latest release and end of life of 8.3, where `as` was required, was in 2013). Given that not too many people have loudly complained about this error, I wonder if we really want to keep this open. I'm inclined to close this issue. (Obviously, I can also live with it if it stays open. :) But I doubt it will move anytime soon...)

Reference: [8.3 syntax documentation](https://www.postgresql.org/docs/8.3/sql-select.html) and [8.4 syntax documentation](https://www.postgresql.org/docs/8.4/sql-select.html).

**Comment by j-bennet** [comment]
Famous last words indeed. :) Let's close the issue.
