### ISSUE TITLE
Support for query parameters/variables, like psql \set

### ISSUE THREAD

**Issue by aseemk** [dbcli/pgcli#829]
Hi there,

Thanks for the great work on `pgcli`! It's a great tool.

Apologies if this is a dupe issue. I searched and didn't find anything (other than saved & favorite queries, which isn't quite the same thing), but I may have missed it.

With `psql`, I regularly make use of `\set` in my scripts to set variables and use them as query parameters:

https://www.postgresql.org/docs/current/static/app-psql.html#APP-PSQL-VARIABLES

(Discovered via https://stackoverflow.com/questions/36959/how-do-you-use-script-variables-in-postgresql)

It would be great to have support for this in `pgcli` too.

Is there some other way though that people use query parameters/variables with `pgcli`?

Thanks again!

**Comment by j-bennet** [comment]
I don't think psycopg2 supports this. We could do our own substitution, but that would be non-trivial. It sounds like a nice feature to have though.
