### ISSUE TITLE
Query the table, the table has the Chinese language to display the garbled code

### ISSUE THREAD

**Issue by cyongk** [dbcli/pgcli#833]
Query the table, the table has the Chinese language to display the garbled code
![1](https://user-images.githubusercontent.com/16489791/34650546-d8d2eb4c-f3fd-11e7-82c2-1c22b9752ba2.PNG)

**Comment by fpietka** [comment]
It may be related to Windows, as I am using it on OSX with Japanese Kanji without any issue.
I'll check later on linux.

**Comment by cyongk** [comment]
I'm using the Chinese language of the Windows 10 professional x64 system

**Comment by dbaty** [comment]
Someone else recently reported the same issue in #833. @cyongk : if you're still around and interested in getting this fixed, do you have a way to reproduce this bug? I don't speak nor write Chinese, so my naïve attempt did not produce anything suspicious when running in pgcli:

```
> create table chinese_chars (t text);
CREATE TABLE
> insert into chinese_chars (t) values ('繁体字')
INSERT 0 1
> select * from chinese_chars
+--------+
| t      |
|--------|
| 繁体字  |
+--------+
SELECT 1
```

I am looking for a particular `insert into` query that would trigger this bug.
