### ISSUE TITLE
Consolidate config options

### ISSUE THREAD

**Issue by j-bennet** [dbcli/pgcli#835]
This is a plan for consolidating and cleaning up config options in pgclirc.

Remove:

* `smart_completion = True` (always True)
* `generate_aliases = False` (always True)
* `keyword_casing = auto` (always `auto`)
* `timing = True` (always True)
* [maybe] `asterisk_column_order = table_order` (do we really need `alphabetic`?)

Merge:

* set `expand ` to one `on|off|auto`, and remove `auto_expand`
* set `multi_line` to `psql|safe|off`, and remove `multi_line_mode`

(Optional) Rework:

* `on_error = STOP`: not well suited for a config option. Better ask the user after the first error occurred if he wants to continue.

cc @amjith @tsroten

**Comment by tsroten** [comment]
Another suggestion is to make a `pager_mode` setting to accompany the `pager` setting. So, `pager` is used to set the pager's command itself, but `pager_mode` is used to set if it's on, off, or set to automatic mode.

In mycli (I'm not sure about pgcli), the default automatic page mode means that the pager will activate if the output is longer than one screen's length of content.

The recent pull requests for `pager_enabled` work well, but only allow the user to turn the pager on or off, which rules out controlling the automatic mode.
