### ISSUE TITLE
Interval type display is inconsistent with postgres.

### ISSUE THREAD

**Issue by usrenmae** [dbcli/pgcli#840]
## Description
When a field is of type `interval` defined in _months_ or years, it will be displayed in _days_ instead, which is very confusing, as the amount of days may be varying depending on the current time. So `'1 month'::interval` is displayed as `30 days, 0:00:00` instead.

### Expected
```sql
db=> select now(), '1 month'::interval, '1 year'::interval;
             now              | interval | interval
------------------------------+----------+----------
 2018-02-12 10:14:34.95266+00 | 1 mon    | 1 year
```

### Actual
```sql
db> select now(), '1 month'::interval, '1 year'::interval;
+-------------------------------+------------------+-------------------+
| now                           | interval         | interval          |
|-------------------------------+------------------+-------------------|
| 2018-02-12 10:15:02.621136+00 | 30 days, 0:00:00 | 365 days, 0:00:00 |
+-------------------------------+------------------+-------------------+
```

## Your environment

- [ ] macOS 10.13.3 (17D47)
- [ ] pgcli: stable 1.8.2 (bottled)

**Comment by amjith** [comment]
You're right. Looks like this is an artifact of psycopg2 trying to convert the intervals into python timedeltas. 

https://github.com/psycopg/psycopg2/issues/449

The github issue linked above has listed a workaround. 

If you're interested in contributing you can take a look at this file ([pgexecute.py](https://github.com/dbcli/pgcli/blob/master/pgcli/pgexecute.py#L61)) where we register adapters to psycopg2 to do our own custom typecasting. 

If you're not interested, let us know and we'll try to get that in ourselves.
