### ISSUE TITLE
Cannot pass parameters to Named Query

### ISSUE THREAD

**Issue by yejianye** [dbcli/pgcli#841]
Description:
I tried the named query example in https://www.pgcli.com/features
```
> \ns foo select $1
Saved.

> \n foo 1
there is no parameter $1
```

Btw, using `%s` works.

Environment:
os: Mac OS High Sierra
pgcli: v1.8.2

**Comment by tsroten** [comment]
@yejianye Thanks for reporting this! It looks like that documentation was released a little too early 😄 That feature isn't in the newest version of pgcli, yet. We'll get that fixed! Thanks!

**Comment by fpietka** [comment]
@yejianye this should now be working with newer 1.9.0 version.

Thanks for your patience.
