### ISSUE TITLE
DistributionNotFound error on fresh install

### ISSUE THREAD

**Issue by mapleoin** [dbcli/pgcli#852]
## Description
I can't start pgcli after a fresh installation using pip:

```
$ pgcli 
Traceback (most recent call last):
  File "/home/ionut/venv/bin/pgcli", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/ionut/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/home/ionut/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ionut/venv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cli-helpers[styles]>=1.0.1
```

## Your environment
Debian GNU/Linux 7.8 (wheezy)
```
backports.csv==1.0.5
cli-helpers==1.0.1
click==6.7
configobj==5.0.6
humanize==0.5.1
pgcli==1.9.0
pgspecial==1.10.0
prompt-toolkit==1.0.15
psycopg2-binary==2.7.4
Pygments==2.2.0
setproctitle==1.1.10
six==1.11.0
sqlparse==0.2.4
tabulate==0.8.2
terminaltables==3.1.0
wcwidth==0.1.7
```

**Comment by j-bennet** [comment]
@tsroten could you take a look?

**Comment by tsroten** [comment]
Hello! It looks like the version of distribute that your pip is using is around 7 years old. It doesn’t appear to support the “extras_require” feature that pgcli uses.

Can you update pip to a newer version? It looks like there are quite a few guides online to update pip on Debian wheezy.

I believe that by updating pip, distribute will be updated with it.

I’m not at the computer right now, but if you have any issues updating pip/distribute, let us know.

Thanks!!

**Comment by mapleoin** [comment]
Upgrading, `distribute` fixed it. Thanks! 

FWIW, I was already on the latest pip version (9.0.1), with a fresh virtualenv.

**Comment by j-bennet** [comment]
@tsroten thanks a lot - eagle eye!
