### ISSUE TITLE
pgcli runs away and hogs all my CPU if I don't exit gracefully

### ISSUE THREAD

**Issue by RoyWiggins** [dbcli/pgcli#853]
## Description
I am invoking pgcli as ``sudo su postgres -c pgcli``. If my SSH connection drops, the process keeps going regardless, and sometimes starts hogging all my CPU. 

## Your environment

Ubuntu 16.04
pgcli v 0.20.1
[pip freeze.txt](https://github.com/dbcli/pgcli/files/1813144/pip.freeze.txt)

**Comment by amjith** [comment]
Sorry about the inconvenience. 

I'm unable to reproduce. Can you try upgrading to the latest version? We've come a long way since v0.20.1.

You can upgrade using `pip install -U pgcli`.
