### ISSUE TITLE
Request: ability to restore saved query and edit

### ISSUE THREAD

**Issue by davidrthorn** [dbcli/pgcli#855]
Would be great to be able to invoke saved queries so that they are available to edit in the command line and then execute, rather than simply executing from memory.

**Comment by j-bennet** [comment]
@davidrthorn Did you find a solution for this? (`Ctrl + R ` history search perhaps)?

**Comment by davidrthorn** [comment]
@j-bennet I actually didn't, but I closed this issue thinking that `\e` was this. One option might be to run the saved query then use `\e` to edit it before resaving.
