### ISSUE TITLE
Customized prompt not used

### ISSUE THREAD

**Issue by akuchling** [dbcli/pgcli#858]
## Description

I was puzzled when connecting to one server produced the `user@server:dbname>` prompt I expected, but another server produced just `dbname>`.  

It turns out that if the prompt ends up longer than `self.max_len_prompt`, which is set to 30 and isn't configurable, pgcli falls back to just `dbname>`.    I was using just 'docker' for one hostname and the other was 'db-dev.domainname.tld', which pushed the whole prompt over the limit.  (My username is always 'akuchling', so there's 9 characters right there!)

Two ideas:

1) bash's prompt formatting supports both the FQDN and just the local hostname.  Would you like me to write a patch adding a similar new formatting character?  Unfortunately bash uses \h for the up-to-the-first-'.' and \H for the full name.  This would be an incompatible change for pgcli, where \h is currently the full server name.  Would we want to change the meaning of \h in pgcli, have the opposite of bash's variables (\h for full, \H for shortened), or just pick some different character?

2) We could also make the max_len_prompt configurable.  Does that seem worth doing?

## Your environment

pgcli version 1.9.0.

**Comment by j-bennet** [comment]
A "short host name" formatting character would be great. I think it would be ok if we switch the meaning of `\h` to "short host name", and use `\H` for "full host name" (users might even appreciate shorter prompt). Perhaps with this change you would not need to increase `max_len_prompt`.

**Comment by akuchling** [comment]
Closing this issue, because a fix was merged.
