### ISSUE TITLE
\dF does not work to list text search configurations

### ISSUE THREAD

**Issue by Flimm** [dbcli/pgcli#887]
When I use `psql`, I can type `\dF` to get a list of text search configurations:

```
> \dF
               List of text search configurations
   Schema   |    Name    |              Description
------------+------------+---------------------------------------
 pg_catalog | danish     | configuration for danish language
 pg_catalog | dutch      | configuration for dutch language
 pg_catalog | english    | configuration for english language
 pg_catalog | finnish    | configuration for finnish language
 pg_catalog | french     | configuration for french language
 pg_catalog | german     | configuration for german language
...
```

However, doing the same in `pgcli` gives an error:

```
> \dF
syntax error at or near "\"
LINE 1: \dF
```

**Comment by amjith** [comment]
Yeah, we don't have full support for all the backslash commands. Looks like \dF is not yet implemented in pgspecial (the library used by pgcli to implement the backslash commands).

If you are interested in contributing, we have a pretty thorough documentation on how to get started.

https://github.com/dbcli/pgspecial/blob/master/DEVELOP.rst#adding-postgresql-special-meta-commands

We're also happy to help you guide through the process if you need it.
