### ISSUE TITLE
Executing operations with info output during execution do not output.

### ISSUE THREAD

**Issue by fake-name** [dbcli/pgcli#900]
## Description

Basically, for commands that have incremental output, the output seems to be buffered until the commands finish, and then displayed all at once. E.g.: 

 - `VACUUM VERBOSE <table>;`
 - \<Command blocks for the duration of the vacuum\>
 - All output shows up at once.

With `psql`:

 - `VACUUM VERBOSE <table>;`
 - \<Each index is vacuumed\>
 - \<Dead rows removed\>
 - \<Toast rows vacuumed\>
 - ... etc...
 - \<Command finished\>

For some vacuum operations, having indication of the progress is really, really important. I have some tables that take more then a week to vacuum, and being able to validate that the vacuum is doing *something* is really nice.

## Env:

 - Ubuntu 16.04 LTS
 - ~> pgcli --version
    Version: 1.9.1
 - Python 3.4.3

I ran `pip3 install --upgrade pgcli` immediately before filing this issue.

**Comment by amjith** [comment]
This is a shortcoming of the python database driver (psycopg2) that we're using. It doesn't have a way to send partial results in an async fashion. 

So we have to wait till the entire operation has finished and only then we get access to the output.
