### ISSUE TITLE
Cannot save sql with has '$'

### ISSUE THREAD

**Issue by cn-src** [dbcli/pgcli#925]
## Description
If the $symbol is included in the SQL statement:
```sql
\ns iuser insert into t_user (id, username, password, enabled) values ('1', 'user', '$2a$10$B4EuHii', true);
```
```
\n iuser
Bad arguments
```
I think it is not necessary to enter arguments, or provide another command execute SQL.

## Your environment
* MacOS use brew install
* pgcli version 1.10.2

**Comment by j-bennet** [comment]
P.S. Old issue - this might work in newer `pgcli`, but has to be verified.

**Comment by dbaty** [comment]
This issue is very old. I cannot reproduce the problem with the latest version of pgcli (4.1.0):

```
$ pgcli --less-chatty
> \ns iuser insert into t_user (id, username, password, enabled) values ('1', 'user', '$2a$10$B4EuHii', true);
Saved.
> quit
$ grep iuser ~/.config/pgcli/config
iuser = "insert into t_user (id, username, password, enabled) values ('1', 'user', '$2a$10$B4EuHii', true)"
```

Everything seems fine. I am closing this issue. Feel free to reopen if you can reproduce.
