### ISSUE TITLE
Installation fails with ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by pydemo** [dbcli/pgcli#931]
## Description
Python 3.7.0a4 Windows build fails.

Error message:
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "C:\Users\OB66759\P\Python37-64\lib\site-packages\setuptools\command\bdis
t_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

## Your environment
Python 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 07:07:02) [MSC v.1900 64 bit (AMD64)] on win32

- [ ] Please provide your OS and version information.
Windows 7 service pack 1
- [ ] Please provide your CLI version.

Microsoft Windows [Version 6.1.7601]

- [ ] What is the output of ``pip freeze`` command.
backcall==0.1.0
blessings==1.7
bpython==0.17.1
certifi==2018.8.13
chardet==3.0.4
cli-helpers==1.0.2
click==6.7
colorama==0.3.9
configobj==5.0.6
curses==2.2+utf8
curtsies==0.3.0
cycler==0.10.0
decorator==4.3.0
docopt==0.6.2
future==0.16.0
greenlet==0.4.14
humanize==0.5.1
idna==2.7
ipython==6.5.0
ipython-genutils==0.2.0
jedi==0.12.1
kiwisolver==1.0.1
matplotlib==2.2.3
numpy==1.15.0
parso==0.3.1
pgcli==1.10.3
pgspecial==1.11.2
pickleshare==0.7.4
ply==3.11
prompt-toolkit==1.0.15
psycopg2==2.7.5
ptpython==0.41
Pygments==2.2.0
PyHive==0.6.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.5
requests==2.19.1
sasl==0.2.1
scipy==1.1.0
setproctitle==1.1.10
simplegeneric==0.8.1
six==1.11.0
sqlparse==0.2.4
tabulate==0.8.2
terminaltables==3.1.0
thrift==0.11.0
thrift-sasl==0.2.1
thriftpy==0.3.9
traitlets==4.3.2
typing==3.6.4
urllib3==1.23
wcwidth==0.1.7

**Comment by j-bennet** [comment]
Let's close.
