### ISSUE TITLE
How can I leave the output of previous commands on screen?

### ISSUE THREAD

**Issue by wonderbeyond** [dbcli/pgcli#935]
![image](https://user-images.githubusercontent.com/228361/45196734-4821a780-b290-11e8-9429-6b37e92be94f.png)

After I press `q` on a output, it just disappears. I really want it stay on screen, so I can compare different commands' outputs.

## My environment
- [x] Ubuntu 16.04.5 LTS
- [ ] pgcli==1.10.3
- [ ] prompt-toolkit==1.0.15

**Comment by lelit** [comment]
Maybe the `-X` option of `less` or `pspg` does what you want? You can try it adding something like
```
pager = less -X
```
to your config. My personal config contains `pspg -XFs 4`.
