### ISSUE TITLE
Named queries not loaded from or saved to config file

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#938]
Pgcli 1.10.3 running on Windows 10 with Python 3.7.0

When using a non-default config file (`--pgclirc`) named queries are neither loaded from nor saved to the config files. Instead they are loaded from and saved to the default config file.

The same issue happens with mssql-cli (https://github.com/dbcli/mssql-cli/issues/222).

**Comment by zachvalenta** [comment]
Now that #962 has been merged can this ticket be closed?

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/962.
