### ISSUE TITLE
Add the option of hiding the toolbar (statusbar)

### ISSUE THREAD

**Issue by igorkaludjer** [dbcli/pgcli#939]
## Description
Apparently prompt-toolkit has this option (https://github.com/jonathanslenders/python-prompt-toolkit/issues/498)

**Comment by stephanoparaskeva** [comment]
Any updates on this?

**Comment by j-bennet** [comment]
Looks like nobody had the time to pick this up. Are you willing to submit a PR? You would need to add a new config option to pgclirc:

https://github.com/dbcli/pgcli/blob/master/pgcli/pgclirc

then read it on `init`:

https://github.com/dbcli/pgcli/blob/005fd2fcee258ae192ed01d503303068558b0e89/pgcli/main.py#L150

then set `bottom_toolbar` to None based on that option's value:

https://github.com/dbcli/pgcli/blob/005fd2fcee258ae192ed01d503303068558b0e89/pgcli/main.py#L795

**Comment by stephanoparaskeva** [comment]
@j-bennet PR for requested changes #1170
