### ISSUE TITLE
Feature request: transaction status prompt option

### ISSUE THREAD

**Issue by cswingle** [dbcli/pgcli#940]
One of the few things I miss from `psql` is the `%x` prompt option that indicates the current transaction status (https://www.postgresql.org/docs/current/static/app-psql.html#APP-PSQL-PROMPTING). It's pretty handy to have a visual clue that there is a transaction pending so you don't walk away and potentially leave other database users locked out of whatever you were doing.

**Comment by j-bennet** [comment]
<img width="810" alt="screenshot 2018-09-21 14 42 52" src="https://user-images.githubusercontent.com/637013/45907424-ab412d00-bdac-11e8-8216-f6f8f5899430.png">

We have a visual indicator of transaction in status bar. Does that help?

**Comment by cswingle** [comment]
@j-bennet Excellent, yes, that helps a lot. I just noticed the transaction indication on my laptop; perhaps my configuration at work is different and I don't have this enabled. Or I simply missed it!
