### ISSUE TITLE
Is there support for functionality analogous to psql -c STATEMENT?

### ISSUE THREAD

**Issue by jrvanalstine** [dbcli/pgcli#947]
I would like to use pgcli to execute sql statements from an application. Usually I use the postgres-client that comes with my debian distro. Is there something analogous to `psql -c STATEMENT` supported by pgcli?

**Comment by j-bennet** [comment]
Not really. The purpose of pgcli was always to provide the best possible UI for humans. Batch jobs, non-interactive usage etc. were not a priority.

We're not opposed to PRs if someone wants to add this feature to pgcli!

Related issue: https://github.com/dbcli/pgcli/issues/307
