### ISSUE TITLE
-d should override PGDATABASE

### ISSUE THREAD

**Issue by mwilliammyers** [dbcli/pgcli#950]
Right now: `PGDATABASE=bar pgcli -d foo` will connect to `bar`. However, `psql` will connect to `foo`.

What are your thoughts on changing it to match `psql`'s behavior? Or is that too big of a breaking change?

In case it matters:
- `psql (PostgreSQL) 10.5 (Ubuntu 10.5-0ubuntu0.18.04)`
- `pgcli`:`Version: 1.6.0`

**Comment by j-bennet** [comment]
Yes, I think command line arguments should override environment variables.
