### ISSUE TITLE
Changing config so that every query doesn't require and extra carriage return

### ISSUE THREAD

**Issue by dekhaus** [dbcli/pgcli#955]
Hi

On my mac - every command I execute within pgcli runs but ends with an (END) being displayed and the only way to continue working is to enter press the 'q' key.

Is the default behavior ?

I would like pgcli to work like psql in that when I execute a sql command - all the results are displayed and no extra/additional key command is necessary for me to continue using pgcli.

The way it works now - I always have to hit the 'q' key to continue using pgcli.  I would like to turn this off.  Is it possible ?  If so - how ?

Thanks
Dave

**Comment by j-bennet** [comment]
This is not pgcli. This is your pager. Try setting `LESS=-XFR` like described here https://www.pgcli.com/pager
