### ISSUE TITLE
Here’s to you guys

### ISSUE THREAD

**Issue by dustinromey** [dbcli/pgcli#957]
## Description
No problem. Just thanks. 

I use the crap out of pgcli. Every day. It’s become my main method for running queries. And it’s glorious. 

The only time I interact with Postgres another way is if I need to visualize the schema, and it’s easier to use OmniDB or PgAdmin for that. 

So I just wanted to say thanks. 

## Your environment
Debian inside Crostini on a pixelbook

**Comment by dustinromey** [comment]
And thanks to @jerodsanto for suggesting the issue. It’s a great idea. 

https://changelog.com/posts/make-an-open-source-maintainers-day-with-this-one-weird-trick

**Comment by j-bennet** [comment]
Aww. Thank you for using `pgcli`!
