### ISSUE TITLE
pgcli.packages.tabulate.tabulate is not aware of multiline strings

### ISSUE THREAD

**Issue by CyberDem0n** [dbcli/pgcli#96]
Test example:

``` python
    >>> print(tabulate([["spam", 41.9999], ["new\\nline", "451.0"]], tablefmt="grid"))
    +------+----------+
    | spam |  41.9999 |
    +------+----------+
    | new  | 451      |
    | line |          |
    +------+----------+
```

But instead of expected output we will get:

``` python
    +----------+----------+
    | spam     |  41.9999 |
    +----------+----------+
    | new
    line | 451      |
    +----------+----------+
```

**Comment by amjith** [comment]
This is a feature request for [Tabulate](https://bitbucket.org/astanin/python-tabulate) and it looks like someone is already working on it. 

https://bitbucket.org/astanin/python-tabulate/issue/28/feature-request-multiline-cells-and

**Comment by bersace** [comment]
@CyberDem0n this is the current output of tabulate in pgcli:

``` console
>>> print(tabulate([["spam", 41.9999], ["new\\nline", "451.0"]], tablefmt="grid")[0])
+-----------+---------+
| spam      | 41.9999 |
+-----------+---------+
| new\nline | 451.0   |
+-----------+---------+
>>>
```

Are you ok with that ?

**Comment by fpietka** [comment]
tabulate is gone now, and terminaltables handle newline fine. Although output is still broken in pgcli.
Anyway, maybe this issue should be closed for a new one, until this display bug is fixed.

**Comment by tsroten** [comment]
@fpietka Thanks for mentioning the recent output change in pgcli.

Actually, tabulate is still used. It's the default package used to display output in pgcli. Users can optionally use terminaltables by setting their `table_format` to `ascii` or `double` (and I don't think that's in the current release, yet).

Now that pgcli is following the official tabulate package, this bug relies on the [upstream issue](https://bitbucket.org/astanin/python-tabulate/issues/28/feature-request-multiline-cells-and) being addressed.

**Comment by fpietka** [comment]
Ok I see it in `cli-helpers`. I thought it was simply gone since 6a33014, sorry

**Comment by tsroten** [comment]
@fpietka No problem! It's hard keeping track of all the dependencies 😄

**Comment by amjith** [comment]
This is now fixed in the latest version.

**Comment by amjith** [comment]
I misspoke. It is not fixed by default you still have to make a change in your config file. 

Change the table_format to `ascii` in your config file (~/.config/pgcli/config) and that will support multi-line strings.
