### ISSUE TITLE
\H prompt variable shows /tmp for unix domain socket connection

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#963]
pgcli shows `/tmp` for unix domain socket connections (prompt is `\u@\H:\p/\d dbcli> `). `psql` shows `[local]` instead.

Port shows as 5432 while it probably should be "(none)" since domain sockets don't have ports. `psql` also shows `5432`.
```
> psql postgresql://postgres:password@
psql (11.0)
Type "help" for help.

postgres@[local]:5432/postgres psql> \q

> pgcli postgresql://postgres:password@
Server: PostgreSQL 11.0
Version: 2.0.0
[...]
postgres@/tmp:5432/postgres dbcli>
```

**Comment by j-bennet** [comment]
Thank you for the bug report! `/tmp` is not a problem - I don't think we need to copy `psql` in everything. But yes, showing port in case of unix socket connection is a bit weird.

**Comment by j-bennet** [comment]
Perhaps - I don't have a strong opinion on this one. :) In case you'd like to take a stab at fixing it, here is the relevant code:

https://github.com/dbcli/pgcli/blob/589c2abdfb329d343f5fcc41f674993677f01607/pgcli/main.py#L888-L903
