### ISSUE TITLE
Default prompt not applied

### ISSUE THREAD

**Issue by thorstenkampe** [dbcli/pgcli#965]
The default prompt is not applied on Linux when using a Unix-domain socket connection neither implicitly through the config file
```
postgres@db:~$ pgcli
Server: PostgreSQL 11.0
Version: 2.0.0
[...]
postgres>
```
...nor explicitly via `--prompt`
```
postgres@db:~$ pgcli --prompt "\u@\h:\d> "
Server: PostgreSQL 11.0
Version: 2.0.0
[...]
postgres>
```
But when I modify the default prompt even slightly, it works:
```
postgres@db:~$ pgcli --prompt "X-\u@\h:\d> "
Server: PostgreSQL 11.0
Version: 2.0.0
[...]
X-postgres@/var/run/postgresql:postgres>
```

**Comment by j-bennet** [comment]
I think your prompt might be too long. Pgcli does this when prompt is length > 30:

https://github.com/dbcli/pgcli/blob/3b9041fe36798639b4316fb3e413ac7a04c43da3/pgcli/main.py#L688-L690

**Comment by thorstenkampe** [comment]
So when the default prompt results in a prompt of more than thirty characters, only the database is prompted. But when I explicitly choose a  - non-default - prompt, this does not apply.

I'm closing this ticket.

**Comment by j-bennet** [comment]
Exactly!
