### ISSUE TITLE
Discarding \ef or \ev code results in AssertionError

### ISSUE THREAD

**Issue by mkcinu** [dbcli/pgcli#969]
## Description
1. Open a function (or a view) to edit with \ef (or \ev) in the editor
2. Close the editor
3. Discard the code from the prompt with Ctrl-C
4. Boom! AssertionError.

Is there any other way to discard the code after \ef other than "backspacing" it? The current behaviour isn't consistent with Ctrl-C after typing the code directly into the prompt.

## Your environment
Linux, bash

pgcli 2.0.0

Thanks.

**Comment by igncampa** [comment]
I'm getting an `IndexError` just by entering `\ef` and `\ev` does literally nothing. Am I missing something here? `\e` works as expected.
I'm on Python 3.6, Ubuntu 18, PostgreSQL 10.6, pgcli 2.0

**Comment by amjith** [comment]
@igncampa I think I have figured out what you were experiencing. 

`\ef` and `\ev` are special commands for editing an existing function or an existing view. 

So they are supposed to be called with `\ev view_name` or `\ef function_name`. If you type in `\ev` without a view name as its argument nothing will happen.

If you type in `\ef` without any function name as its argument it will crash. I'm working on a fix for that.

**Comment by amjith** [comment]
A new version of `pgspecial` is released that addresses the issue raised by @igncampa. 

`pgspecial` is a dependency of pgcli which handles the special commands such as `\ef` and `\ev`. 

You can upgrade it using `pip install -U pgspecial`.

**Comment by igncampa** [comment]
Thanks, it seems your fix did the trick after upgrading both `pgcli` and `pgspecial`.

When `\ev` and `\ef` are passed without arguments using `psql`, it opens a view or function template for the user to use as a starting point. Maybe we can mimic the functionality?

Should I open a new issue?
Let me know if I can help. I'm still getting familiar with the codebase but I'm also looking forward to contributing code.

**Comment by amjith** [comment]
Yeah. Let's open a new issue. That's a great idea to provide a template when a name is not provided.

**Comment by amjith** [comment]
@igncampa I'm glad you're looking to help.

The backslash commands are implemented as a separate package called `pgspecial`. You can find the code here: https://github.com/dbcli/pgspecial

You want to look at this file: https://github.com/dbcli/pgspecial/blob/master/pgspecial/iocommands.py

**Comment by igncampa** [comment]
I just realized the issue had been already raised at #754 so I think we can handle it there. I'm hoping I can propose something by tomorrow. Thanks for the pointer.
