### ISSUE TITLE
Getting pgcli to work on Windows 7

### ISSUE THREAD

**Issue by tinmanjk** [dbcli/pgcli#974]
## Description

I am not able to install pgcli via pip on Windows.
I have tried to install a binary of psycopg2 (as suggested in issue #108) in advance but to no avail. 
Does anybody have a step-by-step guide on how to do that?
## Your environment

- [ ] Please provide your OS and version information.
Windows 7 64bit
- [ ] Please provide your CLI version.
- [ ] What is the output of ``pip freeze`` command.

**Comment by j-bennet** [comment]
What kind of error are you getting?

**Comment by j-bennet** [comment]
Yes, newer versions of `pgcli` bumped psycopg requirement to `psycopg2 >= 2.7.4,<2.8`:

https://github.com/dbcli/pgcli/blob/3b9041fe36798639b4316fb3e413ac7a04c43da3/setup.py#L19

and I don't see any binaries for that in linked issue (previously the problem was solved with binaries from http://www.stickpeople.com/projects/python/win-psycopg/).

@dbcli/pgcli-core Any of you use Windows / able to help?

**Comment by meeuw** [comment]
I haven't tried it but I'd recommend https://www.anaconda.com/download/#windows

Which includes a compiled version of psycopg2 (https://docs.anaconda.com/anaconda/packages/py3.6_win-64/)

After installing anaconda you should start an "Anaconda Prompt"
https://conda.io/docs/user-guide/getting-started.html

And run the following command:
`pip install pgcli`

Then you should be able te start pgcli from the same anaconda prompt.

**Comment by tinmanjk** [comment]
Thanks for the suggestion. Was hoping for something 'simpler' though.

**Comment by dbaty** [comment]
Commit 96eb37fd1989ec8fd86150f20053abd03f50e7a4 changed the requirement to `psycopg2-binary` on Windows, which should fix the installation. (I don't use Windows and I cannot confirm.) This (old and not very detailed) issue can be closed once a new version of pgcli is released with that change.

**Comment by dbaty** [comment]
The aforementioned fix has been included in version 4.1.0 of pgcli. I am closing this.
