### ISSUE TITLE
Use pygments TrueColorFormatter 

### ISSUE THREAD

**Issue by petobens** [dbcli/pgcli#980]
As far as I can see (but might be terribly mistaken) pygments true color formatter is not being used (http://pygments.org/docs/formatters/?highlight=truecolor#TerminalTrueColorFormatter). Can a config option be added to do so? Thanks!

**Comment by igorkaludjer** [comment]
@petobens Is there currently a way to use just the ordinary TerminalFormatter for syntax coloring?

**Comment by petobens** [comment]
You can create your own pygments style and place it in the pygments style folder. I do such thing here: https://github.com/petobens/dotfiles/blob/master/python/onedarkish.py and here: https://github.com/petobens/dotfiles/blob/master/setup-new/python.sh#L99

**Comment by igorkaludjer** [comment]
Thank you! It would be nice though to have a built-in option to use the terminal formatter.
