### ISSUE TITLE
Reconnect automatically

### ISSUE THREAD

**Issue by igorkaludjer** [dbcli/pgcli#989]
## Description
When a redshift connection is idle for a couple of minutes and then a command is issued, pgcli hangs for several minutes (this is a psycopg2 issue) before it outputs "SYSCALL error". Then you have to issue to command again, after which it prompts "Connection reset. Reconnect?".  Then it outputs "Reconnected! Try the command again" and you have to issue the command the third time. mycli reconnects automatically without any prompts. It would be great if we could have the same in pgcli. Thanks for the great work!

## Your environment
MacOS 10.14.1
pgcli v2.0.2.

```
appnope==0.1.0
autopep8==1.4.3
awscli==1.16.81
backcall==0.1.0
boto3==1.9.69
botocore==1.12.71
cachetools==3.0.0
certifi==2018.11.29
chardet==3.0.4
colorama==0.3.9
configobj==5.0.6
decorator==4.3.0
docopt==0.6.2
docutils==0.14
et-xmlfile==1.0.1
future==0.17.1
google-api-python-client==1.7.7
google-auth==1.6.2
google-auth-httplib2==0.0.3
httplib2==0.12.0
idna==2.8
ipython==7.2.0
ipython-genutils==0.2.0
jdcal==1.4
jedi==0.13.2
jmespath==0.9.3
mccabe==0.6.1
mysql-connector==2.1.6
numpy==1.15.4
oauth2client==4.1.3
openpyxl==2.5.12
pandas==0.23.4
parso==0.3.1
pexpect==4.6.0
pickleshare==0.7.5
pluggy==0.8.0
prompt-toolkit==2.0.7
psycopg2==2.7.6.1
ptpython==2.0.4
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pydocstyle==3.0.0
pyflakes==2.0.0
Pygments==2.3.1
python-dateutil==2.7.5
python-jsonrpc-server==0.0.2
python-language-server==0.21.4
pytz==2018.7
PyYAML==3.13
requests==2.21.0
rope==0.11.0
rsa==3.4.2
s3transfer==0.1.13
scipy==1.2.0
six==1.12.0
snowballstemmer==1.2.1
SQLAlchemy==1.2.15
sqlalchemy-redshift==0.7.2
sqlparse==0.2.4
traitlets==4.3.2
uritemplate==3.0.0
urllib3==1.24.1
wcwidth==0.1.7
yapf==0.25.0
```

**Comment by j-bennet** [comment]
I agree, that's annoying. For the reference for someone wanting to take this on, here is where mycli handles reconnection:

https://github.com/dbcli/mycli/blob/6a3b5f3200db1a00053b87e3c80ff0242dd7f069/mycli/main.py#L654-L668

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/1009.
