### ISSUE TITLE
ERROR:  type "hstore" does not exists at character 8

### ISSUE THREAD

**Issue by saper** [dbcli/pgcli#991]
## Description
PostgreSQL server logs the following when using pgcli on a database that does not have `hstore` extension enabled:

    ERROR:  type "hstore" does not exist at character 8
    STATEMENT:   SELECT 'hstore'::regtype::oid

## Your environment
PostgreSQL 11.1 Server, pgcli 1.11.0 (all running on FreeBSD 11)

Also confirmed on: PostgreSQL 9.5.1 server upgraded from 8.4 (all running on Debian Linux), pgcli 1.11.0 (FreeBSD 11)

- [x] Please provide your OS and version information.

FreeBSD 11.1

- [x] Please provide your CLI version.

1.11.0 from FreeBSD ports (py36-pgcli-1.11.0)

- [x] What is the output of ``pip freeze`` command.

````
alabaster==0.7.6
args==0.1.0
arm==1.4.5.0
asn1crypto==0.22.0
attrs==17.3.0
Babel==2.5.3
blinker==1.4
boto==2.48.0
cdiff==1.0
certifi==2018.4.16
cffi==1.11.5
characteristic==14.3.0
chardet==3.0.4
clint==0.5.1
configparser==3.5.0
cryptography==2.1.4
cvs2svn==2.5.0
Cython==0.26
dnet==1.12
dnspython==1.15.0
docopt==0.6.2
docutils==0.14
ec2-cli-tools==1.5
enum34==1.1.6
feedparser==5.2.1
flake8==3.5.0
funcsigs==1.0.2
gdbm==0.0.0
gevent==1.2.2
greenlet==0.4.13
gyp==0.1
httplib2==0.11.3
idna==2.6
imagesize==0.7.1
ipaddr==2.2.0
ipaddress==1.0.22
isc==2.0
Jinja2==2.10
jsonpatch==1.21
jsonpointer==1.9
MarkupSafe==1.0
maxminddb==1.3.0
mccabe==0.6.1
mercurial==4.6
nyx==2.0.4
oauth2client==4.1.2
oauthlib==1.1.2
pep8==1.7.1
pexpect==4.2.0
Pillow==5.0.0
pipenv==2018.5.18
pluggy==0.6.0
ply==3.11
psycopg2==2.7.5
ptyprocess==0.5.1
py==1.5.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycodestyle==2.3.1
pycparser==2.18
pycrypto==2.6.1
pyflakes==1.5.0
pyhdb==0.3.1
PyJWT==1.4.0
pylibpcap==0.6.4
pyOpenSSL==17.5.0
PySocks==1.6.8
PyStemmer==1.3.0
pytest==3.4.2
python-potr==1.0.1
pytz==2018.4
PyYAML==3.12
requests==2.18.4
requests-oauthlib==0.6.2
rsa==3.4.2
scapy===unknown.version
schema==0.4.0
service-identity==17.0.0
six==1.11.0
snowballstemmer==1.2.0
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
sqlite3==0.0.0
stem==1.6.0
Tkinter==0.0.0
tox==2.3.1
Twisted-Core==15.2.1
Twisted-Pair==15.2.1
txsocksx==1.15.0.2.post1
txtorcon==0.14.0
typing==3.6.4
ujson==1.35
urllib3==1.22
vcversioner==2.14.0.0
virtualenv==15.1.0
virtualenv-clone==0.3.0
webencodings==0.5.1
xmpppy==0.5.0
youtube-dl==2016.1.1
zope.interface==4.1.3
````

**Comment by saper** [comment]
Looks like 

     select t.oid FROM pg_type t WHERE t.typname = 'hstore' and t.typisdefined

may provide `hstore` oid without generating an error message on the server.

Borrowed-from: [psycopg2](https://github.com/psycopg/psycopg2/blob/0236c68da94c7ca884e3ced1b2c53ad84812678a/lib/_json.py#L192)

**Comment by j-bennet** [comment]
Closed via https://github.com/dbcli/pgcli/pull/992.
